export const AGENT_SETUP_COPY = {
  docs: "Docs",
  install: "Install",
  retryInstall: "Retry Install",
  updateInstalls: "Update installs",
  updatingInstalls: "Updating...",
  updateInstallsStarted: "Updating local harness installs.",
  installFailed: "Install failed",
  justInstalled: "Just installed",
  installing: "Installing...",
  seedHydrating: "Finishing setup...",
  apiKeys: "API Keys",
  cliLogin: "CLI Login",
  saveCredential: "Save",
  savedInKeychain: "Saved in Keychain",
  changeSavedCredential: "Change",
  loginAction: "Get login command",
  refreshLoginAction: "Refresh login command",
  noCredentials: "This agent has no configurable credentials.",
  savedChangesNotice: "Saved credentials will apply after the runtime restarts.",
  applyAndRestart: "Apply & Restart Runtime",
  applying: "Applying...",
  done: "Done",
  close: "Close",
  credentialPlaceholder: "Paste API key",
  subtitles: {
    ready: "Update authentication credentials",
    unsupported: "Runtime compatibility issue",
    retryInstall: "Retry installation",
    install: "Install and configure",
    credentials: "Configure credentials",
  },
} as const;
