import type { TranscriptState } from "@anyharness/sdk";
import type { PendingPromptQueueEntry } from "@proliferate/product-domain/chats/pending-prompts/pending-prompt-queue";

export const PLAYGROUND_SUBAGENT_WAKE_QUEUE: PendingPromptQueueEntry[] = [{
  seq: 7,
  text: [
    'Subagent "runtime-server-sdk-survey" completed a turn.',
    "",
    "Child session: b5870e25-f4f7-a08b-61d6e703177b",
    "Session link: link-runtime-server-sdk-survey",
    "Outcome: completed",
    "Last child event seq: 184",
    "",
    "Use the subagent tools to inspect the child session before continuing.",
  ].join("\n"),
  contentParts: [],
  isBeingEdited: false,
  promptProvenance: {
    type: "subagentWake",
    sessionLinkId: "link-runtime-server-sdk-survey",
    completionId: "completion-runtime-server-sdk-survey",
    label: "runtime-server-sdk-survey",
  },
}];

export const PLAYGROUND_SUBAGENT_WAKE_TRANSCRIPT: TranscriptState = {
  sessionMeta: {
    sessionId: "playground-subagent-wake",
    title: "Parent delegation session",
    updatedAt: "2026-04-21T02:34:00Z",
    nativeSessionId: null,
    sourceAgentKind: "codex",
  },
  turnOrder: ["turn-subagent-wake"],
  turnsById: {
    "turn-subagent-wake": {
      turnId: "turn-subagent-wake",
      itemOrder: ["assistant-before-wake", "scheduled-wake-message"],
      startedAt: "2026-04-21T02:31:45Z",
      completedAt: "2026-04-21T02:34:00Z",
      stopReason: "end_turn",
      fileBadges: [],
    },
  },
  itemsById: {
    "assistant-before-wake": {
      kind: "assistant_prose",
      itemId: "assistant-before-wake",
      turnId: "turn-subagent-wake",
      status: "completed",
      sourceAgentKind: "codex",
      messageId: null,
      title: null,
      nativeToolName: null,
      parentToolCallId: null,
      rawInput: undefined,
      rawOutput: undefined,
      contentParts: [],
      timestamp: "2026-04-21T02:31:45Z",
      startedSeq: 1,
      lastUpdatedSeq: 1,
      completedSeq: 1,
      completedAt: "2026-04-21T02:31:45Z",
      text: "I scheduled a wake for the runtime survey child and continued the main investigation.",
      isStreaming: false,
    },
    "scheduled-wake-message": {
      kind: "user_message",
      itemId: "scheduled-wake-message",
      turnId: "turn-subagent-wake",
      status: "completed",
      sourceAgentKind: "system",
      messageId: null,
      title: null,
      nativeToolName: null,
      parentToolCallId: null,
      rawInput: undefined,
      rawOutput: undefined,
      contentParts: [],
      timestamp: "2026-04-21T02:34:00Z",
      startedSeq: 9,
      lastUpdatedSeq: 9,
      completedSeq: 9,
      completedAt: "2026-04-21T02:34:00Z",
      text: PLAYGROUND_SUBAGENT_WAKE_QUEUE[0].text,
      isStreaming: false,
      promptProvenance: PLAYGROUND_SUBAGENT_WAKE_QUEUE[0].promptProvenance,
    },
  },
  openAssistantItemId: null,
  openThoughtItemId: null,
  pendingInteractions: [],
  availableCommands: [],
  liveConfig: null,
  currentModeId: null,
  usageState: null,
  unknownEvents: [],
  isStreaming: false,
  lastSeq: 10,
  pendingPrompts: [],
  linkCompletionsByCompletionId: {
    "completion-runtime-server-sdk-survey": {
      relation: "subagent",
      completionId: "completion-runtime-server-sdk-survey",
      sessionLinkId: "link-runtime-server-sdk-survey",
      parentSessionId: "playground-subagent-wake",
      childSessionId: "b5870e25-f4f7-a08b-61d6e703177b",
      childTurnId: "turn-runtime-server-sdk-survey",
      childLastEventSeq: 184,
      outcome: "completed",
      label: "runtime-server-sdk-survey",
      seq: 8,
      timestamp: "2026-04-21T02:33:58Z",
    },
  },
  latestLinkCompletionBySessionLinkId: {
    "link-runtime-server-sdk-survey": "completion-runtime-server-sdk-survey",
  },
};
