/**
 * Synthesizes a single ESM barrel entry per design-system package.
 *
 * Why this exists: neither `@proliferate/ui` (65 exports) nor
 * `@proliferate/product-ui` (73) declares `exports["."]`, `main`, or
 * `module` — both are subpath-only packages. The design-sync converter
 * needs ONE entry whose exports become `window.ProliferateUI.*`, so we
 * generate that barrel from each package.json `exports` map.
 *
 * Collision handling: three names are exported by two subpaths each inside
 * `@proliferate/ui`. ESM drops ambiguous `export *` names silently, so each
 * is pinned explicitly below — explicit exports take precedence over
 * `export *`. Names follow the playground library registry
 * (apps/packages/product-client/src/components/playground/library/), which
 * is the repo's own CI-enforced naming authority.
 *
 * Output is gitignored; this generator is committed. Re-run before a build:
 *   node .design-sync/make-entries.mjs
 */
import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** Explicit winners for names exported by more than one subpath. */
const COLLISION_PINS = {
  "apps/packages/ui": [
    { name: "Checkbox", from: "./dist/primitives/Checkbox.js", exportName: "Checkbox" },
    {
      name: "CheckboxPrimitive",
      from: "./dist/primitives/checkbox-primitive.js",
      exportName: "Checkbox",
    },
    { name: "Tooltip", from: "./dist/primitives/Tooltip.js", exportName: "Tooltip" },
    {
      name: "TooltipPrimitive",
      from: "./dist/primitives/tooltip-primitive.js",
      exportName: "Tooltip",
    },
    { name: "Spinner", from: "./dist/primitives/Spinner.js", exportName: "Spinner" },
  ],
};

async function generate(pkgDir) {
  const pkgPath = resolve(repoRoot, pkgDir, "package.json");
  const pkg = JSON.parse(await readFile(pkgPath, "utf8"));
  const subpaths = Object.entries(pkg.exports ?? {})
    .map(([key, val]) => (typeof val === "string" ? [key, val] : [key, val?.import]))
    .filter(([, imp]) => typeof imp === "string" && imp.endsWith(".js"))
    .map(([, imp]) => imp)
    .sort();

  const missing = subpaths.filter((p) => !existsSync(resolve(repoRoot, pkgDir, p)));
  if (missing.length > 0) {
    throw new Error(
      `${pkg.name}: ${missing.length} export target(s) missing from dist — build the package first ` +
        `(e.g. pnpm -F "${pkg.name}..." build). First missing: ${missing[0]}`,
    );
  }

  const pins = COLLISION_PINS[pkgDir] ?? [];
  const lines = [
    "// GENERATED by .design-sync/make-entries.mjs — do not edit, do not commit.",
    `// Barrel entry for ${pkg.name}: ${subpaths.length} subpath exports.`,
    "",
    ...subpaths.map((p) => `export * from ${JSON.stringify(p)};`),
  ];

  if (pins.length > 0) {
    const modules = [...new Set(pins.map((p) => p.from))].sort();
    const alias = new Map(modules.map((m, i) => [m, `_m${i}`]));
    lines.push(
      "",
      "// Collision pins — explicit exports take precedence over `export *`,",
      "// which would otherwise drop these names as ambiguous.",
      ...modules.map((m) => `import * as ${alias.get(m)} from ${JSON.stringify(m)};`),
      ...pins.map((p) => `export const ${p.name} = ${alias.get(p.from)}.${p.exportName};`),
    );
  }

  // The primary entry also re-exports the sibling DS package at runtime, so
  // one entry backs the whole surface the type barrel declares. Routing
  // product-ui through `extraEntries` instead would make the converter see
  // the same 79 names from two entries and warn [EXPORT_COLLISION].
  if (pkgDir === "apps/packages/ui") {
    lines.push(
      "",
      "// Sibling DS package — one entry backs the whole sanctioned surface.",
      'export * from "../product-ui/.ds-entry.mjs";',
    );
  }

  const outPath = resolve(repoRoot, pkgDir, ".ds-entry.mjs");
  await writeFile(outPath, `${lines.join("\n")}\n`, "utf8");
  console.log(
    `[ds-entry] ${pkg.name}: ${subpaths.length} subpaths` +
      (pins.length > 0 ? `, ${pins.length} collision pins` : "") +
      ` -> ${pkgDir}/.ds-entry.mjs`,
  );
  return { pkg, subpaths, pins };
}

/**
 * The converter discovers components from the package's TYPE entry, resolved
 * as `pkgJson.types` and falling back to `<pkgDir>/index.d.ts`. Neither
 * package declares `types`, so without this barrel discovery finds zero
 * components. It covers both packages because the DS surface the playground
 * registry sanctions spans both, and there are zero cross-package name
 * collisions (verified) — so one type entry can front the whole surface.
 */
async function generateTypeBarrel(primaryDir, allResults) {
  const lines = [
    "// GENERATED by .design-sync/make-entries.mjs — do not edit, do not commit.",
    "// Type entry for the design-sync converter's component discovery.",
    "",
  ];
  for (const { pkg, subpaths, pins } of allResults) {
    const rel = pkg.name === "@proliferate/ui" ? "." : "../product-ui";
    lines.push(`// ${pkg.name}`);
    for (const p of subpaths) {
      const dts = p.replace(/\.js$/, "");
      lines.push(`export * from ${JSON.stringify(`${rel}/${dts.replace(/^\.\//, "")}`)};`);
    }
    for (const p of pins) {
      const dts = p.from.replace(/\.js$/, "").replace(/^\.\//, "");
      lines.push(
        `export { ${p.exportName} as ${p.name} } from ${JSON.stringify(`${rel}/${dts}`)};`,
      );
    }
    lines.push("");
  }
  const outPath = resolve(repoRoot, primaryDir, "index.d.ts");
  await writeFile(outPath, `${lines.join("\n")}\n`, "utf8");
  console.log(`[ds-entry] type barrel -> ${primaryDir}/index.d.ts`);
}

const results = [];
for (const pkgDir of ["apps/packages/ui", "apps/packages/product-ui"]) {
  results.push(await generate(pkgDir));
}
await generateTypeBarrel("apps/packages/ui", results);
