import type { CoworkArtifactSummary, TranscriptState } from "@anyharness/sdk";
import type { PendingPromptQueueEntry } from "@proliferate/product-model/chats/pending-prompts/pending-prompt-queue";
import { toolCallItem } from "@/lib/domain/chat/__fixtures__/playground/tool-call-item-fixture";

const PLAYGROUND_ARTIFACT_SUMMARY: CoworkArtifactSummary = {
  id: "artifact-playground",
  path: "artifacts/status-board.tsx",
  type: "application/vnd.proliferate.react",
  title: "Status board",
  description: "Compact artifact row preview",
  createdAt: "2026-04-12T00:00:00Z",
  updatedAt: "2026-04-12T00:00:01Z",
  exists: true,
  sizeBytes: 2048,
  modifiedAt: "2026-04-12T00:00:01Z",
};

export const PLAYGROUND_COWORK_ARTIFACT_TOOL_CALL = toolCallItem({
  itemId: "tool-artifact",
  toolCallId: "tool-artifact",
  title: "Create artifact",
  nativeToolName: "mcp__cowork__create_artifact",
  semanticKind: "cowork_artifact_create",
  rawInput: {
    title: "Status board",
    path: "artifacts/status-board.tsx",
  },
  rawOutput: PLAYGROUND_ARTIFACT_SUMMARY,
});

const subagentItem = toolCallItem({
  itemId: "tool-agent",
  toolCallId: "tool-agent",
  title: "mcp__subagents__create_subagent",
  nativeToolName: "mcp__subagents__create_subagent",
  semanticKind: "subagent",
  rawInput: {
    agentKind: "codex",
    label: "repo-reviewer",
    modelId: "gpt-5.4",
    prompt: "Inspect the transcript rendering path and report whether nested tool calls use compact rows.",
  },
  rawOutput: {
    childSessionId: "child-repo-reviewer",
    sessionLinkId: "link-repo-reviewer",
    promptStatus: "running",
    wakeScheduleCreated: true,
    wakeScheduled: true,
  },
  contentParts: [
    {
      type: "tool_result_text",
      text: JSON.stringify({
        childSessionId: "child-repo-reviewer",
        sessionLinkId: "link-repo-reviewer",
        promptStatus: "running",
        wakeScheduleCreated: true,
        wakeScheduled: true,
      }),
    },
  ],
});

const subagentCommandItem = toolCallItem({
  itemId: "tool-agent-command",
  toolCallId: "tool-agent-command",
  parentToolCallId: "tool-agent",
  title: "npm test -- --runInBand",
  nativeToolName: "Bash",
  semanticKind: "terminal",
  rawInput: {
    command: "pnpm --dir desktop exec vitest run src/config/playground.test.ts",
  },
  contentParts: [
    {
      type: "terminal_output",
      terminalId: "terminal-playground",
      event: "output",
      data: "RUN  src/config/playground.test.ts\nPASS compact tool-call scenarios\n",
    },
  ],
});

const subagentReadItem = toolCallItem({
  itemId: "tool-agent-read",
  toolCallId: "tool-agent-read",
  parentToolCallId: "tool-agent",
  title: "Read ToolActionRow.tsx",
  nativeToolName: "Read",
  toolKind: "read",
  semanticKind: "file_read",
  contentParts: [
    {
      type: "file_read",
      path: "/Users/pablo/proliferate/desktop/src/components/workspace/chat/tool-calls/ToolActionRow.tsx",
      workspacePath: "desktop/src/components/workspace/chat/tool-calls/ToolActionRow.tsx",
      basename: "ToolActionRow.tsx",
      scope: "range",
      startLine: 1,
      endLine: 12,
      preview: "export function ToolActionRow() {\n  return null;\n}",
    },
  ],
});

const creationGroupItems = [
  subagentCreationFixture("tool-agent-api", "API Surface Check", "Check API surface consistency.", 1),
  subagentCreationFixture("tool-agent-tests", "Test Plan Review", "Review test coverage for delegated work.", 2),
];

const singleCreationItem = subagentCreationFixture(
  "tool-agent-single",
  "Runtime Survey",
  "Inspect the runtime server SDK path and report API mismatches.",
  1,
);

export const PLAYGROUND_SUBAGENT_CREATION_SINGLE_TRANSCRIPT: TranscriptState = {
  sessionMeta: {
    sessionId: "playground-subagent-creation-single",
    title: "Single subagent creation",
    updatedAt: "2026-04-12T00:00:02Z",
    nativeSessionId: null,
    sourceAgentKind: "codex",
  },
  turnOrder: ["turn-subagent-creation-single"],
  turnsById: {
    "turn-subagent-creation-single": {
      turnId: "turn-subagent-creation-single",
      itemOrder: [singleCreationItem.itemId],
      startedAt: "2026-04-12T00:00:00Z",
      completedAt: "2026-04-12T00:00:03Z",
      stopReason: "end_turn",
      fileBadges: [],
    },
  },
  itemsById: {
    [singleCreationItem.itemId]: {
      ...singleCreationItem,
      turnId: "turn-subagent-creation-single",
    },
  },
  openAssistantItemId: null,
  openThoughtItemId: null,
  pendingInteractions: [],
  availableCommands: [],
  liveConfig: null,
  currentModeId: null,
  usageState: null,
  unknownEvents: [],
  isStreaming: false,
  lastSeq: 3,
  pendingPrompts: [],
  linkCompletionsByCompletionId: {},
  latestLinkCompletionBySessionLinkId: {},
};

export const PLAYGROUND_SUBAGENT_CREATION_GROUP_TRANSCRIPT: TranscriptState = {
  sessionMeta: {
    sessionId: "playground-subagent-creations",
    title: "Subagent creation grouping",
    updatedAt: "2026-04-12T00:00:02Z",
    nativeSessionId: null,
    sourceAgentKind: "codex",
  },
  turnOrder: ["turn-subagent-creations"],
  turnsById: {
    "turn-subagent-creations": {
      turnId: "turn-subagent-creations",
      itemOrder: creationGroupItems.map((item) => item.itemId),
      startedAt: "2026-04-12T00:00:00Z",
      completedAt: "2026-04-12T00:00:03Z",
      stopReason: "end_turn",
      fileBadges: [],
    },
  },
  itemsById: Object.fromEntries(creationGroupItems.map((item) => [item.itemId, item])),
  openAssistantItemId: null,
  openThoughtItemId: null,
  pendingInteractions: [],
  availableCommands: [],
  liveConfig: null,
  currentModeId: null,
  usageState: null,
  unknownEvents: [],
  isStreaming: false,
  lastSeq: 4,
  pendingPrompts: [],
  linkCompletionsByCompletionId: {},
  latestLinkCompletionBySessionLinkId: {},
};

export const PLAYGROUND_SUBAGENT_PARENT_SEND_TRANSCRIPT: TranscriptState = {
  sessionMeta: {
    sessionId: "playground-subagent-child",
    title: "Runtime Survey child",
    updatedAt: "2026-04-21T02:36:00Z",
    nativeSessionId: null,
    sourceAgentKind: "codex",
  },
  turnOrder: ["turn-parent-send"],
  turnsById: {
    "turn-parent-send": {
      turnId: "turn-parent-send",
      itemOrder: ["parent-sent-message", "child-response"],
      startedAt: "2026-04-21T02:35:00Z",
      completedAt: "2026-04-21T02:36:00Z",
      stopReason: "end_turn",
      fileBadges: [],
    },
  },
  itemsById: {
    "parent-sent-message": {
      kind: "user_message",
      itemId: "parent-sent-message",
      turnId: "turn-parent-send",
      status: "completed",
      sourceAgentKind: "system",
      messageId: null,
      title: null,
      nativeToolName: null,
      parentToolCallId: null,
      rawInput: undefined,
      rawOutput: undefined,
      contentParts: [],
      timestamp: "2026-04-21T02:35:00Z",
      startedSeq: 1,
      lastUpdatedSeq: 1,
      completedSeq: 1,
      completedAt: "2026-04-21T02:35:00Z",
      text: "Please inspect the runtime server SDK path for delegated-work regressions.",
      isStreaming: false,
      promptProvenance: {
        type: "agentSession",
        sourceSessionId: "playground-parent-session",
        sessionLinkId: "link-runtime-survey",
        label: "Parent delegation session",
      },
    },
    "child-response": {
      kind: "assistant_prose",
      itemId: "child-response",
      turnId: "turn-parent-send",
      status: "completed",
      sourceAgentKind: "codex",
      messageId: null,
      title: null,
      nativeToolName: null,
      parentToolCallId: null,
      rawInput: undefined,
      rawOutput: undefined,
      contentParts: [],
      timestamp: "2026-04-21T02:36:00Z",
      startedSeq: 2,
      lastUpdatedSeq: 2,
      completedSeq: 2,
      completedAt: "2026-04-21T02:36:00Z",
      text: "I will inspect the delegated-work identity path and report back.",
      isStreaming: false,
    },
  },
  openAssistantItemId: null,
  openThoughtItemId: null,
  pendingInteractions: [],
  availableCommands: [],
  liveConfig: null,
  currentModeId: null,
  usageState: null,
  unknownEvents: [],
  isStreaming: false,
  lastSeq: 2,
  pendingPrompts: [],
  linkCompletionsByCompletionId: {},
  latestLinkCompletionBySessionLinkId: {},
};

export const PLAYGROUND_SUBAGENT_TRANSCRIPT: TranscriptState = {
  sessionMeta: {
    sessionId: "playground-subagent",
    title: "Tool row playground",
    updatedAt: "2026-04-12T00:00:02Z",
    nativeSessionId: null,
    sourceAgentKind: "codex",
  },
  turnOrder: ["turn-subagent"],
  turnsById: {
    "turn-subagent": {
      turnId: "turn-subagent",
      itemOrder: ["assistant-intro", "tool-agent"],
      startedAt: "2026-04-12T00:00:00Z",
      completedAt: "2026-04-12T00:00:03Z",
      stopReason: "end_turn",
      fileBadges: [],
    },
  },
  itemsById: {
    "assistant-intro": {
      kind: "assistant_prose",
      itemId: "assistant-intro",
      turnId: "turn-subagent",
      status: "completed",
      sourceAgentKind: "codex",
      messageId: null,
      title: null,
      nativeToolName: null,
      parentToolCallId: null,
      rawInput: undefined,
      rawOutput: undefined,
      contentParts: [],
      timestamp: "2026-04-12T00:00:00Z",
      startedSeq: 1,
      lastUpdatedSeq: 1,
      completedSeq: 1,
      completedAt: "2026-04-12T00:00:00Z",
      text: "I will delegate the transcript check and inspect the nested activity.",
      isStreaming: false,
    },
    "tool-agent": subagentItem,
    "tool-agent-command": subagentCommandItem,
    "tool-agent-read": subagentReadItem,
  },
  openAssistantItemId: null,
  openThoughtItemId: null,
  pendingInteractions: [],
  availableCommands: [],
  liveConfig: null,
  currentModeId: null,
  usageState: null,
  unknownEvents: [],
  isStreaming: false,
  lastSeq: 4,
  pendingPrompts: [],
  linkCompletionsByCompletionId: {},
  latestLinkCompletionBySessionLinkId: {},
};

function subagentCreationFixture(
  itemId: string,
  label: string,
  prompt: string,
  seq: number,
) {
  return toolCallItem({
    itemId,
    toolCallId: itemId,
    turnId: "turn-subagent-creations",
    title: "mcp__subagents__create_subagent",
    nativeToolName: "mcp__subagents__create_subagent",
    semanticKind: "subagent",
    rawInput: {
      agentKind: "codex",
      label,
      modelId: "gpt-5.4",
      prompt,
    },
    rawOutput: {
      childSessionId: `child-${itemId}`,
      sessionLinkId: `link-${itemId}`,
      promptStatus: "queued",
      wakeScheduled: false,
    },
    startedSeq: seq,
    lastUpdatedSeq: seq,
    completedSeq: seq,
  });
}

export const PLAYGROUND_SUBAGENT_WAKE_QUEUE: PendingPromptQueueEntry[] = [{
  seq: 7,
  text: [
    'Subagent "runtime-server-sdk-survey" completed a turn.',
    "",
    "Child session: b5870e25-f4f7-a08b-61d6e703177b",
    "Session link: link-runtime-server-sdk-survey",
    "Outcome: completed",
    "Last child event seq: 184",
    "",
    "Use the subagent tools to inspect the child session before continuing.",
  ].join("\n"),
  contentParts: [],
  isBeingEdited: false,
  promptProvenance: {
    type: "subagentWake",
    sessionLinkId: "link-runtime-server-sdk-survey",
    completionId: "completion-runtime-server-sdk-survey",
    label: "runtime-server-sdk-survey",
  },
}];

export const PLAYGROUND_SUBAGENT_WAKE_TRANSCRIPT: TranscriptState = {
  sessionMeta: {
    sessionId: "playground-subagent-wake",
    title: "Parent delegation session",
    updatedAt: "2026-04-21T02:34:00Z",
    nativeSessionId: null,
    sourceAgentKind: "codex",
  },
  turnOrder: ["turn-subagent-wake"],
  turnsById: {
    "turn-subagent-wake": {
      turnId: "turn-subagent-wake",
      itemOrder: ["assistant-before-wake", "scheduled-wake-message"],
      startedAt: "2026-04-21T02:31:45Z",
      completedAt: "2026-04-21T02:34:00Z",
      stopReason: "end_turn",
      fileBadges: [],
    },
  },
  itemsById: {
    "assistant-before-wake": {
      kind: "assistant_prose",
      itemId: "assistant-before-wake",
      turnId: "turn-subagent-wake",
      status: "completed",
      sourceAgentKind: "codex",
      messageId: null,
      title: null,
      nativeToolName: null,
      parentToolCallId: null,
      rawInput: undefined,
      rawOutput: undefined,
      contentParts: [],
      timestamp: "2026-04-21T02:31:45Z",
      startedSeq: 1,
      lastUpdatedSeq: 1,
      completedSeq: 1,
      completedAt: "2026-04-21T02:31:45Z",
      text: "I scheduled a wake for the runtime survey child and continued the main investigation.",
      isStreaming: false,
    },
    "scheduled-wake-message": {
      kind: "user_message",
      itemId: "scheduled-wake-message",
      turnId: "turn-subagent-wake",
      status: "completed",
      sourceAgentKind: "system",
      messageId: null,
      title: null,
      nativeToolName: null,
      parentToolCallId: null,
      rawInput: undefined,
      rawOutput: undefined,
      contentParts: [],
      timestamp: "2026-04-21T02:34:00Z",
      startedSeq: 9,
      lastUpdatedSeq: 9,
      completedSeq: 9,
      completedAt: "2026-04-21T02:34:00Z",
      text: PLAYGROUND_SUBAGENT_WAKE_QUEUE[0].text,
      isStreaming: false,
      promptProvenance: PLAYGROUND_SUBAGENT_WAKE_QUEUE[0].promptProvenance,
    },
  },
  openAssistantItemId: null,
  openThoughtItemId: null,
  pendingInteractions: [],
  availableCommands: [],
  liveConfig: null,
  currentModeId: null,
  usageState: null,
  unknownEvents: [],
  isStreaming: false,
  lastSeq: 10,
  pendingPrompts: [],
  linkCompletionsByCompletionId: {
    "completion-runtime-server-sdk-survey": {
      relation: "subagent",
      completionId: "completion-runtime-server-sdk-survey",
      sessionLinkId: "link-runtime-server-sdk-survey",
      parentSessionId: "playground-subagent-wake",
      childSessionId: "b5870e25-f4f7-a08b-61d6e703177b",
      childTurnId: "turn-runtime-server-sdk-survey",
      childLastEventSeq: 184,
      outcome: "completed",
      label: "runtime-server-sdk-survey",
      seq: 8,
      timestamp: "2026-04-21T02:33:58Z",
    },
  },
  latestLinkCompletionBySessionLinkId: {
    "link-runtime-server-sdk-survey": "completion-runtime-server-sdk-survey",
  },
};
