export const COMPUTE_COPY = {
  title: "Compute",
  description: "SSH targets and runtimes available to cloud-dispatchable agent work. Each target gets an icon and color for quick visual identification.",
  addSshTarget: "Add SSH target",
  createEnrollmentCommand: "Create enrollment command",
  save: "Save",
  saveSuccess: "Target settings saved.",
  saveError: "Could not save target settings.",
  testConnection: "Test connection",
  testConnectionSuccess: "Connection succeeded through",
  testConnectionError: "Could not reach AnyHarness through SSH.",
  emptyTitle: "No cloud compute targets yet",
  emptyDescription: "Connect an SSH machine or enable a managed cloud target to run work remotely.",
  selectTargetTitle: "No target selected",
  selectTargetDescription: "Choose a target from the list to review readiness, launch auth, direct access, and appearance settings.",
  targetFallbackTitle: "Target",
  installCommandLabel: "Run this on the target machine",
  appearanceHelp: "Shown alongside this target's name throughout the app.",
  directSshHelp: "How Desktop tunnels into this target's AnyHarness runtime. These values are stored locally on this Desktop.",
  directSshUnavailable: "Direct SSH access applies to SSH targets. Managed cloud and local targets use their own runtime connection path.",
  directSshNotSshTarget: "This target does not use a Desktop-managed SSH tunnel.",
  archiveTarget: "Archive target",
  archiveConfirm: "Archive this compute target?",
  archiveError: "Could not archive target.",
} as const;
