/**
 * Pi Manager Extension — string template written to sandbox filesystem.
 *
 * Registers manager tools so Pi can call them during coworker chat sessions.
 * Auto-discovered by pi-acp from ~/.pi/agent/extensions/.
 *
 * Environment variables consumed at runtime inside the sandbox:
 *   PROLIFERATE_GATEWAY_URL        — Gateway base URL
 *   PROLIFERATE_GATEWAY_AUTH_TOKEN  — Bearer token for control-plane API
 *   PROLIFERATE_MANAGER_SESSION_ID  — Session ID
 */

export const PI_MANAGER_EXTENSION = [
	'import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";',
	"",
	"// ---------------------------------------------------------------------------",
	"// Gateway connection — read from sandbox environment",
	"// ---------------------------------------------------------------------------",
	"",
	"const GATEWAY_URL = process.env.PROLIFERATE_GATEWAY_URL;",
	"const AUTH_TOKEN = process.env.PROLIFERATE_GATEWAY_AUTH_TOKEN;",
	"const SESSION_ID = process.env.PROLIFERATE_MANAGER_SESSION_ID;",
	"",
	"// ---------------------------------------------------------------------------",
	"// JSON Schema helpers",
	"// ---------------------------------------------------------------------------",
	"",
	'const Str = (d: string) => ({ type: "string" as const, description: d });',
	'const OptStr = (d: string) => ({ type: "string" as const, description: d, nullable: true } as const);',
	'const EmptyObj = { type: "object" as const, properties: {}, required: [] as string[] };',
	"",
	"function Obj(props: Record<string, unknown>, required?: string[]) {",
	"	return {",
	'		type: "object" as const,',
	"		properties: props,",
	"		...(required ? { required } : {}),",
	"	};",
	"}",
	"",
	"// ---------------------------------------------------------------------------",
	"// Shared HTTP helpers",
	"// ---------------------------------------------------------------------------",
	"",
	"function requireEnv() {",
	"	if (!GATEWAY_URL || !AUTH_TOKEN || !SESSION_ID) {",
	"		throw new Error(",
	'			"Missing required environment variables: PROLIFERATE_GATEWAY_URL, PROLIFERATE_GATEWAY_AUTH_TOKEN, PROLIFERATE_MANAGER_SESSION_ID",',
	"		);",
	"	}",
	"}",
	"",
	"async function executeToolViaGateway(",
	"	toolName: string,",
	"	args: Record<string, unknown>,",
	"): Promise<string> {",
	"	requireEnv();",
	"",
	"	const url = `${GATEWAY_URL}/proliferate/${SESSION_ID}/manager/tools/execute`;",
	"	const response = await fetch(url, {",
	'		method: "POST",',
	"		headers: {",
	"			Authorization: `Bearer ${AUTH_TOKEN}`,",
	'			"Content-Type": "application/json",',
	"		},",
	"		body: JSON.stringify({",
	"			toolName,",
	"			args,",
	"		}),",
	"	});",
	"",
	"	if (!response.ok) {",
	'		const body = await response.text().catch(() => "");',
	"		const safeBody = body.replace(/[\\n\\r]/g, ' ').slice(0, 200);",
	"		throw new Error(`Manager tool ${toolName} failed (${response.status}): ${safeBody}`);",
	"	}",
	"",
	"	const json = (await response.json()) as { result?: string };",
	"	return json.result ?? JSON.stringify(json);",
	"}",
	"",
	"// ---------------------------------------------------------------------------",
	"// Extension entry point",
	"// ---------------------------------------------------------------------------",
	"",
	"export default function (pi: ExtensionAPI) {",
	"	// spawn_child_task",
	"	pi.registerTool({",
	'		name: "spawn_child_task",',
	'		label: "Spawn Child Task",',
	'		description: "Spawn a new child coding task session. The session inherits the coworker\'s repo and baseline settings unless a specific repo configurationId is provided. Returns the session ID.",',
	'		parameters: Obj({ title: Str("Short title describing the task"), instructions: Str("Detailed instructions for the coding agent"), repo: OptStr("configurationId for the target repo (from list_repos). If omitted, inherits the coworker\'s default repo.") }, ["title", "instructions"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("spawn_child_task", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// list_children",
	"	pi.registerTool({",
	'		name: "list_children",',
	'		label: "List Children",',
	'		description: "List all child task sessions spawned by this coworker.",',
	"		parameters: EmptyObj,",
	"		async execute() {",
	'			const text = await executeToolViaGateway("list_children", {});',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// inspect_child",
	"	pi.registerTool({",
	'		name: "inspect_child",',
	'		label: "Inspect Child",',
	'		description: "Get detailed status of a child task session including runtime status, operator status, outcome, and summary. The child must be running — use wake_child first if it is paused.",',
	'		parameters: Obj({ session_id: Str("The child session ID to inspect") }, ["session_id"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("inspect_child", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// message_child",
	"	pi.registerTool({",
	'		name: "message_child",',
	'		label: "Message Child",',
	'		description: "Send a follow-up message to a running child task session. The child must be running — use wake_child first if it is paused.",',
	'		parameters: Obj({ session_id: Str("The child session ID to message"), content: Str("The message content to send") }, ["session_id", "content"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("message_child", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// cancel_child",
	"	pi.registerTool({",
	'		name: "cancel_child",',
	'		label: "Cancel Child",',
	'		description: "Cancel a running child task session.",',
	'		parameters: Obj({ session_id: Str("The child session ID to cancel") }, ["session_id"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("cancel_child", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// wake_child",
	"	pi.registerTool({",
	'		name: "wake_child",',
	'		label: "Wake Child",',
	'		description: "Wake a paused child session by starting its sandbox. Required before inspect_child or message_child if the child is not running.",',
	'		parameters: Obj({ session_id: Str("The child session ID to wake") }, ["session_id"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("wake_child", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// list_repos",
	"	pi.registerTool({",
	'		name: "list_repos",',
	'		label: "List Repos",',
	'		description: "List all configured repos for the organization. Returns repo names, URLs, and configurationIds that can be passed to spawn_child_task.",',
	"		parameters: EmptyObj,",
	"		async execute() {",
	'			const text = await executeToolViaGateway("list_repos", {});',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// list_capabilities",
	"	pi.registerTool({",
	'		name: "list_capabilities",',
	'		label: "List Capabilities",',
	'		description: "List available action capabilities and their current permission modes.",',
	"		parameters: EmptyObj,",
	"		async execute() {",
	'			const text = await executeToolViaGateway("list_capabilities", {});',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// invoke_action",
	"	pi.registerTool({",
	'		name: "invoke_action",',
	'		label: "Invoke Action",',
	'		description: "Invoke an external action through the action boundary (e.g., create a Linear issue, post a Slack message). Actions may require approval.",',
	'		parameters: Obj({ integration: Str(\'The integration identifier (e.g., "linear", "sentry", "github", "connector:<id>")\'), action: Str("The action ID to invoke"), params: { type: "object" as const, description: "Action-specific parameters" } }, ["integration", "action", "params"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("invoke_action", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"}",
].join("\n");
