/**
 * Pi Manager Extension — string template written to sandbox filesystem.
 *
 * Registers manager tools so Pi can call them during manager wake cycles.
 * Auto-discovered by pi-acp from ~/.pi/agent/extensions/.
 *
 * Environment variables consumed at runtime inside the sandbox:
 *   PROLIFERATE_GATEWAY_URL        — Gateway base URL
 *   PROLIFERATE_GATEWAY_AUTH_TOKEN  — Bearer token for control-plane API
 *   PROLIFERATE_MANAGER_SESSION_ID  — Session ID
 */

// biome-ignore lint: template string is intentionally a code template
export const PI_MANAGER_EXTENSION = [
	'import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";',
	"",
	"// ---------------------------------------------------------------------------",
	"// Gateway connection — read from sandbox environment",
	"// ---------------------------------------------------------------------------",
	"",
	"const GATEWAY_URL = process.env.PROLIFERATE_GATEWAY_URL;",
	"const AUTH_TOKEN = process.env.PROLIFERATE_GATEWAY_AUTH_TOKEN;",
	"const SESSION_ID = process.env.PROLIFERATE_MANAGER_SESSION_ID;",
	"",
	"// ---------------------------------------------------------------------------",
	"// Run context — populated by claim_run tool at the start of each wake cycle",
	"// ---------------------------------------------------------------------------",
	"",
	"let currentWorkerRunId: string | null = null;",
	"let currentWorkerId: string | null = null;",
	"",
	"// ---------------------------------------------------------------------------",
	"// JSON Schema helpers",
	"// ---------------------------------------------------------------------------",
	"",
	'const Str = (d: string) => ({ type: "string" as const, description: d });',
	'const OptStr = (d: string) => ({ type: "string" as const, description: d, nullable: true } as const);',
	'const OptNum = (d: string) => ({ type: "number" as const, description: d, nullable: true } as const);',
	'const EmptyObj = { type: "object" as const, properties: {}, required: [] as string[] };',
	"",
	"function Obj(props: Record<string, unknown>, required?: string[]) {",
	"	return {",
	'		type: "object" as const,',
	"		properties: props,",
	"		...(required ? { required } : {}),",
	"	};",
	"}",
	"",
	"// ---------------------------------------------------------------------------",
	"// Shared HTTP helpers",
	"// ---------------------------------------------------------------------------",
	"",
	"function requireEnv() {",
	"	if (!GATEWAY_URL || !AUTH_TOKEN || !SESSION_ID) {",
	"		throw new Error(",
	'			"Missing required environment variables: PROLIFERATE_GATEWAY_URL, PROLIFERATE_GATEWAY_AUTH_TOKEN, PROLIFERATE_MANAGER_SESSION_ID",',
	"		);",
	"	}",
	"}",
	"",
	"async function executeToolViaGateway(",
	"	toolName: string,",
	"	args: Record<string, unknown>,",
	"): Promise<string> {",
	"	requireEnv();",
	"	if (!currentWorkerRunId) {",
	"		throw new Error(",
	'			"No active worker run. Call claim_run first to claim a wake event.",',
	"		);",
	"	}",
	"",
	"	const url = `${GATEWAY_URL}/proliferate/${SESSION_ID}/manager/tools/execute`;",
	"	const response = await fetch(url, {",
	'		method: "POST",',
	"		headers: {",
	"			Authorization: `Bearer ${AUTH_TOKEN}`,",
	'			"Content-Type": "application/json",',
	"		},",
	"		body: JSON.stringify({",
	"			toolName,",
	"			args,",
	"			workerRunId: currentWorkerRunId,",
	"			workerId: currentWorkerId,",
	"		}),",
	"	});",
	"",
	"	if (!response.ok) {",
	'		const body = await response.text().catch(() => "");',
	"		const safeBody = body.replace(/[\\n\\r]/g, ' ').slice(0, 200);",
	"		throw new Error(`Manager tool ${toolName} failed (${response.status}): ${safeBody}`);",
	"	}",
	"",
	"	const json = (await response.json()) as { result?: string };",
	"	return json.result ?? JSON.stringify(json);",
	"}",
	"",
	"// ---------------------------------------------------------------------------",
	"// Extension entry point",
	"// ---------------------------------------------------------------------------",
	"",
	"export default function (pi: ExtensionAPI) {",
	"	// claim_run",
	"	pi.registerTool({",
	'		name: "claim_run",',
	'		label: "Claim Run",',
	"		description:",
	'			"Claim the next pending wake event and start a worker run. MUST be called at the start of each wake cycle before using any other tools. Returns the full run context including wake event details, worker info, and source data.",',
	"		parameters: EmptyObj,",
	"		async execute() {",
	"			requireEnv();",
	"			const url = `${GATEWAY_URL}/proliferate/${SESSION_ID}/manager/runs/claim`;",
	"			const response = await fetch(url, {",
	'				method: "POST",',
	"				headers: {",
	"					Authorization: `Bearer ${AUTH_TOKEN}`,",
	'					"Content-Type": "application/json",',
	"				},",
	"				body: JSON.stringify({}),",
	"			});",
	"			if (!response.ok) {",
	'				const body = await response.text().catch(() => "");',
	"				throw new Error(`claim_run failed (${response.status}): ${body}`);",
	"			}",
	"			const result = await response.json();",
	'			if (result.status === "idle") {',
	"				currentWorkerRunId = null;",
	"				currentWorkerId = null;",
	'				return { content: [{ type: "text" as const, text: JSON.stringify({ status: "idle", message: "No pending wake events to process." }) }] };',
	"			}",
	"			currentWorkerRunId = result.workerRunId ?? null;",
	"			currentWorkerId = result.workerId ?? null;",
	'			return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };',
	"		},",
	"	});",
	"",
	"	// spawn_child_task",
	"	pi.registerTool({",
	'		name: "spawn_child_task",',
	'		label: "Spawn Child Task",',
	'		description: "Spawn a new child coding task session. The session inherits the coworker\'s repo and baseline settings. Returns the session ID.",',
	'		parameters: Obj({ title: Str("Short title describing the task"), instructions: Str("Detailed instructions for the coding agent") }, ["title", "instructions"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("spawn_child_task", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// list_children",
	"	pi.registerTool({",
	'		name: "list_children",',
	'		label: "List Children",',
	'		description: "List all child task sessions spawned during this run.",',
	"		parameters: EmptyObj,",
	"		async execute() {",
	'			const text = await executeToolViaGateway("list_children", {});',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// inspect_child",
	"	pi.registerTool({",
	'		name: "inspect_child",',
	'		label: "Inspect Child",',
	'		description: "Get detailed status of a child task session including runtime status, operator status, outcome, and summary.",',
	'		parameters: Obj({ session_id: Str("The child session ID to inspect") }, ["session_id"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("inspect_child", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// message_child",
	"	pi.registerTool({",
	'		name: "message_child",',
	'		label: "Message Child",',
	'		description: "Send a follow-up message to a running child task session.",',
	'		parameters: Obj({ session_id: Str("The child session ID to message"), content: Str("The message content to send") }, ["session_id", "content"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("message_child", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// cancel_child",
	"	pi.registerTool({",
	'		name: "cancel_child",',
	'		label: "Cancel Child",',
	'		description: "Cancel a running child task session.",',
	'		parameters: Obj({ session_id: Str("The child session ID to cancel") }, ["session_id"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("cancel_child", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// read_source",
	"	pi.registerTool({",
	'		name: "read_source",',
	'		label: "Read Source",',
	'		description: "Read data from a connected source binding (Sentry issues, Linear tickets, GitHub issues/PRs). Use list_source_bindings first to discover available bindings.",',
	'		parameters: Obj({ binding_id: Str("The binding ID to query (from list_source_bindings)"), cursor: OptStr("Pagination cursor from a previous query"), limit: OptNum("Max items to return (1-100, default 25)") }, ["binding_id"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("read_source", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// get_source_item",
	"	pi.registerTool({",
	'		name: "get_source_item",',
	'		label: "Get Source Item",',
	'		description: "Get detailed information about a single source item by its reference ID.",',
	'		parameters: Obj({ binding_id: Str("The binding ID this item belongs to"), item_ref: Str("The source-specific item reference (e.g., issue ID)") }, ["binding_id", "item_ref"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("get_source_item", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// list_source_bindings",
	"	pi.registerTool({",
	'		name: "list_source_bindings",',
	'		label: "List Source Bindings",',
	'		description: "List all connected source bindings for this coworker. Returns binding IDs, source types (sentry/linear/github), and labels.",',
	"		parameters: EmptyObj,",
	"		async execute() {",
	'			const text = await executeToolViaGateway("list_source_bindings", {});',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// list_capabilities",
	"	pi.registerTool({",
	'		name: "list_capabilities",',
	'		label: "List Capabilities",',
	'		description: "List available action capabilities and their current permission modes.",',
	"		parameters: EmptyObj,",
	"		async execute() {",
	'			const text = await executeToolViaGateway("list_capabilities", {});',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// invoke_action",
	"	pi.registerTool({",
	'		name: "invoke_action",',
	'		label: "Invoke Action",',
	'		description: "Invoke an external action through the action boundary (e.g., create a Linear issue, post a Slack message). Actions may require approval.",',
	'		parameters: Obj({ integration: Str(\'The integration identifier (e.g., "linear", "sentry", "github", "connector:<id>")\'), action: Str("The action ID to invoke"), params: { type: "object" as const, description: "Action-specific parameters" } }, ["integration", "action", "params"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("invoke_action", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// send_notification",
	"	pi.registerTool({",
	'		name: "send_notification",',
	'		label: "Send Notification",',
	'		description: "Send a notification to the human operator (in-app and/or Slack). Use this for status updates, escalations, or when human attention is needed.",',
	'		parameters: Obj({ message: Str("The notification message"), severity: OptStr("Notification severity level: info, warning, or error") }, ["message"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("send_notification", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// request_approval",
	"	pi.registerTool({",
	'		name: "request_approval",',
	'		label: "Request Approval",',
	'		description: "Pause execution and request human approval before proceeding with a significant action.",',
	'		parameters: Obj({ description: Str("What you want to do and why approval is needed") }, ["description"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("request_approval", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// skip_run",
	"	pi.registerTool({",
	'		name: "skip_run",',
	'		label: "Skip Run",',
	'		description: "Declare this run as no-action-needed. Use during triage when the wake event does not require any work.",',
	'		parameters: Obj({ reason: Str("Why no action is needed") }, ["reason"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("skip_run", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"",
	"	// complete_run",
	"	pi.registerTool({",
	'		name: "complete_run",',
	'		label: "Complete Run",',
	'		description: "Finalize this run with a summary. Call this after all child tasks are done or after orchestration is complete.",',
	'		parameters: Obj({ summary: Str("Summary of what was accomplished during this run") }, ["summary"]),',
	"		async execute(_toolCallId, params) {",
	'			const text = await executeToolViaGateway("complete_run", params);',
	'			return { content: [{ type: "text" as const, text }] };',
	"		},",
	"	});",
	"}",
].join("\n");
