import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  ALLOWED_ANNOTATION_KEYS,
  KNOWN_RULES,
  KNOWN_UIDS,
  LOG_RULE_UID,
  REPO_ROOT,
  assertLogAnnotationsOnlyOnLogRule,
  assertPrivateReceiptPath,
  canonicalize,
  detectDrift,
  normalizeRule,
  queryChecksum,
  redact,
  runApply,
  runCheck,
  runExport,
  runRestore,
  sha256,
  validateOverlayDocument,
  verifyTarget,
  verifyUidAllowlist,
} from "./grafana-alerting.mjs";
import {
  ALERTMANAGER_CONFIG,
  TARGET,
  WORKSPACE_BASE_URL,
  assertOperatorAccount,
  createGrafanaClient,
  resolveSecretField,
  ruleFromRulerEntry,
} from "./grafana-client.mjs";
import { extractQueryModel } from "./grafana-alerting.mjs";

// --- Fixtures: an in-memory Grafana behind a fake fetch (transport seam) -----

function rawRule(uid, title, extra = {}) {
  return {
    uid,
    title,
    condition: "C",
    data: [{ refId: "A", model: { expr: `metric{uid="${uid}"}` } }],
    noDataState: "NoData",
    execErrState: "Error",
    for: "5m",
    ruleGroup: "prod-alerts",
    folderUID: "prod-folder",
    isPaused: false,
    labels: {},
    annotations: {},
    // volatile noise:
    id: Math.floor(Math.random() * 1000),
    updated: new Date().toISOString(),
    version: Math.floor(Math.random() * 10),
    provenance: "api",
    ...extra,
  };
}

function liveRulesFixture() {
  return KNOWN_RULES.map((r) => rawRule(r.uid, r.title));
}

function newState(rules = liveRulesFixture()) {
  return {
    rules: rules.map((r) => JSON.parse(JSON.stringify(r))),
    contactPoints: [{ uid: "slack1", name: "slack-ops-alerts", type: "slack", settings: {} }],
    notificationPolicy: { receiver: "slack-ops-alerts", routes: [{ receiver: "slack-eng-triage" }] },
    amConfig: {
      template_files: {},
      alertmanager_config: {
        receivers: [
          {
            name: "slack-eng-triage",
            grafana_managed_receiver_configs: [
              { uid: "s1", name: "slack-eng-triage", type: "slack", settings: { recipient: "#eng" }, secureFields: { token: true, url: true } },
            ],
          },
          {
            name: "slack-ops-alerts",
            grafana_managed_receiver_configs: [
              { uid: "s2", name: "slack-ops-alerts", type: "slack", settings: { recipient: "#ops" }, secureFields: { token: true, url: true } },
            ],
          },
        ],
        route: {
          receiver: "slack-eng-triage",
          routes: [
            {
              object_matchers: [["__grafana_autogenerated__", "=", "true"]],
              receiver: "slack-eng-triage",
              routes: [
                { object_matchers: [["__grafana_receiver__", "=", "slack-eng-triage"]], receiver: "slack-eng-triage", group_by: ["grafana_folder", "alertname"] },
                { object_matchers: [["__grafana_receiver__", "=", "slack-ops-alerts"]], receiver: "slack-ops-alerts", group_by: ["grafana_folder", "alertname"] },
              ],
            },
            { receiver: "slack-ops-alerts", object_matchers: [["severity", "=", "critical"]] },
          ],
        },
      },
    },
    requests: [],
    onWrite: null,
    onAmPost: null,
    nextUid: 1,
  };
}

// Mimic the server's behavior on Alertmanager config POST: secureSettings
// values are encrypted away into secureFields markers, and Grafana REGENERATES
// the autogenerated routing subtree to hold exactly one child per receiver.
function encryptAmConfig(config) {
  const stored = JSON.parse(JSON.stringify(config));
  for (const receiver of stored.alertmanager_config.receivers || []) {
    for (const cfg of receiver.grafana_managed_receiver_configs || []) {
      if (cfg.secureSettings) {
        cfg.secureFields = { ...(cfg.secureFields || {}) };
        for (const key of Object.keys(cfg.secureSettings)) {
          cfg.secureFields[key] = true;
        }
        delete cfg.secureSettings;
      }
    }
  }
  const autogen = (stored.alertmanager_config.route?.routes || []).find((r) =>
    (r.object_matchers || []).some((m) => m[0] === "__grafana_autogenerated__"),
  );
  if (autogen) {
    autogen.routes = (stored.alertmanager_config.receivers || []).map((r) => ({
      object_matchers: [["__grafana_receiver__", "=", r.name]],
      receiver: r.name,
      group_by: ["grafana_folder", "alertname"],
    }));
  }
  return stored;
}

function jsonResponse(status, body) {
  return {
    ok: status >= 200 && status < 300,
    status,
    text: async () => (body === undefined ? "" : JSON.stringify(body)),
  };
}

const API = "/api/v1/provisioning";

// Fake fetch implementing the provisioning routes the client uses. Only the
// transport is faked; the client under test is the real one.
function fakeGrafanaFetch(state) {
  return async (url, init = {}) => {
    const method = init.method || "GET";
    const parsed = new URL(url);
    const p = parsed.pathname;
    state.requests.push({ method, url, path: p, headers: init.headers || {}, body: init.body });
    if (method !== "GET" && state.onWrite) state.onWrite(method, p);
    const body = init.body ? JSON.parse(init.body) : undefined;

    if (method === "GET" && p === `${API}/alert-rules`) return jsonResponse(200, state.rules);
    const ruleMatch = p.match(new RegExp(`^${API}/alert-rules/(.+)$`));
    if (ruleMatch) {
      const uid = decodeURIComponent(ruleMatch[1]);
      const idx = state.rules.findIndex((r) => r.uid === uid);
      if (method === "GET") return idx >= 0 ? jsonResponse(200, state.rules[idx]) : jsonResponse(404, {});
      if (method === "PUT") {
        if (idx < 0) return jsonResponse(404, {});
        state.rules[idx] = body;
        return jsonResponse(200, body);
      }
    }
    if (p === `${API}/contact-points`) {
      if (method === "GET") return jsonResponse(200, state.contactPoints);
      if (method === "POST") {
        const created = { ...body, uid: `cp${state.nextUid++}` };
        state.contactPoints.push(created);
        return jsonResponse(202, created);
      }
    }
    const cpMatch = p.match(new RegExp(`^${API}/contact-points/(.+)$`));
    if (cpMatch) {
      const uid = decodeURIComponent(cpMatch[1]);
      const idx = state.contactPoints.findIndex((cp) => cp.uid === uid);
      if (idx < 0) return jsonResponse(404, {});
      if (method === "PUT") {
        state.contactPoints[idx] = { ...body, uid };
        return jsonResponse(202, state.contactPoints[idx]);
      }
      if (method === "DELETE") {
        state.contactPoints.splice(idx, 1);
        return jsonResponse(202, {});
      }
    }
    if (method === "GET" && p === `${API}/policies`) return jsonResponse(200, state.notificationPolicy);
    if (p === ALERTMANAGER_CONFIG) {
      if (method === "GET") return jsonResponse(200, state.amConfig);
      if (method === "POST") {
        state.amConfig = encryptAmConfig(body);
        if (state.onAmPost) state.onAmPost(state);
        return jsonResponse(202, { message: "configuration created" });
      }
    }
    return jsonResponse(404, {});
  };
}

function realClient(state, token = "test-token-value") {
  return createGrafanaClient({ fetchImpl: fakeGrafanaFetch(state), tokenProvider: () => token });
}

function tmpReceiptPath() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "grafana-e1-"));
  return path.join(dir, "receipt.json");
}

// A throwaway repo root whose checked-in overlay matches `rules` (the live
// fixtures), so the live-vs-checked-in gate passes unless a test tampers.
function fixtureRepo(rules = liveRulesFixture()) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "grafana-repo-"));
  const dir = path.join(root, "server/infra/observability/grafana");
  fs.mkdirSync(dir, { recursive: true });
  const overlay = {
    target: { ...TARGET },
    component: "proliferate-server",
    rules: KNOWN_RULES.map((k) => {
      const live = rules.find((r) => r.uid === k.uid);
      const annotations = {
        runbook_url: "https://example.invalid/runbook#anchor",
        ...(k.uid === LOG_RULE_UID
          ? {
              proliferate_log_group: "/ecs/proliferate-prod",
              proliferate_log_filter_pattern: "CRITICAL_FAILURE",
              proliferate_log_region: "us-east-1",
            }
          : {}),
      };
      return {
        uid: k.uid,
        title: k.title,
        severity: k.severity,
        labels: { proliferate_rule_uid: k.uid, proliferate_component: "proliferate-server", severity: k.severity },
        annotations,
        queryModel: extractQueryModel(live),
        queryChecksum: queryChecksum(live),
      };
    }),
  };
  fs.writeFileSync(path.join(dir, "production-alerts.json"), JSON.stringify(overlay));
  return root;
}

// --- Client transport: request construction + target lock -------------------

test("base URL derives only from the frozen TARGET constants", () => {
  assert.equal(
    WORKSPACE_BASE_URL,
    `https://${TARGET.grafanaWorkspaceId}.grafana-workspace.${TARGET.awsRegion}.amazonaws.com`,
  );
  assert.equal(WORKSPACE_BASE_URL, "https://g-e532d030d8.grafana-workspace.us-east-1.amazonaws.com");
});

test("listAlertRules issues a GET to the workspace provisioning path with a Bearer header", async () => {
  const state = newState();
  const client = realClient(state, "sekrit-token");
  const rules = await client.listAlertRules();
  assert.equal(rules.length, 5);
  const req = state.requests[0];
  assert.equal(req.method, "GET");
  assert.equal(req.url, `${WORKSPACE_BASE_URL}${API}/alert-rules`);
  assert.equal(req.headers.Authorization, "Bearer sekrit-token");
});

test("upsertAlertRule PUTs JSON to the rule path with X-Disable-Provenance", async () => {
  const state = newState();
  const client = realClient(state);
  const next = { ...state.rules[0], labels: { severity: "critical" } };
  await client.upsertAlertRule(next.uid, next);
  const req = state.requests.at(-1);
  assert.equal(req.method, "PUT");
  assert.equal(req.path, `${API}/alert-rules/${next.uid}`);
  assert.equal(req.headers["X-Disable-Provenance"], "true");
  assert.equal(req.headers["Content-Type"], "application/json");
  assert.deepEqual(JSON.parse(req.body).labels, { severity: "critical" });
});

test("HTTP errors surface only path and status, never host or token", async () => {
  const client = createGrafanaClient({
    fetchImpl: async () => jsonResponse(403, {}),
    tokenProvider: () => "sekrit-token",
  });
  await assert.rejects(client.listAlertRules(), (error) => {
    assert.match(error.message, /GET \/api\/v1\/provisioning\/alert-rules failed with HTTP 403/);
    assert.ok(!error.message.includes("sekrit"));
    assert.ok(!error.message.includes("amazonaws"));
    return true;
  });
});

test("ruler entries map to the provisioning shape with identical checksums", () => {
  const provisioning = rawRule("dfrmh7bc4yqrkf", "ALB 5xx > 10 in 5m");
  const rulerEntry = {
    for: provisioning.for,
    labels: {},
    annotations: {},
    grafana_alert: {
      uid: provisioning.uid,
      title: provisioning.title,
      condition: provisioning.condition,
      data: provisioning.data,
      no_data_state: provisioning.noDataState,
      exec_err_state: provisioning.execErrState,
      rule_group: provisioning.ruleGroup,
      namespace_uid: provisioning.folderUID,
      is_paused: false,
    },
  };
  const mapped = ruleFromRulerEntry(rulerEntry);
  assert.equal(queryChecksum(mapped), queryChecksum(provisioning));
});

test("listAlertRulesViaRuler flattens namespaces and maps entries", async () => {
  const provisioning = liveRulesFixture();
  const namespaces = {
    prod: [
      {
        name: "prod-alerts",
        rules: provisioning.map((r) => ({
          for: r.for,
          labels: {},
          annotations: {},
          grafana_alert: {
            uid: r.uid,
            title: r.title,
            condition: r.condition,
            data: r.data,
            no_data_state: r.noDataState,
            exec_err_state: r.execErrState,
            rule_group: r.ruleGroup,
            namespace_uid: r.folderUID,
            is_paused: false,
          },
        })),
      },
    ],
  };
  const requests = [];
  const client = createGrafanaClient({
    fetchImpl: async (url, init) => {
      requests.push({ url, method: init.method || "GET" });
      return jsonResponse(200, namespaces);
    },
    tokenProvider: () => "t",
  });
  const rules = await client.listAlertRulesViaRuler();
  assert.equal(requests[0].method, "GET");
  assert.equal(requests[0].url, `${WORKSPACE_BASE_URL}/api/ruler/grafana/api/v1/rules`);
  assert.equal(rules.length, 5);
  for (let i = 0; i < rules.length; i += 1) {
    assert.equal(queryChecksum(rules[i]), queryChecksum(provisioning[i]));
  }
});

// --- Secret resolution (fake execFile; value returned, never logged) ---------

// Fake execFile: answers sts get-caller-identity with `account`, then
// delegates secretsmanager calls to `onSecret`.
function fakeAws(account, onSecret) {
  const calls = [];
  const impl = async (cmd, args) => {
    calls.push({ cmd, args });
    if (args[0] === "sts") {
      return { stdout: JSON.stringify({ Account: account }) };
    }
    return onSecret(cmd, args);
  };
  return { impl, calls };
}

test("resolveSecretField checks caller identity, then parses the named field", async () => {
  const { impl, calls } = fakeAws(TARGET.awsAccount, async () => ({
    stdout: JSON.stringify({ grafanaWebhookSecret: "value-under-test" }),
  }));
  const value = await resolveSecretField("ops/example-app", "grafanaWebhookSecret", { execFileImpl: impl });
  assert.equal(value, "value-under-test");
  assert.deepEqual(calls[0].args.slice(0, 2), ["sts", "get-caller-identity"]);
  const sm = calls[1];
  assert.equal(sm.cmd, "aws");
  assert.deepEqual(sm.args.slice(0, 2), ["secretsmanager", "get-secret-value"]);
  assert.ok(sm.args.includes("ops/example-app"));
  assert.ok(sm.args.includes(TARGET.awsRegion));
});

test("a wrong AWS account is rejected before any secret read", async () => {
  const { impl, calls } = fakeAws("999999999999", async () => {
    throw new Error("secretsmanager must never be reached");
  });
  await assert.rejects(
    resolveSecretField("ops/example-app", "grafanaWebhookSecret", { execFileImpl: impl }),
    /not the fixed target account 157466816238/,
  );
  assert.equal(calls.filter((c) => c.args[0] === "secretsmanager").length, 0);
  // Direct gate check too.
  await assert.rejects(assertOperatorAccount(fakeAws("000000000000", async () => ({})).impl), /not the fixed target/);
  await assert.doesNotReject(assertOperatorAccount(fakeAws(TARGET.awsAccount, async () => ({})).impl));
});

test("resolveSecretField failures never echo secret material", async () => {
  const { impl } = fakeAws(TARGET.awsAccount, async () => {
    throw new Error("aws stderr containing something-sensitive");
  });
  await assert.rejects(resolveSecretField("ops/example-app", "x", { execFileImpl: impl }), (error) => {
    assert.ok(!error.message.includes("something-sensitive"));
    return true;
  });
  const { impl: missingField } = fakeAws(TARGET.awsAccount, async () => ({
    stdout: JSON.stringify({ other: "v" }),
  }));
  await assert.rejects(
    resolveSecretField("ops/example-app", "grafanaWebhookSecret", { execFileImpl: missingField }),
    /missing field/,
  );
});

// --- Normalization stability --------------------------------------------------

test("normalization is stable across ordering and timestamp noise", () => {
  const a = rawRule("dfrmh7bc4yqrkf", "ALB 5xx > 10 in 5m");
  const b = rawRule("dfrmh7bc4yqrkf", "ALB 5xx > 10 in 5m");
  assert.equal(queryChecksum(a), queryChecksum(b));
  const reordered = { for: a.for, data: a.data, condition: a.condition, title: a.title };
  const straight = { title: a.title, condition: a.condition, data: a.data, for: a.for };
  assert.equal(canonicalize(reordered), canonicalize(straight));
  const n = normalizeRule(a);
  assert.equal("updated" in n, false);
  assert.equal("version" in n, false);
  assert.equal("provenance" in n, false);
  assert.equal(n.title, a.title);
});

// --- Exactly five known UIDs ---------------------------------------------------

test("accepts exactly the five known UIDs", () => {
  assert.doesNotThrow(() => verifyUidAllowlist(KNOWN_UIDS));
});

test("rejects an unknown, extra, or missing UID", () => {
  assert.throws(() => verifyUidAllowlist([...KNOWN_UIDS, "zzzunknown"]), /Unknown rule UID/);
  assert.throws(() => verifyUidAllowlist(KNOWN_UIDS.slice(1)), /missing/);
});

// --- Drift is a hard failure ---------------------------------------------------

test("title drift and unexpected rules are detected", () => {
  const tampered = KNOWN_RULES.map((r) => ({ uid: r.uid, title: r.uid === LOG_RULE_UID ? "CHANGED" : r.title }));
  assert.ok(detectDrift(tampered).some((m) => m.includes(LOG_RULE_UID)));
  const extra = [...KNOWN_RULES.map((r) => ({ uid: r.uid, title: r.title })), { uid: "extra999", title: "x" }];
  assert.ok(detectDrift(extra).some((m) => m.includes("extra999")));
});

test("apply hard-rejects a live query mismatch rather than recreating", async () => {
  const state = newState();
  const repoRoot = fixtureRepo(state.rules);
  const client = realClient(state);
  const receiptPath = tmpReceiptPath();
  await runExport({ client, receiptPath, repoRoot, now: () => "2026-07-14T00:00:00Z" });
  state.rules.find((r) => r.uid === "dfrmh7bc4yqrkf").data = [{ refId: "A", model: { expr: "TAMPERED" } }];
  await assert.rejects(
    runApply({ client, receiptPath, repoRoot }),
    /drifted/,
  );
  const puts = state.requests.filter((r) => r.method === "PUT" && r.path.includes("dfrmh7bc4yqrkf"));
  assert.equal(puts.length, 0);
});

test("export refuses when live rules drift from the checked-in definitions", async () => {
  const state = newState();
  const repoRoot = fixtureRepo(); // checked-in overlay from pristine fixtures
  state.rules.find((r) => r.uid === LOG_RULE_UID).data = [{ refId: "A", model: { expr: "PRE-DRIFTED" } }];
  const client = realClient(state);
  await assert.rejects(
    runExport({ client, receiptPath: tmpReceiptPath(), repoRoot, now: () => "2026-07-14T00:00:00Z" }),
    /drifted from the checked-in definition/,
  );
});

test("apply refuses when live matches the receipt but drifted from the checked-in definitions", async () => {
  // Drift happened BEFORE the export: the receipt agrees with live, so only
  // the checked-in gate can catch it.
  const pristine = liveRulesFixture();
  const repoRoot = fixtureRepo(pristine);
  const drifted = liveRulesFixture();
  drifted.find((r) => r.uid === "cfrmh7f2sbe2od").data = [{ refId: "A", model: { expr: "PRE-DRIFTED" } }];
  const state = newState(drifted);
  const client = realClient(state);
  // Craft a receipt that matches the drifted live state (as a same-session
  // export of the drifted workspace would).
  const receiptPath = tmpReceiptPath();
  const checksums = Object.fromEntries(drifted.map((r) => [r.uid, queryChecksum(r)]));
  fs.writeFileSync(
    receiptPath,
    JSON.stringify({
      schemaVersion: 1,
      kind: "grafana-alerting-rollback-receipt",
      target: { ...TARGET },
      before: { rules: {}, contactPoints: [], notificationPolicy: {} },
      checksums: { rules: checksums, notificationPolicy: "x" },
    }),
    { mode: 0o600 },
  );
  await assert.rejects(
    runApply({ client, receiptPath, repoRoot }),
    /drifted from the checked-in definition.*cfrmh7f2sbe2od/,
  );
  assert.equal(state.requests.filter((r) => r.method !== "GET").length, 0);
});

// --- Only the log rule may carry log annotations -------------------------------

test("only bfrmh7e7x2k8wd may contain log annotations", () => {
  const good = KNOWN_RULES.map((r) => ({
    uid: r.uid,
    annotations: r.uid === LOG_RULE_UID
      ? {
          runbook_url: "x",
          proliferate_log_group: "/ecs/proliferate-prod",
          proliferate_log_filter_pattern: "CRITICAL_FAILURE",
          proliferate_log_region: "us-east-1",
        }
      : { runbook_url: "x" },
  }));
  assert.doesNotThrow(() => assertLogAnnotationsOnlyOnLogRule(good));
  const bad = JSON.parse(JSON.stringify(good));
  bad[0].annotations.proliferate_log_group = "/ecs/proliferate-prod";
  assert.throws(() => assertLogAnnotationsOnlyOnLogRule(bad), /must not carry log-lookup/);
  const missing = KNOWN_RULES.map((r) => ({ uid: r.uid, annotations: { runbook_url: "x" } }));
  assert.throws(() => assertLogAnnotationsOnlyOnLogRule(missing), /missing log annotations/);
});

// --- Redaction coverage ---------------------------------------------------------

test("redaction covers urls, bearer values, and long tokens", () => {
  const raw = "POST https://ops.example.invalid/v1/ingest/grafana Authorization: Bearer glsa_abcdefghijklmnopqrstuvwxyz123";
  const red = redact(raw);
  assert.ok(!red.includes("ops.example.invalid"));
  assert.ok(!red.includes("glsa_abcdefghijklmnopqrstuvwxyz123"));
  assert.ok(red.includes("<redacted-url>"));
});

// --- Target verification --------------------------------------------------------

test("wrong account, region, or workspace is rejected", () => {
  const good = { ...TARGET };
  assert.throws(() => verifyTarget({ ...good, awsAccount: "000000000000" }), /awsAccount/);
  assert.throws(() => verifyTarget({ ...good, awsRegion: "eu-west-1" }), /awsRegion/);
  assert.throws(() => verifyTarget({ ...good, grafanaWorkspaceId: "g-wrong" }), /grafanaWorkspaceId/);
});

// --- apply cannot mutate the notification policy --------------------------------

test("apply leaves the notification policy and Alertmanager config untouched", async () => {
  const state = newState();
  const repoRoot = fixtureRepo(state.rules);
  const client = realClient(state);
  const receiptPath = tmpReceiptPath();
  await runExport({ client, receiptPath, repoRoot, now: () => "2026-07-14T00:00:00Z" });
  const policyBefore = JSON.stringify(state.notificationPolicy);
  const result = await runApply({ client, receiptPath, repoRoot });
  assert.equal(result.policyUnchanged, true);
  assert.equal(JSON.stringify(state.notificationPolicy), policyBefore);
  // No request ever targeted the policies route with a write.
  assert.ok(!state.requests.some((r) => r.method !== "GET" && r.path.endsWith("/policies")));
  // Contact points and the Alertmanager config are never written by apply.
  assert.equal(state.requests.filter((r) => r.method !== "GET" && r.path.includes("contact-points")).length, 0);
  assert.equal(state.requests.filter((r) => r.method !== "GET" && r.path === ALERTMANAGER_CONFIG).length, 0);
  // The receipt captured the full before-config for rollback context.
  const receipt = JSON.parse(fs.readFileSync(receiptPath, "utf8"));
  assert.ok(receipt.before.alertmanagerConfig);
  for (const uid of KNOWN_UIDS) {
    assert.equal(result.beforeChecksums[uid], result.afterChecksums[uid]);
  }
});

test("apply throws if the policy is mutated underneath it", async () => {
  const state = newState();
  const repoRoot = fixtureRepo(state.rules);
  const client = realClient(state);
  const receiptPath = tmpReceiptPath();
  await runExport({ client, receiptPath, repoRoot, now: () => "2026-07-14T00:00:00Z" });
  state.onWrite = (method, p) => {
    if (p.includes("/alert-rules/")) state.notificationPolicy.receiver = "tampered";
  };
  await assert.rejects(
    runApply({ client, receiptPath, repoRoot }),
    /Notification policy changed/,
  );
});

test("restore replays the before-export rules", async () => {
  const state = newState();
  const repoRoot = fixtureRepo(state.rules);
  const client = realClient(state);
  const receiptPath = tmpReceiptPath();
  await runExport({ client, receiptPath, repoRoot, now: () => "2026-07-14T00:00:00Z" });
  await runApply({ client, receiptPath, repoRoot });
  const { restored } = await runRestore({ client, receiptPath });
  assert.deepEqual(restored.sort(), [...KNOWN_UIDS].sort());
  const receiverNames = () => state.amConfig.alertmanager_config.receivers.map((r) => r.name);
  assert.deepEqual(receiverNames(), ["slack-eng-triage", "slack-ops-alerts"]);
});

// --- Receipt path safety ---------------------------------------------------------

test("receipt path refuses worktree and relative paths, accepts private absolute ones", () => {
  assert.throws(() => assertPrivateReceiptPath("relative/path.json"), /absolute/);
  assert.throws(() => assertPrivateReceiptPath(path.join(REPO_ROOT, "receipt.json")), /outside the Git worktree/);
  assert.doesNotThrow(() => assertPrivateReceiptPath(tmpReceiptPath()));
});

// --- Checked-in overlay: identity + checksum consistency --------------------------

test("checked-in overlay validates and every checksum reproduces from its checked-in model", () => {
  const overlay = JSON.parse(
    fs.readFileSync(path.join(REPO_ROOT, "server/infra/observability/grafana/production-alerts.json"), "utf8"),
  );
  assert.doesNotThrow(() => validateOverlayDocument(overlay));
  for (const rule of overlay.rules) {
    assert.ok(rule.queryModel && typeof rule.queryModel === "object", `${rule.uid} has a captured queryModel`);
    assert.equal(rule.queryModel.title, rule.title);
    assert.equal(rule.queryChecksum, sha256(canonicalize(rule.queryModel)), `${rule.uid} checksum reproduces`);
    // Safe content: no secret-shaped material in the stored model.
    const serialized = JSON.stringify(rule.queryModel).toLowerCase();
    for (const needle of ["glsa_", "authorization", "secret", "password", "cookie"]) {
      assert.ok(!serialized.includes(needle), `${rule.uid} model contains no "${needle}"`);
    }
  }
});

test("a tampered checked-in model fails validation", () => {
  const overlay = JSON.parse(
    fs.readFileSync(path.join(REPO_ROOT, "server/infra/observability/grafana/production-alerts.json"), "utf8"),
  );
  overlay.rules[0].queryModel.condition = "tampered";
  assert.throws(() => validateOverlayDocument(overlay), /queryChecksum does not match/);
});

test("runCheck passes offline and detects drift against a tampered snapshot", () => {
  assert.doesNotThrow(() => runCheck());
  const snapshot = { rules: KNOWN_RULES.map((r) => ({ uid: r.uid, title: r.uid === "dfrmh7bc4yqrkf" ? "WRONG" : r.title })) };
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "grafana-snap-"));
  const snapPath = path.join(dir, "snap.json");
  fs.writeFileSync(snapPath, JSON.stringify(snapshot));
  assert.throws(() => runCheck({ snapshotPath: snapPath }), /Drift detected/);
});

test("ALLOWED_ANNOTATION_KEYS includes only runbook_url plus the three log keys", () => {
  assert.deepEqual([...ALLOWED_ANNOTATION_KEYS].sort(), [
    "proliferate_log_filter_pattern",
    "proliferate_log_group",
    "proliferate_log_region",
    "runbook_url",
  ]);
});
