// Fixed-target Grafana client for operator writes and metadata inventory.
// TARGET alone derives the base URL; an injected fetch changes only transport,
// while request construction, authorization, parsing, and writes remain real.

import { execFile } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

import { runContextualAwsCommand } from "./grafana-credential-process.mjs";
import { readMetadataInventoryInternal } from "./grafana-metadata-inventory.mjs";

const execFileAsync = promisify(execFile);

// Fixed production target. Shared single source of truth for the E1 tooling.
export const TARGET = Object.freeze({
  awsAccount: "157466816238",
  awsRegion: "us-east-1",
  grafanaWorkspaceId: "g-e532d030d8",
  grafanaWorkspaceName: "proliferate-ops",
  grafanaVersion: "10.4",
});
const { grafanaVersion: expectedGrafanaVersion, ...inventoryTarget } = TARGET;
const INVENTORY_TARGET = Object.freeze({ ...inventoryTarget, expectedGrafanaVersion });

// Derived exclusively from TARGET. Not configurable.
export const WORKSPACE_BASE_URL = `https://${TARGET.grafanaWorkspaceId}.grafana-workspace.${TARGET.awsRegion}.amazonaws.com`;

export const ADMIN_TOKEN_PATH = path.join(os.homedir(), ".proliferate-local/ops/grafana-admin.token");
export const CONTACT_POINT_NAME = "issue-tracker-webhook";

const PROVISIONING = "/api/v1/provisioning";
export const ALERTMANAGER_CONFIG = "/api/alertmanager/grafana/config/api/v1/alerts";

function fixedWorkspaceUrl(apiPath) {
  if (typeof apiPath !== "string" || !apiPath.startsWith("/api/") || apiPath.startsWith("//")) {
    throw Object.assign(new Error("Invalid fixed Grafana API path"), { code: "GRAFANA_TARGET_MISMATCH" });
  }
  const absolute = `${WORKSPACE_BASE_URL}${apiPath}`;
  const url = new URL(absolute);
  if (url.origin !== WORKSPACE_BASE_URL || url.username || url.password || url.hash) {
    throw Object.assign(new Error("Invalid fixed Grafana API origin"), { code: "GRAFANA_TARGET_MISMATCH" });
  }
  return absolute;
}

// Deterministic route/receiver bytes: sorted keys, preserved array order.
// Kept local to avoid a cycle with grafana-alerting.mjs.
export function canonicalJson(value) {
  if (Array.isArray(value)) {
    return `[${value.map(canonicalJson).join(",")}]`;
  }
  if (value && typeof value === "object") {
    const keys = Object.keys(value).sort();
    return `{${keys.map((k) => `${JSON.stringify(k)}:${canonicalJson(value[k])}`).join(",")}}`;
  }
  return JSON.stringify(value === undefined ? null : value);
}

function othersByName(receivers) {
  return (receivers || [])
    .filter((r) => r.name !== CONTACT_POINT_NAME)
    .slice()
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

// Grafana regenerates a matcher-keyed route subtree as receivers change.
// Authored bytes stay equal; the generated subtree must have the exact delta.
const AUTOGEN_MATCHER = "__grafana_autogenerated__";
const RECEIVER_MATCHER = "__grafana_receiver__";

function isAutogenBranch(node) {
  return (node.object_matchers || []).some((m) => Array.isArray(m) && m[0] === AUTOGEN_MATCHER);
}

// Separate canonical authored bytes from generated children grouped by receiver.
export function partitionRoute(route) {
  if (!route) {
    return { authored: canonicalJson(null), autogenByName: new Map() };
  }
  const clone = JSON.parse(JSON.stringify(route));
  const autogenByName = new Map();
  for (const child of clone.routes || []) {
    if (!isAutogenBranch(child)) {
      continue;
    }
    for (const sub of child.routes || []) {
      const matcher = (sub.object_matchers || []).find((m) => Array.isArray(m) && m[0] === RECEIVER_MATCHER);
      const name = matcher ? matcher[2] : `<unnamed:${canonicalJson(sub)}>`;
      const list = autogenByName.get(name) || [];
      list.push({ bytes: canonicalJson(sub), receiver: sub.receiver, matcherOp: matcher ? matcher[1] : null });
      autogenByName.set(name, list);
    }
    child.routes = [];
  }
  return { authored: canonicalJson(clone), autogenByName };
}

// Require authored byte equality and exactly one generated tracker-child add/remove.
export function verifyRouteDelta(beforeRoute, afterRoute, expectation, phase) {
  const failures = [];
  const before = partitionRoute(beforeRoute);
  const after = partitionRoute(afterRoute);
  if (before.authored !== after.authored) {
    failures.push(`operator-authored route tree changed during ${phase}`);
  }
  const names = new Set([...before.autogenByName.keys(), ...after.autogenByName.keys()]);
  for (const name of names) {
    if (name === CONTACT_POINT_NAME) {
      continue; // handled by the exact-delta rules below
    }
    const beforeBytes = (before.autogenByName.get(name) || []).map((c) => c.bytes);
    const afterBytes = (after.autogenByName.get(name) || []).map((c) => c.bytes);
    if (canonicalJson(beforeBytes) !== canonicalJson(afterBytes)) {
      failures.push(`unexpected autogenerated route change during ${phase} (receiver ${name})`);
    }
  }
  const trackerBefore = before.autogenByName.get(CONTACT_POINT_NAME) || [];
  const trackerAfter = after.autogenByName.get(CONTACT_POINT_NAME) || [];
  const isCanonicalChild = (c) => c.receiver === CONTACT_POINT_NAME && c.matcherOp === "=";
  if (expectation === "create") {
    if (trackerBefore.length !== 0 || trackerAfter.length !== 1) {
      failures.push(
        `autogenerated delta is not exactly one new ${CONTACT_POINT_NAME} child during ${phase}`,
      );
    } else if (!isCanonicalChild(trackerAfter[0])) {
      failures.push(`new autogenerated child is not the canonical ${CONTACT_POINT_NAME} child`);
    }
  } else if (expectation === "remove") {
    // Strict mirror of the create side: exactly one canonical tracker child
    // must exist before removal and zero after. A missing, duplicate, or
    // non-canonical (wrong operator/target) pre-state is rejected rather than
    // treated as a verified removal.
    if (trackerBefore.length !== 1) {
      failures.push(
        `expected exactly one autogenerated ${CONTACT_POINT_NAME} child before ${phase}, found ${trackerBefore.length}`,
      );
    } else if (!isCanonicalChild(trackerBefore[0])) {
      failures.push(`pre-${phase} autogenerated child is not the canonical ${CONTACT_POINT_NAME} child`);
    }
    if (trackerAfter.length !== 0) {
      failures.push(`autogenerated ${CONTACT_POINT_NAME} child still present during ${phase}`);
    }
  } else if (canonicalJson(trackerBefore.map((c) => c.bytes)) !== canonicalJson(trackerAfter.map((c) => c.bytes))) {
    failures.push(`unexpected autogenerated ${CONTACT_POINT_NAME} change during ${phase}`);
  }
  return failures;
}

// Verify encrypted tracker storage, exact route delta, and untouched peers.
function verifyTrackerWrite(afterConfig, beforeReceivers, beforeRoute) {
  const failures = [];
  const am = afterConfig.alertmanager_config || {};
  const tracker = (am.receivers || []).find((r) => r.name === CONTACT_POINT_NAME);
  const cfg = tracker?.grafana_managed_receiver_configs?.[0];
  if (!cfg) {
    failures.push("tracker receiver missing after write");
  } else if (cfg.secureFields?.authorization_credentials !== true) {
    failures.push("credential not stored as an encrypted secure field");
  }
  failures.push(...verifyRouteDelta(beforeRoute, am.route ?? null, "create", "write"));
  if (canonicalJson(othersByName(am.receivers)) !== canonicalJson(othersByName(beforeReceivers))) {
    failures.push("non-tracker receivers changed during write");
  }
  return failures;
}

function responseMatchesWorkspace(response) {
  try {
    const received = new URL(response.url);
    return received.origin === WORKSPACE_BASE_URL && !received.username && !received.password;
  } catch {
    return false;
  }
}

// Reads the ephemeral operator Admin token minted immediately before E1 ops.
// The token is used only as a request header and is never logged or returned
// through any printing path.
export function adminTokenProvider({ tokenPath = ADMIN_TOKEN_PATH } = {}) {
  if (!fs.existsSync(tokenPath)) {
    throw new Error(`Admin token not found at its named 0600 path (${tokenPath})`);
  }
  const mode = fs.statSync(tokenPath).mode & 0o777;
  if (mode !== 0o600) {
    throw new Error("Admin token file must be mode 0600");
  }
  const token = fs.readFileSync(tokenPath, "utf8").trim();
  if (!token) {
    throw new Error("Admin token file is empty");
  }
  return token;
}

function hasAwsCredentialContext(signal, throwIfDeadlineExpired) {
  const contextual = signal !== undefined || throwIfDeadlineExpired !== undefined;
  if (contextual && (!signal || typeof throwIfDeadlineExpired !== "function")) {
    throw new Error("AWS credential context requires both signal and deadline guard");
  }
  return contextual;
}

// Hard identity gate before any secret resolution: the AWS caller must be in
// the fixed target account, or we refuse to read anything.
export async function assertOperatorAccount(
  execFileImpl = execFileAsync,
  { signal, throwIfDeadlineExpired } = {},
) {
  const contextual = hasAwsCredentialContext(signal, throwIfDeadlineExpired);
  let account;
  try {
    const args = ["sts", "get-caller-identity", "--output", "json"];
    const { stdout } = contextual
      ? await runContextualAwsCommand({ execFileImpl, args, signal, throwIfDeadlineExpired })
      : await execFileImpl("aws", args);
    account = JSON.parse(stdout).Account;
  } catch {
    throw new Error("Unable to determine the AWS caller identity; refusing to resolve secrets");
  }
  if (account !== TARGET.awsAccount) {
    throw new Error(`AWS caller account ${account} is not the fixed target account ${TARGET.awsAccount}`);
  }
}

// Resolves one field of a JSON secret from AWS Secrets Manager at execution
// time. The value is returned to the caller and never printed; stderr from a
// failed call is discarded so no secret material can leak through error text.
export async function resolveSecretField(
  secretId,
  field,
  { execFileImpl = execFileAsync, signal, throwIfDeadlineExpired } = {},
) {
  const contextual = hasAwsCredentialContext(signal, throwIfDeadlineExpired);
  await assertOperatorAccount(execFileImpl, { signal, throwIfDeadlineExpired });
  let stdout;
  try {
    const args = [
      "secretsmanager",
      "get-secret-value",
      "--secret-id",
      secretId,
      "--region",
      TARGET.awsRegion,
      "--query",
      "SecretString",
      "--output",
      "text",
    ];
    ({ stdout } = contextual
      ? await runContextualAwsCommand({ execFileImpl, args, signal, throwIfDeadlineExpired })
      : await execFileImpl("aws", args));
  } catch {
    throw new Error(`Failed to read secret ${secretId} from AWS Secrets Manager`);
  }
  let parsed;
  try {
    parsed = JSON.parse(stdout);
  } catch {
    throw new Error(`Secret ${secretId} is not a JSON object`);
  }
  const value = parsed[field];
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`Secret ${secretId} is missing field ${field}`);
  }
  return value;
}

// Canonical secret reference issue-tracker/app.grafanaWebhookSecret,
// resolved at execution time (contract requirement 8).
export async function resolveWebhookSecret({ execFileImpl } = {}) {
  return resolveSecretField("issue-tracker/app", "grafanaWebhookSecret", { execFileImpl });
}

// Dedicated Viewer token issue-tracker/sources.grafanaToken (read-only path).
export async function resolveViewerToken({ execFileImpl, signal, throwIfDeadlineExpired } = {}) {
  return resolveSecretField("issue-tracker/sources", "grafanaToken",
    { execFileImpl, signal, throwIfDeadlineExpired });
}

// Maps one ruler-API rule entry ({for, grafana_alert}) onto the provisioning
// rule shape, so query models normalize identically regardless of which read
// surface produced them.
export function ruleFromRulerEntry(entry) {
  const ga = entry.grafana_alert || {};
  return {
    uid: ga.uid,
    title: ga.title,
    condition: ga.condition ?? null,
    data: ga.data ?? null,
    noDataState: ga.no_data_state ?? null,
    execErrState: ga.exec_err_state ?? null,
    for: entry.for ?? null,
    ruleGroup: ga.rule_group ?? null,
    folderUID: ga.namespace_uid ?? null,
    isPaused: ga.is_paused ?? false,
    labels: entry.labels ?? {},
    annotations: entry.annotations ?? {},
  };
}

// A fetch-like function is the only transport seam. Legacy calls resolve a
// bearer per request; inventory keeps one snapshot only in its invocation.
export function createGrafanaClient({ fetchImpl = fetch, tokenProvider }) {
  if (typeof tokenProvider !== "function") {
    throw new Error("createGrafanaClient requires a tokenProvider function");
  }

  async function request(method, apiPath, body = undefined, extraHeaders = {}) {
    const url = fixedWorkspaceUrl(apiPath);
    const headers = {
      Authorization: `Bearer ${tokenProvider()}`,
      Accept: "application/json",
      ...extraHeaders,
    };
    const init = { method, headers, redirect: "manual" };
    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
      init.body = JSON.stringify(body);
    }
    const response = await fetchImpl(url, init);
    if (!response.ok) {
      // Redacted by construction: path + status only. No host, no auth, no body.
      throw new Error(`Grafana ${method} ${apiPath} failed with HTTP ${response.status}`);
    }
    if (response.status === 204) {
      return null;
    }
    const text = await response.text();
    return text ? JSON.parse(text) : null;
  }

  // Verification failures restore the full pre-mutation config. If that write
  // also fails, re-read once so the operator gets both the diagnosis and the
  // bounded, non-secret recovery state.
  async function restoreOrThrow(config, diagnosis, inspectRestore, restoredMessage) {
    try {
      await request("POST", ALERTMANAGER_CONFIG, config);
    } catch (restoreError) {
      let restoreState = "restore state unknown (re-read failed)";
      try {
        restoreState = await inspectRestore();
      } catch {
        // Keep the fail-closed unknown state.
      }
      throw new Error(
        `${diagnosis}; RESTORE ALSO FAILED (${restoreError.message}); ${restoreState}.`,
      );
    }
    throw new Error(`${diagnosis}; ${restoredMessage}`);
  }

  async function prepareAuthorizedGet({ signal, guard, staticPaths, credentialBytes }) {
    for (const apiPath of staticPaths) fixedWorkspaceUrl(apiPath);
    guard();
    let removeAbort = () => {};
    const aborted = new Promise((_, reject) => {
      const onAbort = () => reject(signal.reason || new Error("Inventory credential acquisition aborted"));
      signal.addEventListener("abort", onAbort, { once: true });
      removeAbort = () => signal.removeEventListener("abort", onAbort);
    });
    let provided;
    try {
      provided = tokenProvider({ signal, throwIfDeadlineExpired: guard });
      provided = await Promise.race([Promise.resolve(provided), aborted]);
      guard();
    } catch {
      throw new Error("Inventory credential is unavailable");
    } finally {
      removeAbort();
    }
    if (
      typeof provided !== "string" ||
      Buffer.byteLength(provided, "utf8") > credentialBytes ||
      !/^[A-Za-z0-9._~+/-]+={0,}$/.test(provided)
    ) {
      throw new Error("Inventory credential is unavailable");
    }
    return async (apiPath, requestSignal) => {
      const url = fixedWorkspaceUrl(apiPath);
      const response = await fetchImpl(url, {
        method: "GET",
        headers: { Authorization: `Bearer ${provided}`, Accept: "application/json" },
        redirect: "manual",
        signal: requestSignal,
      });
      return { response, targetMatches: responseMatchesWorkspace(response) };
    };
  }

  return {
    async readMetadataInventory() {
      return readMetadataInventoryInternal({ target: INVENTORY_TARGET, prepareAuthorizedGet });
    },
    // --- reads (GET only) ---
    async listAlertRules() {
      return request("GET", `${PROVISIONING}/alert-rules`);
    },
    // Read-only rule listing over the ruler API, the surface the dedicated
    // Viewer service account can read (P0 read proof). Mapped to the same
    // provisioning shape so normalization/checksums are surface-independent.
    async listAlertRulesViaRuler() {
      const namespaces = await request("GET", "/api/ruler/grafana/api/v1/rules");
      const rules = [];
      for (const groups of Object.values(namespaces || {})) {
        for (const group of groups || []) {
          for (const entry of group.rules || []) {
            rules.push(ruleFromRulerEntry(entry));
          }
        }
      }
      return rules;
    },
    async getAlertRule(uid) {
      return request("GET", `${PROVISIONING}/alert-rules/${encodeURIComponent(uid)}`);
    },
    async getContactPoints() {
      return request("GET", `${PROVISIONING}/contact-points`);
    },
    async getNotificationPolicy() {
      return request("GET", `${PROVISIONING}/policies`);
    },

    // --- writes (apply/restore only; guarded by the caller) ---
    async upsertAlertRule(uid, rule) {
      return request("PUT", `${PROVISIONING}/alert-rules/${encodeURIComponent(uid)}`, rule, {
        "X-Disable-Provenance": "true",
      });
    },

    // AMG Grafana 10.4 cannot create webhook contact points through its
    // provisioning endpoint. The proven Alertmanager-config surface retains
    // encrypted credentials and permits the exact route-delta checks below.
    async getAlertmanagerConfig() {
      return request("GET", ALERTMANAGER_CONFIG);
    },
    async postAlertmanagerConfig(config) {
      return request("POST", ALERTMANAGER_CONFIG, config);
    },

    // Create-only read/modify/write for the one owned receiver. Read-back must
    // preserve other receivers and the authored route while adding exactly one
    // canonical autogenerated child; any mismatch restores the prior config.
    async upsertContactPoint(contactPoint) {
      if (contactPoint.name !== CONTACT_POINT_NAME) {
        throw new Error(`Refusing to write a contact point other than ${CONTACT_POINT_NAME}`);
      }
      const before = await request("GET", ALERTMANAGER_CONFIG);
      const beforeAm = before.alertmanager_config || {};
      const beforeReceivers = beforeAm.receivers || [];
      if (beforeReceivers.some((r) => r.name === CONTACT_POINT_NAME)) {
        throw new Error(
          `Refusing to overwrite a pre-existing ${CONTACT_POINT_NAME} receiver: ` +
            "remove it via restore first, then re-run apply.",
        );
      }
      const beforeRoute = beforeAm.route ?? null;
      const receiver = {
        name: CONTACT_POINT_NAME,
        grafana_managed_receiver_configs: [
          {
            name: CONTACT_POINT_NAME,
            type: contactPoint.type,
            disableResolveMessage: contactPoint.disableResolveMessage ?? false,
            settings: { ...(contactPoint.settings || {}) },
            secureSettings: { ...(contactPoint.secureSettings || {}) },
          },
        ],
      };
      const next = JSON.parse(JSON.stringify(before));
      next.alertmanager_config.receivers = [...beforeReceivers, receiver];
      await request("POST", ALERTMANAGER_CONFIG, next);

      const after = await request("GET", ALERTMANAGER_CONFIG);
      const failures = verifyTrackerWrite(after, beforeReceivers, beforeRoute);
      if (failures.length > 0) {
        const diagnosis = `Post-write verification failed (${failures.join("; ")})`;
        return restoreOrThrow(
          before,
          diagnosis,
          async () => {
            const current = await request("GET", ALERTMANAGER_CONFIG);
            const stillPresent = (current.alertmanager_config?.receivers || []).some(
              (r) => r.name === CONTACT_POINT_NAME,
            );
            return stillPresent
              ? "tracker receiver STILL PRESENT - manual restore required"
              : "tracker receiver absent - config appears restored";
          },
          "the pre-write Alertmanager config was restored.",
        );
      }
      return null;
    },

    // Restore removes only the owned receiver. It never replays redacted
    // receipt credentials, and verifies every unowned receiver and route.
    async restoreContactPoints(beforeContactPoints) {
      const hadTracker = (beforeContactPoints || []).some((cp) => cp.name === CONTACT_POINT_NAME);
      if (hadTracker) {
        throw new Error(
          `Refusing to restore a pre-existing ${CONTACT_POINT_NAME} contact point from a receipt: ` +
            "exported secure fields are redacted placeholders and would destroy the live credential. " +
            "Re-run `apply`, which re-resolves the real credential from its canonical secret reference.",
        );
      }
      const current = await request("GET", ALERTMANAGER_CONFIG);
      const am = current.alertmanager_config || {};
      const receivers = am.receivers || [];
      if (!receivers.some((r) => r.name === CONTACT_POINT_NAME)) {
        return null; // nothing to remove
      }
      const keep = receivers.filter((r) => r.name !== CONTACT_POINT_NAME);
      const beforeRoute = am.route ?? null;
      const next = JSON.parse(JSON.stringify(current));
      next.alertmanager_config.receivers = keep;
      await request("POST", ALERTMANAGER_CONFIG, next);

      const after = await request("GET", ALERTMANAGER_CONFIG);
      const afterAm = after.alertmanager_config || {};
      const failures = [];
      if ((afterAm.receivers || []).some((r) => r.name === CONTACT_POINT_NAME)) {
        failures.push("tracker receiver still present after removal");
      }
      failures.push(...verifyRouteDelta(beforeRoute, afterAm.route ?? null, "remove", "removal"));
      if (canonicalJson(othersByName(afterAm.receivers)) !== canonicalJson(othersByName(keep))) {
        failures.push("non-tracker receivers changed during removal");
      }
      if (failures.length > 0) {
        const diagnosis = `Removal verification failed (${failures.join("; ")})`;
        return restoreOrThrow(
          current,
          diagnosis,
          async () => {
            const live = await request("GET", ALERTMANAGER_CONFIG);
            return canonicalJson(live.alertmanager_config) === canonicalJson(current.alertmanager_config)
              ? "config matches the pre-removal state"
              : "config DIFFERS from the pre-removal state - manual restore required";
          },
          "the pre-removal Alertmanager config was restored.",
        );
      }
      return null;
    },
  };
}
