// Real Grafana HTTP client for the E1 operator script (grafana-alerting.mjs).
// Contract: specs/codebase/systems/engineering/issue-lifecycle/grafana-rules-delivery.md
//
// Network-layer target lock: the base URL is derived ONLY from the frozen
// TARGET constants below (workspace id + region), never from env or config, so
// no code path can aim at another workspace. Tests fake only the transport
// seam by injecting a fetch-like function; request construction, URL
// targeting, Authorization handling, response parsing, and upsert/restore wire
// semantics are all real reviewed code.

import { execFile } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

// Fixed production target. Shared single source of truth for the E1 tooling.
export const TARGET = Object.freeze({
  awsAccount: "157466816238",
  awsRegion: "us-east-1",
  grafanaWorkspaceId: "g-e532d030d8",
  grafanaWorkspaceName: "proliferate-ops",
  grafanaVersion: "10.4",
});

// Derived exclusively from TARGET. Not configurable.
export const WORKSPACE_BASE_URL = `https://${TARGET.grafanaWorkspaceId}.grafana-workspace.${TARGET.awsRegion}.amazonaws.com`;

export const ADMIN_TOKEN_PATH = path.join(os.homedir(), ".proliferate-local/ops/grafana-admin.token");
export const CONTACT_POINT_NAME = "issue-tracker-webhook";

const PROVISIONING = "/api/v1/provisioning";
export const ALERTMANAGER_CONFIG = "/api/alertmanager/grafana/config/api/v1/alerts";

// Deterministic serialization used for the route/receiver byte-equality
// guards (sorted keys, array order preserved). Local copy to keep the import
// graph acyclic with grafana-alerting.mjs.
export function canonicalJson(value) {
  if (Array.isArray(value)) {
    return `[${value.map(canonicalJson).join(",")}]`;
  }
  if (value && typeof value === "object") {
    const keys = Object.keys(value).sort();
    return `{${keys.map((k) => `${JSON.stringify(k)}:${canonicalJson(value[k])}`).join(",")}}`;
  }
  return JSON.stringify(value === undefined ? null : value);
}

function othersByName(receivers) {
  return (receivers || [])
    .filter((r) => r.name !== CONTACT_POINT_NAME)
    .slice()
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

// Grafana maintains an autogenerated routing subtree: a route child matching
// __grafana_autogenerated__=true whose children (one per receiver, keyed by a
// __grafana_receiver__ matcher) Grafana REGENERATES whenever a receiver is
// created or removed. Byte-equality therefore applies to the operator-authored
// tree only; the autogen subtree must change by EXACTLY the expected delta.
const AUTOGEN_MATCHER = "__grafana_autogenerated__";
const RECEIVER_MATCHER = "__grafana_receiver__";

function isAutogenBranch(node) {
  return (node.object_matchers || []).some((m) => Array.isArray(m) && m[0] === AUTOGEN_MATCHER);
}

// Split a route tree into the operator-authored part (canonical bytes, with
// autogen children emptied in place) and the autogen children grouped by the
// receiver name their matcher points at.
export function partitionRoute(route) {
  if (!route) {
    return { authored: canonicalJson(null), autogenByName: new Map() };
  }
  const clone = JSON.parse(JSON.stringify(route));
  const autogenByName = new Map();
  for (const child of clone.routes || []) {
    if (!isAutogenBranch(child)) {
      continue;
    }
    for (const sub of child.routes || []) {
      const matcher = (sub.object_matchers || []).find((m) => Array.isArray(m) && m[0] === RECEIVER_MATCHER);
      const name = matcher ? matcher[2] : `<unnamed:${canonicalJson(sub)}>`;
      const list = autogenByName.get(name) || [];
      list.push({ bytes: canonicalJson(sub), receiver: sub.receiver, matcherOp: matcher ? matcher[1] : null });
      autogenByName.set(name, list);
    }
    child.routes = [];
  }
  return { authored: canonicalJson(clone), autogenByName };
}

// Strict route-delta verification (coordinator ruling 2026-07-15):
// - operator-authored tree byte-identical;
// - autogen delta EXACTLY the expected change for issue-tracker-webhook
//   ("create": precisely one new child for our receiver; "remove": precisely
//   that child's removal); any other autogen delta is a failure.
export function verifyRouteDelta(beforeRoute, afterRoute, expectation, phase) {
  const failures = [];
  const before = partitionRoute(beforeRoute);
  const after = partitionRoute(afterRoute);
  if (before.authored !== after.authored) {
    failures.push(`operator-authored route tree changed during ${phase}`);
  }
  const names = new Set([...before.autogenByName.keys(), ...after.autogenByName.keys()]);
  for (const name of names) {
    if (name === CONTACT_POINT_NAME) {
      continue; // handled by the exact-delta rules below
    }
    const beforeBytes = (before.autogenByName.get(name) || []).map((c) => c.bytes);
    const afterBytes = (after.autogenByName.get(name) || []).map((c) => c.bytes);
    if (canonicalJson(beforeBytes) !== canonicalJson(afterBytes)) {
      failures.push(`unexpected autogenerated route change during ${phase} (receiver ${name})`);
    }
  }
  const trackerBefore = before.autogenByName.get(CONTACT_POINT_NAME) || [];
  const trackerAfter = after.autogenByName.get(CONTACT_POINT_NAME) || [];
  const isCanonicalChild = (c) => c.receiver === CONTACT_POINT_NAME && c.matcherOp === "=";
  if (expectation === "create") {
    if (trackerBefore.length !== 0 || trackerAfter.length !== 1) {
      failures.push(
        `autogenerated delta is not exactly one new ${CONTACT_POINT_NAME} child during ${phase}`,
      );
    } else if (!isCanonicalChild(trackerAfter[0])) {
      failures.push(`new autogenerated child is not the canonical ${CONTACT_POINT_NAME} child`);
    }
  } else if (expectation === "remove") {
    // Strict mirror of the create side: exactly one canonical tracker child
    // must exist before removal and zero after. A missing, duplicate, or
    // non-canonical (wrong operator/target) pre-state is rejected rather than
    // treated as a verified removal.
    if (trackerBefore.length !== 1) {
      failures.push(
        `expected exactly one autogenerated ${CONTACT_POINT_NAME} child before ${phase}, found ${trackerBefore.length}`,
      );
    } else if (!isCanonicalChild(trackerBefore[0])) {
      failures.push(`pre-${phase} autogenerated child is not the canonical ${CONTACT_POINT_NAME} child`);
    }
    if (trackerAfter.length !== 0) {
      failures.push(`autogenerated ${CONTACT_POINT_NAME} child still present during ${phase}`);
    }
  } else if (canonicalJson(trackerBefore.map((c) => c.bytes)) !== canonicalJson(trackerAfter.map((c) => c.bytes))) {
    failures.push(`unexpected autogenerated ${CONTACT_POINT_NAME} change during ${phase}`);
  }
  return failures;
}

// Post-write verification for the tracker receiver add: present with an
// encrypted credential, authored route byte-identical + exact autogen delta,
// other receivers untouched.
function verifyTrackerWrite(afterConfig, beforeReceivers, beforeRoute) {
  const failures = [];
  const am = afterConfig.alertmanager_config || {};
  const tracker = (am.receivers || []).find((r) => r.name === CONTACT_POINT_NAME);
  const cfg = tracker?.grafana_managed_receiver_configs?.[0];
  if (!cfg) {
    failures.push("tracker receiver missing after write");
  } else if (cfg.secureFields?.authorization_credentials !== true) {
    failures.push("credential not stored as an encrypted secure field");
  }
  failures.push(...verifyRouteDelta(beforeRoute, am.route ?? null, "create", "write"));
  if (canonicalJson(othersByName(am.receivers)) !== canonicalJson(othersByName(beforeReceivers))) {
    failures.push("non-tracker receivers changed during write");
  }
  return failures;
}

// Reads the ephemeral operator Admin token minted immediately before E1 ops.
// The token is used only as a request header and is never logged or returned
// through any printing path.
export function adminTokenProvider({ tokenPath = ADMIN_TOKEN_PATH } = {}) {
  if (!fs.existsSync(tokenPath)) {
    throw new Error(`Admin token not found at its named 0600 path (${tokenPath})`);
  }
  const mode = fs.statSync(tokenPath).mode & 0o777;
  if (mode !== 0o600) {
    throw new Error("Admin token file must be mode 0600");
  }
  const token = fs.readFileSync(tokenPath, "utf8").trim();
  if (!token) {
    throw new Error("Admin token file is empty");
  }
  return token;
}

// Hard identity gate before any secret resolution: the AWS caller must be in
// the fixed target account, or we refuse to read anything.
export async function assertOperatorAccount(execFileImpl = execFileAsync) {
  let account;
  try {
    const { stdout } = await execFileImpl("aws", ["sts", "get-caller-identity", "--output", "json"]);
    account = JSON.parse(stdout).Account;
  } catch {
    throw new Error("Unable to determine the AWS caller identity; refusing to resolve secrets");
  }
  if (account !== TARGET.awsAccount) {
    throw new Error(`AWS caller account ${account} is not the fixed target account ${TARGET.awsAccount}`);
  }
}

// Resolves one field of a JSON secret from AWS Secrets Manager at execution
// time. The value is returned to the caller and never printed; stderr from a
// failed call is discarded so no secret material can leak through error text.
export async function resolveSecretField(secretId, field, { execFileImpl = execFileAsync } = {}) {
  await assertOperatorAccount(execFileImpl);
  let stdout;
  try {
    ({ stdout } = await execFileImpl("aws", [
      "secretsmanager",
      "get-secret-value",
      "--secret-id",
      secretId,
      "--region",
      TARGET.awsRegion,
      "--query",
      "SecretString",
      "--output",
      "text",
    ]));
  } catch {
    throw new Error(`Failed to read secret ${secretId} from AWS Secrets Manager`);
  }
  let parsed;
  try {
    parsed = JSON.parse(stdout);
  } catch {
    throw new Error(`Secret ${secretId} is not a JSON object`);
  }
  const value = parsed[field];
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`Secret ${secretId} is missing field ${field}`);
  }
  return value;
}

// Canonical secret reference issue-tracker/app.grafanaWebhookSecret,
// resolved at execution time (contract requirement 8).
export async function resolveWebhookSecret({ execFileImpl } = {}) {
  return resolveSecretField("issue-tracker/app", "grafanaWebhookSecret", { execFileImpl });
}

// Dedicated Viewer token issue-tracker/sources.grafanaToken (read-only path).
export async function resolveViewerToken({ execFileImpl } = {}) {
  return resolveSecretField("issue-tracker/sources", "grafanaToken", { execFileImpl });
}

// Maps one ruler-API rule entry ({for, grafana_alert}) onto the provisioning
// rule shape, so query models normalize identically regardless of which read
// surface produced them.
export function ruleFromRulerEntry(entry) {
  const ga = entry.grafana_alert || {};
  return {
    uid: ga.uid,
    title: ga.title,
    condition: ga.condition ?? null,
    data: ga.data ?? null,
    noDataState: ga.no_data_state ?? null,
    execErrState: ga.exec_err_state ?? null,
    for: entry.for ?? null,
    ruleGroup: ga.rule_group ?? null,
    folderUID: ga.namespace_uid ?? null,
    isPaused: ga.is_paused ?? false,
    labels: entry.labels ?? {},
    annotations: entry.annotations ?? {},
  };
}

// A fetch-like function is the only injectable seam. `tokenProvider` returns
// the bearer token at request time so the token never lives on the client.
export function createGrafanaClient({ fetchImpl = fetch, tokenProvider }) {
  if (typeof tokenProvider !== "function") {
    throw new Error("createGrafanaClient requires a tokenProvider function");
  }

  async function request(method, apiPath, body = undefined, extraHeaders = {}) {
    const headers = {
      Authorization: `Bearer ${tokenProvider()}`,
      Accept: "application/json",
      ...extraHeaders,
    };
    const init = { method, headers };
    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
      init.body = JSON.stringify(body);
    }
    const response = await fetchImpl(`${WORKSPACE_BASE_URL}${apiPath}`, init);
    if (!response.ok) {
      // Redacted by construction: path + status only. No host, no auth, no body.
      throw new Error(`Grafana ${method} ${apiPath} failed with HTTP ${response.status}`);
    }
    if (response.status === 204) {
      return null;
    }
    const text = await response.text();
    return text ? JSON.parse(text) : null;
  }

  return {
    // --- reads (GET only) ---
    async listAlertRules() {
      return request("GET", `${PROVISIONING}/alert-rules`);
    },
    // Read-only rule listing over the ruler API, the surface the dedicated
    // Viewer service account can read (P0 read proof). Mapped to the same
    // provisioning shape so normalization/checksums are surface-independent.
    async listAlertRulesViaRuler() {
      const namespaces = await request("GET", "/api/ruler/grafana/api/v1/rules");
      const rules = [];
      for (const groups of Object.values(namespaces || {})) {
        for (const group of groups || []) {
          for (const entry of group.rules || []) {
            rules.push(ruleFromRulerEntry(entry));
          }
        }
      }
      return rules;
    },
    async getAlertRule(uid) {
      return request("GET", `${PROVISIONING}/alert-rules/${encodeURIComponent(uid)}`);
    },
    async getContactPoints() {
      return request("GET", `${PROVISIONING}/contact-points`);
    },
    async getNotificationPolicy() {
      return request("GET", `${PROVISIONING}/policies`);
    },

    // --- writes (apply/restore only; guarded by the caller) ---
    async upsertAlertRule(uid, rule) {
      return request("PUT", `${PROVISIONING}/alert-rules/${encodeURIComponent(uid)}`, rule, {
        "X-Disable-Provenance": "true",
      });
    },

    // --- tracker contact point via the Alertmanager config API -------------
    //
    // Evidence-backed surface change (E1 Phase 2 runs + coordinator probe,
    // 2026-07-14/15): AMG Grafana 10.4's provisioning API cannot create ANY
    // webhook contact point — POST /api/v1/provisioning/contact-points returns
    // HTTP 500 {"message":"no secrets configured for type 'webhook'"} even
    // with zero credential fields in the body (a type-registry defect in this
    // version, not a body-shape problem). The Alertmanager config API is
    // proven working on this workspace: POST of the full config with an
    // appended webhook receiver (settings + secureSettings) returned 202,
    // read-back showed secureFields.authorization_credentials=true
    // (server-side encrypted), and the route tree was byte-identical across
    // the add/remove cycle.
    async getAlertmanagerConfig() {
      return request("GET", ALERTMANAGER_CONFIG);
    },
    async postAlertmanagerConfig(config) {
      return request("POST", ALERTMANAGER_CONFIG, config);
    },

    // Create ONLY the named tracker contact point via an Alertmanager-config
    // read-modify-write. Any other name is refused (contract requirement 6);
    // a pre-existing receiver of our name is refused (create-only semantics —
    // updating would require replaying a credential we must not hold in a
    // receipt). After the write, read back and verify: receiver present with
    // secureFields.authorization_credentials=true, the operator-authored route
    // tree byte-identical to the pre-write GET with the autogen subtree delta
    // being exactly one new child for our receiver (see verifyRouteDelta), and
    // every other receiver untouched. Any verification failure triggers an
    // immediate restore (re-POST of the before-config) and a hard failure.
    async upsertContactPoint(contactPoint) {
      if (contactPoint.name !== CONTACT_POINT_NAME) {
        throw new Error(`Refusing to write a contact point other than ${CONTACT_POINT_NAME}`);
      }
      const before = await request("GET", ALERTMANAGER_CONFIG);
      const beforeAm = before.alertmanager_config || {};
      const beforeReceivers = beforeAm.receivers || [];
      if (beforeReceivers.some((r) => r.name === CONTACT_POINT_NAME)) {
        throw new Error(
          `Refusing to overwrite a pre-existing ${CONTACT_POINT_NAME} receiver: ` +
            "remove it via restore first, then re-run apply.",
        );
      }
      const beforeRoute = beforeAm.route ?? null;
      const receiver = {
        name: CONTACT_POINT_NAME,
        grafana_managed_receiver_configs: [
          {
            name: CONTACT_POINT_NAME,
            type: contactPoint.type,
            disableResolveMessage: contactPoint.disableResolveMessage ?? false,
            settings: { ...(contactPoint.settings || {}) },
            secureSettings: { ...(contactPoint.secureSettings || {}) },
          },
        ],
      };
      const next = JSON.parse(JSON.stringify(before));
      next.alertmanager_config.receivers = [...beforeReceivers, receiver];
      await request("POST", ALERTMANAGER_CONFIG, next);

      const after = await request("GET", ALERTMANAGER_CONFIG);
      const failures = verifyTrackerWrite(after, beforeReceivers, beforeRoute);
      if (failures.length > 0) {
        // Fail closed: put the pre-write config back, then report. A failed
        // restore must never swallow the verification diagnosis — attach both
        // errors and re-GET to report whether the restore actually landed.
        const diagnosis = `Post-write verification failed (${failures.join("; ")})`;
        try {
          await request("POST", ALERTMANAGER_CONFIG, before);
        } catch (restoreError) {
          let restoreState = "restore state unknown (re-read failed)";
          try {
            const current = await request("GET", ALERTMANAGER_CONFIG);
            const stillPresent = (current.alertmanager_config?.receivers || []).some(
              (r) => r.name === CONTACT_POINT_NAME,
            );
            restoreState = stillPresent
              ? "tracker receiver STILL PRESENT - manual restore required"
              : "tracker receiver absent - config appears restored";
          } catch {
            // keep "restore state unknown"
          }
          throw new Error(
            `${diagnosis}; RESTORE ALSO FAILED (${restoreError.message}); ${restoreState}.`,
          );
        }
        throw new Error(`${diagnosis}; the pre-write Alertmanager config was restored.`);
      }
      return null;
    },

    // Restore semantics are deliberately narrow: only the tracker receiver is
    // ever created by this tooling, so restore removes ONLY that receiver via
    // read-modify-write and verifies the route tree and every other receiver
    // are untouched. Slack receivers are never restored from a receipt:
    // exported configs carry secure fields only as secureFields/[REDACTED]
    // markers, so replaying any receipt receiver would destroy real
    // credentials. If the before-export HAD a tracker receiver, fail closed:
    // re-run `apply`, which re-resolves the real credential from the secret
    // store at execution time.
    async restoreContactPoints(beforeContactPoints) {
      const hadTracker = (beforeContactPoints || []).some((cp) => cp.name === CONTACT_POINT_NAME);
      if (hadTracker) {
        throw new Error(
          `Refusing to restore a pre-existing ${CONTACT_POINT_NAME} contact point from a receipt: ` +
            "exported secure fields are redacted placeholders and would destroy the live credential. " +
            "Re-run `apply`, which re-resolves the real credential from its canonical secret reference.",
        );
      }
      const current = await request("GET", ALERTMANAGER_CONFIG);
      const am = current.alertmanager_config || {};
      const receivers = am.receivers || [];
      if (!receivers.some((r) => r.name === CONTACT_POINT_NAME)) {
        return null; // nothing to remove
      }
      const keep = receivers.filter((r) => r.name !== CONTACT_POINT_NAME);
      const beforeRoute = am.route ?? null;
      const next = JSON.parse(JSON.stringify(current));
      next.alertmanager_config.receivers = keep;
      await request("POST", ALERTMANAGER_CONFIG, next);

      const after = await request("GET", ALERTMANAGER_CONFIG);
      const afterAm = after.alertmanager_config || {};
      const failures = [];
      if ((afterAm.receivers || []).some((r) => r.name === CONTACT_POINT_NAME)) {
        failures.push("tracker receiver still present after removal");
      }
      failures.push(...verifyRouteDelta(beforeRoute, afterAm.route ?? null, "remove", "removal"));
      if (canonicalJson(othersByName(afterAm.receivers)) !== canonicalJson(othersByName(keep))) {
        failures.push("non-tracker receivers changed during removal");
      }
      if (failures.length > 0) {
        // Fail closed exactly like the create path: put the pre-removal config
        // back rather than leaving detected damage live, and never let a
        // failed restore swallow the verification diagnosis.
        const diagnosis = `Removal verification failed (${failures.join("; ")})`;
        try {
          await request("POST", ALERTMANAGER_CONFIG, current);
        } catch (restoreError) {
          let restoreState = "restore state unknown (re-read failed)";
          try {
            const live = await request("GET", ALERTMANAGER_CONFIG);
            restoreState =
              canonicalJson(live.alertmanager_config) === canonicalJson(current.alertmanager_config)
                ? "config matches the pre-removal state"
                : "config DIFFERS from the pre-removal state - manual restore required";
          } catch {
            // keep "restore state unknown"
          }
          throw new Error(
            `${diagnosis}; RESTORE ALSO FAILED (${restoreError.message}); ${restoreState}.`,
          );
        }
        throw new Error(`${diagnosis}; the pre-removal Alertmanager config was restored.`);
      }
      return null;
    },
  };
}
