import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  ALLOWED_ANNOTATION_KEYS,
  CONTACT_POINT_NAME,
  KNOWN_RULES,
  KNOWN_UIDS,
  LOG_RULE_UID,
  REPO_ROOT,
  WEBHOOK_SECRET_REF,
  assertContactTemplateSafe,
  assertLogAnnotationsOnlyOnLogRule,
  assertPrivateReceiptPath,
  canonicalize,
  detectDrift,
  normalizeRule,
  queryChecksum,
  redact,
  runApply,
  runCheck,
  runExport,
  runRestore,
  sha256,
  validateOverlayDocument,
  verifyTarget,
  verifyUidAllowlist,
} from "./grafana-alerting.mjs";
import {
  ALERTMANAGER_CONFIG,
  TARGET,
  WORKSPACE_BASE_URL,
  assertOperatorAccount,
  canonicalJson,
  createGrafanaClient,
  resolveSecretField,
  ruleFromRulerEntry,
  verifyRouteDelta,
} from "./grafana-client.mjs";
import { extractQueryModel } from "./grafana-alerting.mjs";

// --- Fixtures: an in-memory Grafana behind a fake fetch (transport seam) -----

function rawRule(uid, title, extra = {}) {
  return {
    uid,
    title,
    condition: "C",
    data: [{ refId: "A", model: { expr: `metric{uid="${uid}"}` } }],
    noDataState: "NoData",
    execErrState: "Error",
    for: "5m",
    ruleGroup: "prod-alerts",
    folderUID: "prod-folder",
    isPaused: false,
    labels: {},
    annotations: {},
    // volatile noise:
    id: Math.floor(Math.random() * 1000),
    updated: new Date().toISOString(),
    version: Math.floor(Math.random() * 10),
    provenance: "api",
    ...extra,
  };
}

function liveRulesFixture() {
  return KNOWN_RULES.map((r) => rawRule(r.uid, r.title));
}

function newState(rules = liveRulesFixture()) {
  return {
    rules: rules.map((r) => JSON.parse(JSON.stringify(r))),
    contactPoints: [{ uid: "slack1", name: "slack-ops-alerts", type: "slack", settings: {} }],
    notificationPolicy: { receiver: "slack-ops-alerts", routes: [{ receiver: "slack-eng-triage" }] },
    amConfig: {
      template_files: {},
      alertmanager_config: {
        receivers: [
          {
            name: "slack-eng-triage",
            grafana_managed_receiver_configs: [
              { uid: "s1", name: "slack-eng-triage", type: "slack", settings: { recipient: "#eng" }, secureFields: { token: true, url: true } },
            ],
          },
          {
            name: "slack-ops-alerts",
            grafana_managed_receiver_configs: [
              { uid: "s2", name: "slack-ops-alerts", type: "slack", settings: { recipient: "#ops" }, secureFields: { token: true, url: true } },
            ],
          },
        ],
        route: {
          receiver: "slack-eng-triage",
          routes: [
            {
              object_matchers: [["__grafana_autogenerated__", "=", "true"]],
              receiver: "slack-eng-triage",
              routes: [
                { object_matchers: [["__grafana_receiver__", "=", "slack-eng-triage"]], receiver: "slack-eng-triage", group_by: ["grafana_folder", "alertname"] },
                { object_matchers: [["__grafana_receiver__", "=", "slack-ops-alerts"]], receiver: "slack-ops-alerts", group_by: ["grafana_folder", "alertname"] },
              ],
            },
            { receiver: "slack-ops-alerts", object_matchers: [["severity", "=", "critical"]] },
          ],
        },
      },
    },
    requests: [],
    onWrite: null,
    onAmPost: null,
    nextUid: 1,
  };
}

// Mimic the server's behavior on Alertmanager config POST: secureSettings
// values are encrypted away into secureFields markers, and Grafana REGENERATES
// the autogenerated routing subtree to hold exactly one child per receiver.
function encryptAmConfig(config) {
  const stored = JSON.parse(JSON.stringify(config));
  for (const receiver of stored.alertmanager_config.receivers || []) {
    for (const cfg of receiver.grafana_managed_receiver_configs || []) {
      if (cfg.secureSettings) {
        cfg.secureFields = { ...(cfg.secureFields || {}) };
        for (const key of Object.keys(cfg.secureSettings)) {
          cfg.secureFields[key] = true;
        }
        delete cfg.secureSettings;
      }
    }
  }
  const autogen = (stored.alertmanager_config.route?.routes || []).find((r) =>
    (r.object_matchers || []).some((m) => m[0] === "__grafana_autogenerated__"),
  );
  if (autogen) {
    autogen.routes = (stored.alertmanager_config.receivers || []).map((r) => ({
      object_matchers: [["__grafana_receiver__", "=", r.name]],
      receiver: r.name,
      group_by: ["grafana_folder", "alertname"],
    }));
  }
  return stored;
}

function jsonResponse(status, body) {
  return {
    ok: status >= 200 && status < 300,
    status,
    text: async () => (body === undefined ? "" : JSON.stringify(body)),
  };
}

const API = "/api/v1/provisioning";

// Fake fetch implementing the provisioning routes the client uses. Only the
// transport is faked; the client under test is the real one.
function fakeGrafanaFetch(state) {
  return async (url, init = {}) => {
    const method = init.method || "GET";
    const parsed = new URL(url);
    const p = parsed.pathname;
    state.requests.push({ method, url, path: p, headers: init.headers || {}, body: init.body });
    if (method !== "GET" && state.onWrite) state.onWrite(method, p);
    const body = init.body ? JSON.parse(init.body) : undefined;

    if (method === "GET" && p === `${API}/alert-rules`) return jsonResponse(200, state.rules);
    const ruleMatch = p.match(new RegExp(`^${API}/alert-rules/(.+)$`));
    if (ruleMatch) {
      const uid = decodeURIComponent(ruleMatch[1]);
      const idx = state.rules.findIndex((r) => r.uid === uid);
      if (method === "GET") return idx >= 0 ? jsonResponse(200, state.rules[idx]) : jsonResponse(404, {});
      if (method === "PUT") {
        if (idx < 0) return jsonResponse(404, {});
        state.rules[idx] = body;
        return jsonResponse(200, body);
      }
    }
    if (p === `${API}/contact-points`) {
      if (method === "GET") return jsonResponse(200, state.contactPoints);
      if (method === "POST") {
        const created = { ...body, uid: `cp${state.nextUid++}` };
        state.contactPoints.push(created);
        return jsonResponse(202, created);
      }
    }
    const cpMatch = p.match(new RegExp(`^${API}/contact-points/(.+)$`));
    if (cpMatch) {
      const uid = decodeURIComponent(cpMatch[1]);
      const idx = state.contactPoints.findIndex((cp) => cp.uid === uid);
      if (idx < 0) return jsonResponse(404, {});
      if (method === "PUT") {
        state.contactPoints[idx] = { ...body, uid };
        return jsonResponse(202, state.contactPoints[idx]);
      }
      if (method === "DELETE") {
        state.contactPoints.splice(idx, 1);
        return jsonResponse(202, {});
      }
    }
    if (method === "GET" && p === `${API}/policies`) return jsonResponse(200, state.notificationPolicy);
    if (p === ALERTMANAGER_CONFIG) {
      if (method === "GET") return jsonResponse(200, state.amConfig);
      if (method === "POST") {
        state.amConfig = encryptAmConfig(body);
        if (state.onAmPost) state.onAmPost(state);
        return jsonResponse(202, { message: "configuration created" });
      }
    }
    return jsonResponse(404, {});
  };
}

function realClient(state, token = "test-token-value") {
  return createGrafanaClient({ fetchImpl: fakeGrafanaFetch(state), tokenProvider: () => token });
}

function tmpReceiptPath() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "grafana-e1-"));
  return path.join(dir, "receipt.json");
}

// A throwaway repo root whose checked-in overlay matches `rules` (the live
// fixtures), so the live-vs-checked-in gate passes unless a test tampers.
function fixtureRepo(rules = liveRulesFixture()) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "grafana-repo-"));
  const dir = path.join(root, "server/infra/observability/grafana");
  fs.mkdirSync(dir, { recursive: true });
  const overlay = {
    target: { ...TARGET },
    component: "proliferate-server",
    rules: KNOWN_RULES.map((k) => {
      const live = rules.find((r) => r.uid === k.uid);
      const annotations = {
        runbook_url: "https://example.invalid/runbook#anchor",
        ...(k.uid === LOG_RULE_UID
          ? {
              proliferate_log_group: "/ecs/proliferate-prod",
              proliferate_log_filter_pattern: "CRITICAL_FAILURE",
              proliferate_log_region: "us-east-1",
            }
          : {}),
      };
      return {
        uid: k.uid,
        title: k.title,
        severity: k.severity,
        labels: { proliferate_rule_uid: k.uid, proliferate_component: "proliferate-server", severity: k.severity },
        annotations,
        queryModel: extractQueryModel(live),
        queryChecksum: queryChecksum(live),
      };
    }),
  };
  fs.writeFileSync(path.join(dir, "production-alerts.json"), JSON.stringify(overlay));
  fs.copyFileSync(
    path.join(REPO_ROOT, "server/infra/observability/grafana/issue-tracker-contact.json"),
    path.join(dir, "issue-tracker-contact.json"),
  );
  return root;
}

// --- Client transport: request construction + target lock -------------------

test("base URL derives only from the frozen TARGET constants", () => {
  assert.equal(
    WORKSPACE_BASE_URL,
    `https://${TARGET.grafanaWorkspaceId}.grafana-workspace.${TARGET.awsRegion}.amazonaws.com`,
  );
  assert.equal(WORKSPACE_BASE_URL, "https://g-e532d030d8.grafana-workspace.us-east-1.amazonaws.com");
});

test("listAlertRules issues a GET to the workspace provisioning path with a Bearer header", async () => {
  const state = newState();
  const client = realClient(state, "sekrit-token");
  const rules = await client.listAlertRules();
  assert.equal(rules.length, 6);
  const req = state.requests[0];
  assert.equal(req.method, "GET");
  assert.equal(req.url, `${WORKSPACE_BASE_URL}${API}/alert-rules`);
  assert.equal(req.headers.Authorization, "Bearer sekrit-token");
});

test("upsertAlertRule PUTs JSON to the rule path with X-Disable-Provenance", async () => {
  const state = newState();
  const client = realClient(state);
  const next = { ...state.rules[0], labels: { severity: "critical" } };
  await client.upsertAlertRule(next.uid, next);
  const req = state.requests.at(-1);
  assert.equal(req.method, "PUT");
  assert.equal(req.path, `${API}/alert-rules/${next.uid}`);
  assert.equal(req.headers["X-Disable-Provenance"], "true");
  assert.equal(req.headers["Content-Type"], "application/json");
  assert.deepEqual(JSON.parse(req.body).labels, { severity: "critical" });
});

function trackerContactFixture(credential = "resolved-credential-under-test") {
  return {
    name: CONTACT_POINT_NAME,
    type: "webhook",
    disableResolveMessage: false,
    settings: { url: "https://issues.proliferate.com/v1/ingest/grafana", httpMethod: "POST", maxAlerts: 0, authorization_scheme: "Bearer" },
    secureSettings: { authorization_credentials: credential },
  };
}

test("upsertContactPoint appends the tracker receiver via the Alertmanager config API and pins the wire shape", async () => {
  // Wire-shape pin (coordinator's live probe): full-config POST to the
  // Alertmanager config API; the appended receiver carries non-secret fields
  // in settings and the credential in secureSettings (encrypted server-side).
  const state = newState();
  const client = realClient(state);
  await client.upsertContactPoint(trackerContactFixture());
  const post = state.requests.find((r) => r.method === "POST" && r.path === ALERTMANAGER_CONFIG);
  assert.ok(post, "one Alertmanager config POST issued");
  const body = JSON.parse(post.body);
  const receivers = body.alertmanager_config.receivers;
  assert.deepEqual(receivers.map((r) => r.name), ["slack-eng-triage", "slack-ops-alerts", CONTACT_POINT_NAME]);
  const cfg = receivers.at(-1).grafana_managed_receiver_configs[0];
  assert.equal(cfg.type, "webhook");
  assert.equal(cfg.disableResolveMessage, false);
  assert.equal(cfg.settings.authorization_scheme, "Bearer");
  assert.equal(cfg.settings.maxAlerts, 0);
  assert.equal("authorization_credentials" in cfg.settings, false, "credential not in settings");
  assert.equal(cfg.secureSettings.authorization_credentials, "resolved-credential-under-test");
  // Slack receivers in the POSTed config are byte-identical to the GET.
  assert.equal(canonicalJson(receivers.slice(0, 2)), canonicalJson(newState().amConfig.alertmanager_config.receivers));
  // Route untouched in the POSTed body.
  assert.equal(canonicalJson(body.alertmanager_config.route), canonicalJson(newState().amConfig.alertmanager_config.route));
  // Read-back state: credential stored only as an encrypted marker.
  const stored = state.amConfig.alertmanager_config.receivers.at(-1).grafana_managed_receiver_configs[0];
  assert.equal(stored.secureFields.authorization_credentials, true);
  assert.equal("secureSettings" in stored, false);
});

test("upsertContactPoint refuses other names and refuses a pre-existing tracker receiver", async () => {
  const state = newState();
  const client = realClient(state);
  await assert.rejects(client.upsertContactPoint({ name: "slack-ops-alerts", type: "slack" }), /Refusing/);
  await client.upsertContactPoint(trackerContactFixture());
  await assert.rejects(client.upsertContactPoint(trackerContactFixture()), /pre-existing issue-tracker-webhook receiver/);
});

test("a write that tampers with the route hard-fails and restores the pre-write config", async () => {
  const state = newState();
  const client = realClient(state);
  const originalRoute = canonicalJson(state.amConfig.alertmanager_config.route);
  let tampered = false;
  state.onAmPost = (s) => {
    if (!tampered) {
      tampered = true; // only the first (write) POST tampers; the restore POST must not.
      s.amConfig.alertmanager_config.route = { receiver: CONTACT_POINT_NAME };
    }
  };
  await assert.rejects(client.upsertContactPoint(trackerContactFixture("sekrit-credential")), (error) => {
    assert.match(error.message, /route tree changed during write/);
    assert.ok(!error.message.includes("sekrit-credential"), "no credential in error");
    return true;
  });
  // The client re-POSTed the before-config: route + receivers back to original.
  assert.equal(canonicalJson(state.amConfig.alertmanager_config.route), originalRoute);
  assert.deepEqual(
    state.amConfig.alertmanager_config.receivers.map((r) => r.name),
    ["slack-eng-triage", "slack-ops-alerts"],
  );
  const amPosts = state.requests.filter((r) => r.method === "POST" && r.path === ALERTMANAGER_CONFIG);
  assert.equal(amPosts.length, 2, "write POST + restore POST");
});

test("the expected autogen regeneration (one new tracker child) passes verification", async () => {
  const state = newState();
  const client = realClient(state);
  // The regenerating fake adds exactly one autogen child for the new receiver;
  // the strict guard must accept this and only this.
  await client.upsertContactPoint(trackerContactFixture());
  const autogen = state.amConfig.alertmanager_config.route.routes.find((r) =>
    (r.object_matchers || []).some((m) => m[0] === "__grafana_autogenerated__"),
  );
  const names = autogen.routes.map((r) => r.receiver).sort();
  assert.deepEqual(names, ["issue-tracker-webhook", "slack-eng-triage", "slack-ops-alerts"]);
  // And the full cycle back: removal restores exactly the two originals.
  await client.restoreContactPoints([]);
  assert.deepEqual(autogen === undefined ? [] : state.amConfig.alertmanager_config.route.routes
    .find((r) => (r.object_matchers || []).some((m) => m[0] === "__grafana_autogenerated__"))
    .routes.map((r) => r.receiver).sort(), ["slack-eng-triage", "slack-ops-alerts"]);
});

test("an unexpected autogen child beyond the expected delta hard-fails and restores", async () => {
  const state = newState();
  const client = realClient(state);
  state.onAmPost = (s) => {
    const autogen = s.amConfig.alertmanager_config.route.routes.find((r) =>
      (r.object_matchers || []).some((m) => m[0] === "__grafana_autogenerated__"),
    );
    autogen.routes.push({
      object_matchers: [["__grafana_receiver__", "=", "rogue-receiver"]],
      receiver: "rogue-receiver",
    });
  };
  await assert.rejects(client.upsertContactPoint(trackerContactFixture()), (error) => {
    assert.match(error.message, /unexpected autogenerated route change during write \(receiver rogue-receiver\)/);
    return true;
  });
  // Auto-restore: back to the two slack receivers only.
  assert.deepEqual(
    state.amConfig.alertmanager_config.receivers.map((r) => r.name),
    ["slack-eng-triage", "slack-ops-alerts"],
  );
});

test("a mutation of an existing autogen child hard-fails as an unexpected delta", async () => {
  const state = newState();
  const client = realClient(state);
  state.onAmPost = (s) => {
    const autogen = s.amConfig.alertmanager_config.route.routes.find((r) =>
      (r.object_matchers || []).some((m) => m[0] === "__grafana_autogenerated__"),
    );
    const slackChild = autogen.routes.find((r) => r.receiver === "slack-ops-alerts");
    slackChild.group_by = ["tampered"];
  };
  await assert.rejects(
    client.upsertContactPoint(trackerContactFixture()),
    /unexpected autogenerated route change during write \(receiver slack-ops-alerts\)/,
  );
});

// --- Strict removal delta (verifyRouteDelta unit coverage) --------------------

function routeWithAutogenChildren(children) {
  return {
    receiver: "slack-eng-triage",
    routes: [
      { object_matchers: [["__grafana_autogenerated__", "=", "true"]], receiver: "slack-eng-triage", routes: children },
    ],
  };
}

function trackerChild(overrides = {}) {
  return {
    object_matchers: [["__grafana_receiver__", overrides.op || "=", overrides.target || CONTACT_POINT_NAME]],
    receiver: overrides.receiver || CONTACT_POINT_NAME,
    group_by: ["grafana_folder", "alertname"],
  };
}

test("removal delta requires exactly one canonical tracker child before and zero after", () => {
  const withChild = routeWithAutogenChildren([trackerChild()]);
  const without = routeWithAutogenChildren([]);
  // Happy path: one canonical child removed.
  assert.deepEqual(verifyRouteDelta(withChild, without, "remove", "removal"), []);
  // Missing pre-child: not a verified removal.
  assert.ok(
    verifyRouteDelta(without, without, "remove", "removal").some((f) => f.includes("expected exactly one")),
  );
  // Duplicate pre-children: rejected.
  assert.ok(
    verifyRouteDelta(routeWithAutogenChildren([trackerChild(), trackerChild()]), without, "remove", "removal")
      .some((f) => f.includes("expected exactly one")),
  );
  // Wrong-target child (matcher name ours, receiver someone else's): rejected.
  assert.ok(
    verifyRouteDelta(routeWithAutogenChildren([trackerChild({ receiver: "slack-ops-alerts" })]), without, "remove", "removal")
      .some((f) => f.includes("not the canonical")),
  );
  // Wrong-operator matcher: rejected.
  assert.ok(
    verifyRouteDelta(routeWithAutogenChildren([trackerChild({ op: "=~" })]), without, "remove", "removal")
      .some((f) => f.includes("not the canonical")),
  );
  // Child still present after: rejected.
  assert.ok(
    verifyRouteDelta(withChild, withChild, "remove", "removal").some((f) => f.includes("still present")),
  );
});

test("create delta requires the new child to be canonical", () => {
  const without = routeWithAutogenChildren([]);
  assert.deepEqual(verifyRouteDelta(without, routeWithAutogenChildren([trackerChild()]), "create", "write"), []);
  assert.ok(
    verifyRouteDelta(without, routeWithAutogenChildren([trackerChild({ op: "=~" })]), "create", "write")
      .some((f) => f.includes("not the canonical")),
  );
  assert.ok(
    verifyRouteDelta(without, routeWithAutogenChildren([trackerChild({ receiver: "rogue" })]), "create", "write")
      .some((f) => f.includes("not the canonical")),
  );
});

// --- Removal-path fail-closed restore (mirror of the create path) -------------

test("a removal that damages the authored route hard-fails and restores the pre-removal config", async () => {
  const state = newState();
  const client = realClient(state);
  await client.upsertContactPoint(trackerContactFixture());
  const preRemoval = canonicalJson(state.amConfig.alertmanager_config);
  let posts = 0;
  state.onAmPost = (s) => {
    posts += 1;
    if (posts === 1) {
      // Only the removal POST tampers; the restore POST must not.
      s.amConfig.alertmanager_config.route.receiver = "tampered-default";
    }
  };
  await assert.rejects(client.restoreContactPoints([]), (error) => {
    assert.match(error.message, /Removal verification failed/);
    assert.match(error.message, /operator-authored route tree changed during removal/);
    assert.match(error.message, /the pre-removal Alertmanager config was restored/);
    return true;
  });
  assert.equal(canonicalJson(state.amConfig.alertmanager_config), preRemoval);
  // Tracker receiver is back (pre-removal state had it).
  assert.ok(state.amConfig.alertmanager_config.receivers.some((r) => r.name === CONTACT_POINT_NAME));
});

test("a removal that damages a non-tracker receiver hard-fails and restores", async () => {
  const state = newState();
  const client = realClient(state);
  await client.upsertContactPoint(trackerContactFixture());
  const preRemoval = canonicalJson(state.amConfig.alertmanager_config);
  let posts = 0;
  state.onAmPost = (s) => {
    posts += 1;
    if (posts === 1) {
      s.amConfig.alertmanager_config.receivers = s.amConfig.alertmanager_config.receivers.filter(
        (r) => r.name !== "slack-ops-alerts",
      );
    }
  };
  await assert.rejects(client.restoreContactPoints([]), /non-tracker receivers changed during removal/);
  assert.equal(canonicalJson(state.amConfig.alertmanager_config), preRemoval);
});

test("a failed restore on the removal path reports both errors and the live restore state", async () => {
  const state = newState();
  const client = realClient(state);
  await client.upsertContactPoint(trackerContactFixture("sekrit-credential"));
  let amPosts = 0;
  const baseFetch = fakeGrafanaFetch(state);
  const failingRestoreFetch = async (url, init = {}) => {
    const method = init.method || "GET";
    const p = new URL(url).pathname;
    if (p === ALERTMANAGER_CONFIG && method === "POST") {
      amPosts += 1;
      if (amPosts === 1) {
        // The removal POST "succeeds" but the stored route is tampered.
        state.amConfig = encryptAmConfig(JSON.parse(init.body));
        state.amConfig.alertmanager_config.route.receiver = "tampered-default";
        return { ok: true, status: 202, text: async () => "{}" };
      }
      // The restore POST fails.
      return { ok: false, status: 500, text: async () => "" };
    }
    return baseFetch(url, init);
  };
  const failingClient = createGrafanaClient({ fetchImpl: failingRestoreFetch, tokenProvider: () => "t" });
  await assert.rejects(failingClient.restoreContactPoints([]), (error) => {
    assert.match(error.message, /Removal verification failed/);
    assert.match(error.message, /RESTORE ALSO FAILED/);
    assert.match(error.message, /HTTP 500/);
    assert.match(error.message, /DIFFERS from the pre-removal state - manual restore required/);
    assert.ok(!error.message.includes("sekrit-credential"), "no credential in error");
    return true;
  });
  assert.equal(amPosts, 2, "removal POST + attempted restore POST");
});

test("a failed restore after failed verification reports both errors and the live restore state", async () => {
  const state = newState();
  let amPosts = 0;
  const failingRestoreFetch = async (url, init = {}) => {
    const method = init.method || "GET";
    const p = new URL(url).pathname;
    if (p === ALERTMANAGER_CONFIG && method === "POST") {
      amPosts += 1;
      if (amPosts === 1) {
        // The write "succeeds" but the stored route is tampered.
        state.amConfig = encryptAmConfig(JSON.parse(init.body));
        state.amConfig.alertmanager_config.route = { receiver: CONTACT_POINT_NAME };
        return { ok: true, status: 202, text: async () => "{}" };
      }
      // The restore POST fails.
      return { ok: false, status: 500, text: async () => "" };
    }
    return fakeGrafanaFetch(state)(url, init);
  };
  const client = createGrafanaClient({ fetchImpl: failingRestoreFetch, tokenProvider: () => "t" });
  await assert.rejects(client.upsertContactPoint(trackerContactFixture("sekrit-credential")), (error) => {
    // Both diagnoses present: the verification failure AND the restore failure.
    assert.match(error.message, /Post-write verification failed/);
    assert.match(error.message, /route tree changed during write/);
    assert.match(error.message, /RESTORE ALSO FAILED/);
    assert.match(error.message, /HTTP 500/);
    // The re-GET reported the live state: tracker receiver still present.
    assert.match(error.message, /STILL PRESENT - manual restore required/);
    assert.ok(!error.message.includes("sekrit-credential"), "no credential in error");
    return true;
  });
  assert.equal(amPosts, 2, "write POST + attempted restore POST");
});

test("a write whose credential is not stored encrypted hard-fails and restores", async () => {
  const state = newState();
  const client = realClient(state);
  state.onAmPost = (s) => {
    const tracker = s.amConfig.alertmanager_config.receivers.find((r) => r.name === CONTACT_POINT_NAME);
    if (tracker) delete tracker.grafana_managed_receiver_configs[0].secureFields;
  };
  await assert.rejects(client.upsertContactPoint(trackerContactFixture()), /not stored as an encrypted secure field/);
  assert.deepEqual(
    state.amConfig.alertmanager_config.receivers.map((r) => r.name),
    ["slack-eng-triage", "slack-ops-alerts"],
  );
});

test("restoreContactPoints removes only the tracker receiver and leaves route + Slack untouched", async () => {
  const state = newState();
  const client = realClient(state);
  await client.upsertContactPoint(trackerContactFixture());
  const slackBefore = canonicalJson(newState().amConfig.alertmanager_config.receivers);
  // The full add/remove cycle must return the route to its pristine shape:
  // Grafana regenerates the autogen subtree, so after removal it again holds
  // exactly one child per remaining receiver.
  const pristineRoute = canonicalJson(encryptAmConfig(newState().amConfig).alertmanager_config.route);
  await client.restoreContactPoints([{ uid: "slack1", name: "slack-ops-alerts", type: "slack", settings: {} }]);
  assert.deepEqual(
    state.amConfig.alertmanager_config.receivers.map((r) => r.name),
    ["slack-eng-triage", "slack-ops-alerts"],
  );
  assert.equal(canonicalJson(state.amConfig.alertmanager_config.receivers), slackBefore);
  assert.equal(canonicalJson(state.amConfig.alertmanager_config.route), pristineRoute);
  // No DELETEs on the wire; removal is a config POST.
  assert.equal(state.requests.filter((r) => r.method === "DELETE").length, 0);
  // Idempotent when the receiver is already gone: no further write issued.
  const writesBefore = state.requests.filter((r) => r.method !== "GET").length;
  await client.restoreContactPoints([]);
  assert.equal(state.requests.filter((r) => r.method !== "GET").length, writesBefore);
});

test("restoreContactPoints refuses a pre-existing tracker point (redacted secure fields must never be replayed)", async () => {
  const state = newState();
  // The receipt's exported point carries the provider's redaction placeholder
  // where the real credential was; replaying it would destroy the credential.
  const before = [
    ...JSON.parse(JSON.stringify(state.contactPoints)),
    {
      uid: "cp9",
      name: CONTACT_POINT_NAME,
      type: "webhook",
      settings: { httpMethod: "POST", authorization_credentials: "[REDACTED]" },
    },
  ];
  state.contactPoints.push({ uid: "cp9", name: CONTACT_POINT_NAME, type: "webhook", settings: { httpMethod: "POST" } });
  const client = realClient(state);
  await assert.rejects(client.restoreContactPoints(before), /Refusing to restore a pre-existing/);
  await assert.rejects(client.restoreContactPoints(before), /Re-run `apply`/);
  // Fail-closed: no write of any kind was issued.
  assert.equal(state.requests.filter((r) => r.method !== "GET").length, 0);
});

test("HTTP errors surface only path and status, never host or token", async () => {
  const client = createGrafanaClient({
    fetchImpl: async () => jsonResponse(403, {}),
    tokenProvider: () => "sekrit-token",
  });
  await assert.rejects(client.listAlertRules(), (error) => {
    assert.match(error.message, /GET \/api\/v1\/provisioning\/alert-rules failed with HTTP 403/);
    assert.ok(!error.message.includes("sekrit"));
    assert.ok(!error.message.includes("amazonaws"));
    return true;
  });
});

test("ruler entries map to the provisioning shape with identical checksums", () => {
  const provisioning = rawRule("dfrmh7bc4yqrkf", "ALB 5xx > 10 in 5m");
  const rulerEntry = {
    for: provisioning.for,
    labels: {},
    annotations: {},
    grafana_alert: {
      uid: provisioning.uid,
      title: provisioning.title,
      condition: provisioning.condition,
      data: provisioning.data,
      no_data_state: provisioning.noDataState,
      exec_err_state: provisioning.execErrState,
      rule_group: provisioning.ruleGroup,
      namespace_uid: provisioning.folderUID,
      is_paused: false,
    },
  };
  const mapped = ruleFromRulerEntry(rulerEntry);
  assert.equal(queryChecksum(mapped), queryChecksum(provisioning));
});

test("listAlertRulesViaRuler flattens namespaces and maps entries", async () => {
  const provisioning = liveRulesFixture();
  const namespaces = {
    prod: [
      {
        name: "prod-alerts",
        rules: provisioning.map((r) => ({
          for: r.for,
          labels: {},
          annotations: {},
          grafana_alert: {
            uid: r.uid,
            title: r.title,
            condition: r.condition,
            data: r.data,
            no_data_state: r.noDataState,
            exec_err_state: r.execErrState,
            rule_group: r.ruleGroup,
            namespace_uid: r.folderUID,
            is_paused: false,
          },
        })),
      },
    ],
  };
  const requests = [];
  const client = createGrafanaClient({
    fetchImpl: async (url, init) => {
      requests.push({ url, method: init.method || "GET" });
      return jsonResponse(200, namespaces);
    },
    tokenProvider: () => "t",
  });
  const rules = await client.listAlertRulesViaRuler();
  assert.equal(requests[0].method, "GET");
  assert.equal(requests[0].url, `${WORKSPACE_BASE_URL}/api/ruler/grafana/api/v1/rules`);
  assert.equal(rules.length, 6);
  for (let i = 0; i < rules.length; i += 1) {
    assert.equal(queryChecksum(rules[i]), queryChecksum(provisioning[i]));
  }
});

// --- Secret resolution (fake execFile; value returned, never logged) ---------

// Fake execFile: answers sts get-caller-identity with `account`, then
// delegates secretsmanager calls to `onSecret`.
function fakeAws(account, onSecret) {
  const calls = [];
  const impl = async (cmd, args) => {
    calls.push({ cmd, args });
    if (args[0] === "sts") {
      return { stdout: JSON.stringify({ Account: account }) };
    }
    return onSecret(cmd, args);
  };
  return { impl, calls };
}

test("resolveSecretField checks caller identity, then parses the named field", async () => {
  const { impl, calls } = fakeAws(TARGET.awsAccount, async () => ({
    stdout: JSON.stringify({ grafanaWebhookSecret: "value-under-test" }),
  }));
  const value = await resolveSecretField("issue-tracker/app", "grafanaWebhookSecret", { execFileImpl: impl });
  assert.equal(value, "value-under-test");
  assert.deepEqual(calls[0].args.slice(0, 2), ["sts", "get-caller-identity"]);
  const sm = calls[1];
  assert.equal(sm.cmd, "aws");
  assert.deepEqual(sm.args.slice(0, 2), ["secretsmanager", "get-secret-value"]);
  assert.ok(sm.args.includes("issue-tracker/app"));
  assert.ok(sm.args.includes(TARGET.awsRegion));
});

test("a wrong AWS account is rejected before any secret read", async () => {
  const { impl, calls } = fakeAws("999999999999", async () => {
    throw new Error("secretsmanager must never be reached");
  });
  await assert.rejects(
    resolveSecretField("issue-tracker/app", "grafanaWebhookSecret", { execFileImpl: impl }),
    /not the fixed target account 157466816238/,
  );
  assert.equal(calls.filter((c) => c.args[0] === "secretsmanager").length, 0);
  // Direct gate check too.
  await assert.rejects(assertOperatorAccount(fakeAws("000000000000", async () => ({})).impl), /not the fixed target/);
  await assert.doesNotReject(assertOperatorAccount(fakeAws(TARGET.awsAccount, async () => ({})).impl));
});

test("resolveSecretField failures never echo secret material", async () => {
  const { impl } = fakeAws(TARGET.awsAccount, async () => {
    throw new Error("aws stderr containing something-sensitive");
  });
  await assert.rejects(resolveSecretField("issue-tracker/app", "x", { execFileImpl: impl }), (error) => {
    assert.ok(!error.message.includes("something-sensitive"));
    return true;
  });
  const { impl: missingField } = fakeAws(TARGET.awsAccount, async () => ({
    stdout: JSON.stringify({ other: "v" }),
  }));
  await assert.rejects(
    resolveSecretField("issue-tracker/app", "grafanaWebhookSecret", { execFileImpl: missingField }),
    /missing field/,
  );
});

// --- Normalization stability --------------------------------------------------

test("normalization is stable across ordering and timestamp noise", () => {
  const a = rawRule("dfrmh7bc4yqrkf", "ALB 5xx > 10 in 5m");
  const b = rawRule("dfrmh7bc4yqrkf", "ALB 5xx > 10 in 5m");
  assert.equal(queryChecksum(a), queryChecksum(b));
  const reordered = { for: a.for, data: a.data, condition: a.condition, title: a.title };
  const straight = { title: a.title, condition: a.condition, data: a.data, for: a.for };
  assert.equal(canonicalize(reordered), canonicalize(straight));
  const n = normalizeRule(a);
  assert.equal("updated" in n, false);
  assert.equal("version" in n, false);
  assert.equal("provenance" in n, false);
  assert.equal(n.title, a.title);
});

// --- Exactly six known UIDs ---------------------------------------------------

test("accepts exactly the six known UIDs", () => {
  assert.doesNotThrow(() => verifyUidAllowlist(KNOWN_UIDS));
});

test("rejects an unknown, extra, or missing UID", () => {
  assert.throws(() => verifyUidAllowlist([...KNOWN_UIDS, "zzzunknown"]), /Unknown rule UID/);
  assert.throws(() => verifyUidAllowlist(KNOWN_UIDS.slice(1)), /missing/);
});

// --- Drift is a hard failure ---------------------------------------------------

test("title drift and unexpected rules are detected", () => {
  const tampered = KNOWN_RULES.map((r) => ({ uid: r.uid, title: r.uid === LOG_RULE_UID ? "CHANGED" : r.title }));
  assert.ok(detectDrift(tampered).some((m) => m.includes(LOG_RULE_UID)));
  const extra = [...KNOWN_RULES.map((r) => ({ uid: r.uid, title: r.title })), { uid: "extra999", title: "x" }];
  assert.ok(detectDrift(extra).some((m) => m.includes("extra999")));
});

test("apply hard-rejects a live query mismatch rather than recreating", async () => {
  const state = newState();
  const repoRoot = fixtureRepo(state.rules);
  const client = realClient(state);
  const receiptPath = tmpReceiptPath();
  await runExport({ client, receiptPath, repoRoot, now: () => "2026-07-14T00:00:00Z" });
  state.rules.find((r) => r.uid === "dfrmh7bc4yqrkf").data = [{ refId: "A", model: { expr: "TAMPERED" } }];
  await assert.rejects(
    runApply({ client, secretResolver: async () => "secret", receiptPath, repoRoot }),
    /drifted/,
  );
  const puts = state.requests.filter((r) => r.method === "PUT" && r.path.includes("dfrmh7bc4yqrkf"));
  assert.equal(puts.length, 0);
});

test("export refuses when live rules drift from the checked-in definitions", async () => {
  const state = newState();
  const repoRoot = fixtureRepo(); // checked-in overlay from pristine fixtures
  state.rules.find((r) => r.uid === LOG_RULE_UID).data = [{ refId: "A", model: { expr: "PRE-DRIFTED" } }];
  const client = realClient(state);
  await assert.rejects(
    runExport({ client, receiptPath: tmpReceiptPath(), repoRoot, now: () => "2026-07-14T00:00:00Z" }),
    /drifted from the checked-in definition/,
  );
});

test("apply refuses when live matches the receipt but drifted from the checked-in definitions", async () => {
  // Drift happened BEFORE the export: the receipt agrees with live, so only
  // the checked-in gate can catch it.
  const pristine = liveRulesFixture();
  const repoRoot = fixtureRepo(pristine);
  const drifted = liveRulesFixture();
  drifted.find((r) => r.uid === "cfrmh7d7od8g0c").data = [{ refId: "A", model: { expr: "PRE-DRIFTED" } }];
  const state = newState(drifted);
  const client = realClient(state);
  // Craft a receipt that matches the drifted live state (as a same-session
  // export of the drifted workspace would).
  const receiptPath = tmpReceiptPath();
  const checksums = Object.fromEntries(drifted.map((r) => [r.uid, queryChecksum(r)]));
  fs.writeFileSync(
    receiptPath,
    JSON.stringify({
      schemaVersion: 1,
      kind: "grafana-alerting-rollback-receipt",
      target: { ...TARGET },
      before: { rules: {}, contactPoints: [], notificationPolicy: {} },
      checksums: { rules: checksums, notificationPolicy: "x" },
    }),
    { mode: 0o600 },
  );
  await assert.rejects(
    runApply({ client, secretResolver: async () => "s", receiptPath, repoRoot }),
    /drifted from the checked-in definition.*cfrmh7d7od8g0c/,
  );
  assert.equal(state.requests.filter((r) => r.method !== "GET").length, 0);
});

// --- Only the log rule may carry log annotations -------------------------------

test("only bfrmh7e7x2k8wd may contain log annotations", () => {
  const good = KNOWN_RULES.map((r) => ({
    uid: r.uid,
    annotations: r.uid === LOG_RULE_UID
      ? {
          runbook_url: "x",
          proliferate_log_group: "/ecs/proliferate-prod",
          proliferate_log_filter_pattern: "CRITICAL_FAILURE",
          proliferate_log_region: "us-east-1",
        }
      : { runbook_url: "x" },
  }));
  assert.doesNotThrow(() => assertLogAnnotationsOnlyOnLogRule(good));
  const bad = JSON.parse(JSON.stringify(good));
  bad[0].annotations.proliferate_log_group = "/ecs/proliferate-prod";
  assert.throws(() => assertLogAnnotationsOnlyOnLogRule(bad), /must not carry log-lookup/);
  const missing = KNOWN_RULES.map((r) => ({ uid: r.uid, annotations: { runbook_url: "x" } }));
  assert.throws(() => assertLogAnnotationsOnlyOnLogRule(missing), /missing log annotations/);
});

// --- Contact-point serialization: reference but no secret ----------------------

test("contact template has a secret reference and no secret value", () => {
  const contact = JSON.parse(
    fs.readFileSync(path.join(REPO_ROOT, "server/infra/observability/grafana/issue-tracker-contact.json"), "utf8"),
  );
  assert.doesNotThrow(() => assertContactTemplateSafe(contact));
  assert.ok(JSON.stringify(contact).includes(WEBHOOK_SECRET_REF));
  assert.equal(contact.contactPoint.secureSettings.authorization_credentials.secretRef, WEBHOOK_SECRET_REF);
});

test("an inline credential value in the contact point is rejected", () => {
  const contact = JSON.parse(
    fs.readFileSync(path.join(REPO_ROOT, "server/infra/observability/grafana/issue-tracker-contact.json"), "utf8"),
  );
  contact.contactPoint.secureSettings.authorization_credentials = "glsa_live_secret_value_1234567890";
  assert.throws(() => assertContactTemplateSafe(contact), /reference/);
});

// --- Redaction coverage ---------------------------------------------------------

test("redaction covers urls, bearer values, and long tokens", () => {
  const raw = "POST https://issues.proliferate.com/v1/ingest/grafana Authorization: Bearer glsa_abcdefghijklmnopqrstuvwxyz123";
  const red = redact(raw);
  assert.ok(!red.includes("issues.proliferate.com"));
  assert.ok(!red.includes("glsa_abcdefghijklmnopqrstuvwxyz123"));
  assert.ok(red.includes("<redacted-url>"));
});

// --- Target verification --------------------------------------------------------

test("wrong account, region, or workspace is rejected", () => {
  const good = { ...TARGET };
  assert.throws(() => verifyTarget({ ...good, awsAccount: "000000000000" }), /awsAccount/);
  assert.throws(() => verifyTarget({ ...good, awsRegion: "eu-west-1" }), /awsRegion/);
  assert.throws(() => verifyTarget({ ...good, grafanaWorkspaceId: "g-wrong" }), /grafanaWorkspaceId/);
});

// --- apply cannot mutate the notification policy --------------------------------

test("apply leaves the notification policy untouched and only touches the tracker contact point", async () => {
  const state = newState();
  const repoRoot = fixtureRepo(state.rules);
  const client = realClient(state);
  const receiptPath = tmpReceiptPath();
  await runExport({ client, receiptPath, repoRoot, now: () => "2026-07-14T00:00:00Z" });
  const policyBefore = JSON.stringify(state.notificationPolicy);
  const result = await runApply({ client, secretResolver: async () => "resolved-secret", receiptPath, repoRoot });
  assert.equal(result.policyUnchanged, true);
  assert.equal(JSON.stringify(state.notificationPolicy), policyBefore);
  // No request ever targeted the policies route with a write.
  assert.ok(!state.requests.some((r) => r.method !== "GET" && r.path.endsWith("/policies")));
  // The only contact-point write is one Alertmanager-config POST appending the
  // tracker receiver, with the resolved credential in secureSettings only.
  assert.equal(state.requests.filter((r) => r.method !== "GET" && r.path.includes("contact-points")).length, 0);
  const amWrites = state.requests.filter((r) => r.method === "POST" && r.path === ALERTMANAGER_CONFIG);
  assert.equal(amWrites.length, 1);
  const posted = JSON.parse(amWrites[0].body).alertmanager_config.receivers.at(-1);
  assert.equal(posted.name, CONTACT_POINT_NAME);
  const postedCfg = posted.grafana_managed_receiver_configs[0];
  assert.equal(postedCfg.secureSettings.authorization_credentials, "resolved-secret");
  assert.equal("authorization_credentials" in postedCfg.settings, false);
  // The receipt captured the full before-config (no tracker receiver yet).
  const receipt = JSON.parse(fs.readFileSync(receiptPath, "utf8"));
  assert.ok(receipt.before.alertmanagerConfig);
  assert.ok(!receipt.before.alertmanagerConfig.alertmanager_config.receivers.some((r) => r.name === CONTACT_POINT_NAME));
  for (const uid of KNOWN_UIDS) {
    assert.equal(result.beforeChecksums[uid], result.afterChecksums[uid]);
  }
});

test("apply throws if the policy is mutated underneath it", async () => {
  const state = newState();
  const repoRoot = fixtureRepo(state.rules);
  const client = realClient(state);
  const receiptPath = tmpReceiptPath();
  await runExport({ client, receiptPath, repoRoot, now: () => "2026-07-14T00:00:00Z" });
  state.onWrite = (method, p) => {
    if (p === ALERTMANAGER_CONFIG) state.notificationPolicy.receiver = "tampered";
  };
  await assert.rejects(
    runApply({ client, secretResolver: async () => "s", receiptPath, repoRoot }),
    /Notification policy changed/,
  );
});

test("restore replays the before-export and removes a newly created tracker point", async () => {
  const state = newState();
  const repoRoot = fixtureRepo(state.rules);
  const client = realClient(state);
  const receiptPath = tmpReceiptPath();
  await runExport({ client, receiptPath, repoRoot, now: () => "2026-07-14T00:00:00Z" });
  await runApply({ client, secretResolver: async () => "s", receiptPath, repoRoot });
  const receiverNames = () => state.amConfig.alertmanager_config.receivers.map((r) => r.name);
  assert.ok(receiverNames().includes(CONTACT_POINT_NAME));
  const { restored } = await runRestore({ client, receiptPath });
  assert.deepEqual(restored.sort(), [...KNOWN_UIDS].sort());
  assert.deepEqual(receiverNames(), ["slack-eng-triage", "slack-ops-alerts"]);
});

// --- Receipt path safety ---------------------------------------------------------

test("receipt path refuses worktree and relative paths, accepts private absolute ones", () => {
  assert.throws(() => assertPrivateReceiptPath("relative/path.json"), /absolute/);
  assert.throws(() => assertPrivateReceiptPath(path.join(REPO_ROOT, "receipt.json")), /outside the Git worktree/);
  assert.doesNotThrow(() => assertPrivateReceiptPath(tmpReceiptPath()));
});

// --- Checked-in overlay: identity + checksum consistency --------------------------

test("checked-in overlay validates and every checksum reproduces from its checked-in model", () => {
  const overlay = JSON.parse(
    fs.readFileSync(path.join(REPO_ROOT, "server/infra/observability/grafana/production-alerts.json"), "utf8"),
  );
  assert.doesNotThrow(() => validateOverlayDocument(overlay));
  for (const rule of overlay.rules) {
    assert.ok(rule.queryModel && typeof rule.queryModel === "object", `${rule.uid} has a captured queryModel`);
    assert.equal(rule.queryModel.title, rule.title);
    assert.equal(rule.queryChecksum, sha256(canonicalize(rule.queryModel)), `${rule.uid} checksum reproduces`);
    // Safe content: no secret-shaped material in the stored model.
    const serialized = JSON.stringify(rule.queryModel).toLowerCase();
    for (const needle of ["glsa_", "authorization", "secret", "password", "cookie"]) {
      assert.ok(!serialized.includes(needle), `${rule.uid} model contains no "${needle}"`);
    }
  }
});

test("a tampered checked-in model fails validation", () => {
  const overlay = JSON.parse(
    fs.readFileSync(path.join(REPO_ROOT, "server/infra/observability/grafana/production-alerts.json"), "utf8"),
  );
  overlay.rules[0].queryModel.condition = "tampered";
  assert.throws(() => validateOverlayDocument(overlay), /queryChecksum does not match/);
});

test("runCheck passes offline and detects drift against a tampered snapshot", () => {
  assert.doesNotThrow(() => runCheck());
  const snapshot = { rules: KNOWN_RULES.map((r) => ({ uid: r.uid, title: r.uid === "dfrmh7bc4yqrkf" ? "WRONG" : r.title })) };
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "grafana-snap-"));
  const snapPath = path.join(dir, "snap.json");
  fs.writeFileSync(snapPath, JSON.stringify(snapshot));
  assert.throws(() => runCheck({ snapshotPath: snapPath }), /Drift detected/);
});

test("ALLOWED_ANNOTATION_KEYS includes only runbook_url plus the three log keys", () => {
  assert.deepEqual([...ALLOWED_ANNOTATION_KEYS].sort(), [
    "proliferate_log_filter_pattern",
    "proliferate_log_group",
    "proliferate_log_region",
    "runbook_url",
  ]);
});
