"""Daytona sandbox constants."""

DAYTONA_TEMPLATE_NAME = "debian:12.9"
DAYTONA_TEMPLATE_VERSION = "v1"
DAYTONA_CREATE_TIMEOUT_SECONDS = 120
DAYTONA_START_TIMEOUT_SECONDS = 60
DAYTONA_STOP_TIMEOUT_SECONDS = 60
DAYTONA_DELETE_TIMEOUT_SECONDS = 60
DAYTONA_AUTO_STOP_INTERVAL_MINUTES = 0
DAYTONA_AUTO_ARCHIVE_INTERVAL_MINUTES = 0
DAYTONA_AUTO_DELETE_INTERVAL_MINUTES = -1
DAYTONA_RUNTIME_PORT = 8457
DAYTONA_USER_HOME = "/home/daytona"
DAYTONA_RUNTIME_WORKDIR = "/home/daytona/workspace"
DAYTONA_RUNTIME_BINARY_PATH = "/home/daytona/anyharness"
