from __future__ import annotations

import uuid
from datetime import UTC, datetime
from types import SimpleNamespace
from typing import Any

import pytest

from proliferate.db.store.cloud_repo_config import CloudRepoConfigValue, CloudRepoFileValue
from proliferate.db.store.managed_sandbox_repo_materializations import (
    ManagedSandboxRepoMaterializationValue,
)
from proliferate.db.store.managed_sandboxes import ManagedSandboxValue
from proliferate.server.cloud.managed_sandboxes.materialization import (
    github_credentials,
    manifests,
    repos,
)


def _repo_config(
    *,
    env_vars: dict[str, str] | None = None,
    env_vars_version: int = 0,
    files_version: int = 0,
    setup_script: str = "",
    setup_script_version: int = 0,
    tracked_files: tuple[CloudRepoFileValue, ...] = (),
) -> CloudRepoConfigValue:
    now = datetime.now(UTC)
    return CloudRepoConfigValue(
        id=uuid.uuid4(),
        owner_scope="personal",
        user_id=uuid.uuid4(),
        organization_id=None,
        git_owner="acme",
        git_repo_name="rocket",
        configured=True,
        configured_at=now,
        default_branch="main",
        env_vars=env_vars or {},
        env_vars_version=env_vars_version,
        setup_script=setup_script,
        setup_script_version=setup_script_version,
        run_command="",
        files_version=files_version,
        tracked_files=tracked_files,
        created_at=now,
        updated_at=now,
    )


def _sandbox(*, runtime_generation: int = 1) -> ManagedSandboxValue:
    now = datetime.now(UTC)
    return ManagedSandboxValue(
        id=uuid.uuid4(),
        owner_scope="personal",
        owner_user_id=uuid.uuid4(),
        organization_id=None,
        created_by_user_id=uuid.uuid4(),
        billing_subject_id=uuid.uuid4(),
        status="ready",
        last_error=None,
        e2b_sandbox_id="sbx",
        e2b_template_ref="template",
        anyharness_base_url="https://runtime.example.invalid",
        anyharness_bearer_token_ciphertext="token",
        anyharness_data_key_ciphertext="data-key",
        runtime_generation=runtime_generation,
        created_at=now,
        updated_at=now,
        ready_at=now,
        last_health_at=now,
        destroyed_at=None,
    )


def _materialization(
    *,
    sandbox_generation: int = 1,
    applied_files_version: int = 0,
    applied_setup_script_version: int = 0,
    applied_env_vars_version: int = 0,
) -> ManagedSandboxRepoMaterializationValue:
    now = datetime.now(UTC)
    return ManagedSandboxRepoMaterializationValue(
        id=uuid.uuid4(),
        managed_sandbox_id=uuid.uuid4(),
        cloud_repo_config_id=uuid.uuid4(),
        sandbox_generation=sandbox_generation,
        repo_path="/home/user/workspace/repos/acme/rocket",
        status="ready",
        anyharness_repo_root_id="repo-root",
        anyharness_workspace_id="workspace",
        applied_files_version=applied_files_version,
        applied_setup_script_version=applied_setup_script_version,
        applied_env_vars_version=applied_env_vars_version,
        last_error=None,
        created_at=now,
        updated_at=now,
        last_attempted_at=now,
        materialized_at=now,
    )


def test_render_env_file_matches_anyharness_materialized_env_contract() -> None:
    contents = manifests.render_env_file(
        {
            "API_BASE_URL": "https://example.test",
            "QUOTED": "a'b",
        }
    )

    assert contents == (
        "# Generated by Proliferate. Do not edit.\n"
        "export API_BASE_URL='https://example.test'\n"
        "export QUOTED='a'\\''b'\n"
    )


def test_materialization_freshness_is_repo_lifecycle_not_secret_version() -> None:
    repo_config = _repo_config(env_vars={"API_BASE_URL": "https://example.test"})
    materialization = _materialization(applied_env_vars_version=0)

    assert repos._materialization_versions_match(
        materialization,
        sandbox=_sandbox(),
        repo_config=repo_config,
        run_setup=False,
    )

    stale_generation = _materialization(sandbox_generation=0)
    assert not repos._materialization_versions_match(
        stale_generation,
        sandbox=_sandbox(runtime_generation=1),
        repo_config=repo_config,
        run_setup=False,
    )


def test_materialization_freshness_includes_setup_version_when_setup_runs() -> None:
    repo_config = _repo_config(setup_script="pnpm install", setup_script_version=2)
    materialization = _materialization(applied_setup_script_version=1)

    assert not repos._materialization_versions_match(
        materialization,
        sandbox=_sandbox(),
        repo_config=repo_config,
        run_setup=True,
    )

    current = _materialization(applied_setup_script_version=2)
    assert repos._materialization_versions_match(
        current,
        sandbox=_sandbox(),
        repo_config=repo_config,
        run_setup=True,
    )


@pytest.mark.asyncio
async def test_managed_materialization_paths_include_workspace_secrets(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    async def _workspace_secret_relative_paths(
        *_args: object,
        **_kwargs: object,
    ) -> tuple[str, ...]:
        return (".env.example", "config/app.env")

    monkeypatch.setattr(
        repos,
        "workspace_secret_relative_paths",
        _workspace_secret_relative_paths,
    )

    assert await repos._managed_materialization_paths(
        object(),
        repo_config=_repo_config(),
    ) == (
        ".env.example",
        ".proliferate/env/workspace.env",
        ".proliferate/env/workspace.manifest.json",
        "config/app.env",
    )


@pytest.mark.asyncio
async def test_clone_dirty_check_allows_managed_workspace_secret_paths(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls: list[dict[str, Any]] = []

    async def _capture_script(*_args: object, **kwargs: Any) -> None:
        calls.append(kwargs)

    async def _workspace_secret_relative_paths(
        *_args: object,
        **_kwargs: object,
    ) -> tuple[str, ...]:
        return (".env.example", "config/app.env")

    monkeypatch.setattr(repos, "run_materialization_script", _capture_script)
    monkeypatch.setattr(
        repos,
        "workspace_secret_relative_paths",
        _workspace_secret_relative_paths,
    )

    await repos._clone_or_update_repo(
        object(),
        object(),
        repo_config=_repo_config(),
        repo_path="/home/user/workspace/repos/acme/rocket",
        sandbox=_sandbox(),
    )

    assert calls
    command = calls[0]["script"]
    assert ".proliferate/env/workspace.env" in command
    assert ".proliferate/env/workspace.manifest.json" in command
    assert ".env.example" in command
    assert "config/app.env" in command
    assert "status --porcelain=v1 -z --untracked-files=all" in command
    assert "Repository has unmanaged local changes" in command


@pytest.mark.asyncio
async def test_git_credential_readiness_uses_worker_lease(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls: list[dict[str, Any]] = []

    async def _capture_script(*_args: object, **kwargs: Any) -> None:
        calls.append(kwargs)

    monkeypatch.setattr(
        github_credentials,
        "run_materialization_script",
        _capture_script,
    )
    target = SimpleNamespace(
        runtime_context=SimpleNamespace(home_dir="/home/user"),
    )
    sandbox = SimpleNamespace(id=uuid.uuid4())

    result = await github_credentials.ensure_sandbox_git_credentials_ready(
        object(),
        sandbox=sandbox,
        user_id=uuid.uuid4(),
        target=target,
    )

    assert result is target
    assert calls
    assert calls[0]["label"] == "managed_sandbox_git_credentials_ready"
    command = calls[0]["script"]
    assert "proliferate-git-credential-helper" in command
    assert ".proliferate/git/github.com/token" in command
    assert ".proliferate/git/github.com/meta.json" in command
    assert "github_app_user_to_server" in command
    assert "GitHub credentials are not ready in the managed sandbox." in command
    assert "credential.https://github.com.helper" in command
