from __future__ import annotations

import uuid
from datetime import UTC, datetime
from types import SimpleNamespace
from typing import Any

import pytest

from proliferate.db.store.cloud_repo_config import CloudRepoConfigValue, CloudRepoFileValue
from proliferate.db.store.managed_sandbox_repo_materializations import (
    ManagedSandboxRepoMaterializationValue,
)
from proliferate.db.store.managed_sandboxes import ManagedSandboxValue
from proliferate.server.cloud.managed_sandboxes import repo_materialization


def _repo_file(relative_path: str) -> CloudRepoFileValue:
    now = datetime.now(UTC)
    return CloudRepoFileValue(
        relative_path=relative_path,
        content="value",
        content_sha256="sha",
        byte_size=5,
        created_at=now,
        updated_at=now,
        last_synced_at=now,
    )


def _repo_config(
    *,
    env_vars: dict[str, str] | None = None,
    env_vars_version: int = 0,
    files_version: int = 0,
    setup_script: str = "",
    setup_script_version: int = 0,
    tracked_files: tuple[CloudRepoFileValue, ...] = (),
) -> CloudRepoConfigValue:
    now = datetime.now(UTC)
    return CloudRepoConfigValue(
        id=uuid.uuid4(),
        owner_scope="personal",
        user_id=uuid.uuid4(),
        organization_id=None,
        git_owner="acme",
        git_repo_name="rocket",
        configured=True,
        configured_at=now,
        default_branch="main",
        env_vars=env_vars or {},
        env_vars_version=env_vars_version,
        setup_script=setup_script,
        setup_script_version=setup_script_version,
        run_command="",
        files_version=files_version,
        tracked_files=tracked_files,
        created_at=now,
        updated_at=now,
    )


def _sandbox(*, runtime_generation: int = 1) -> ManagedSandboxValue:
    now = datetime.now(UTC)
    return ManagedSandboxValue(
        id=uuid.uuid4(),
        owner_scope="personal",
        owner_user_id=uuid.uuid4(),
        organization_id=None,
        created_by_user_id=uuid.uuid4(),
        billing_subject_id=uuid.uuid4(),
        status="ready",
        last_error=None,
        e2b_sandbox_id="sbx",
        e2b_template_ref="template",
        anyharness_base_url="https://runtime.example.invalid",
        anyharness_bearer_token_ciphertext="token",
        anyharness_data_key_ciphertext="data-key",
        runtime_generation=runtime_generation,
        created_at=now,
        updated_at=now,
        ready_at=now,
        last_health_at=now,
        destroyed_at=None,
    )


def _materialization(
    *,
    sandbox_generation: int = 1,
    applied_files_version: int = 0,
    applied_setup_script_version: int = 0,
    applied_env_vars_version: int = 0,
) -> ManagedSandboxRepoMaterializationValue:
    now = datetime.now(UTC)
    return ManagedSandboxRepoMaterializationValue(
        id=uuid.uuid4(),
        managed_sandbox_id=uuid.uuid4(),
        cloud_repo_config_id=uuid.uuid4(),
        sandbox_generation=sandbox_generation,
        repo_path="/home/user/workspace/repos/acme/rocket",
        status="ready",
        anyharness_repo_root_id="repo-root",
        anyharness_workspace_id="workspace",
        applied_files_version=applied_files_version,
        applied_setup_script_version=applied_setup_script_version,
        applied_env_vars_version=applied_env_vars_version,
        last_error=None,
        created_at=now,
        updated_at=now,
        last_attempted_at=now,
        materialized_at=now,
    )


def test_session_env_contents_matches_anyharness_materialized_env_contract() -> None:
    contents = repo_materialization._session_env_contents(
        {
            "API_BASE_URL": "https://example.test",
            "QUOTED": "a'b",
        }
    )

    assert contents == (
        "# Generated by Proliferate. Do not edit.\n"
        "export API_BASE_URL='https://example.test'\n"
        "export QUOTED='a'\\''b'\n"
    )


def test_materialization_freshness_includes_env_var_version() -> None:
    repo_config = _repo_config(
        env_vars={"API_BASE_URL": "https://example.test"}, env_vars_version=2
    )
    materialization = _materialization(applied_env_vars_version=1)

    assert not repo_materialization._materialization_versions_match(
        materialization,
        sandbox=_sandbox(),
        repo_config=repo_config,
        run_setup=False,
    )

    current = _materialization(applied_env_vars_version=2)
    assert repo_materialization._materialization_versions_match(
        current,
        sandbox=_sandbox(),
        repo_config=repo_config,
        run_setup=False,
    )


@pytest.mark.asyncio
async def test_apply_repo_env_vars_writes_private_session_env(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls: list[dict[str, Any]] = []

    async def _capture_command(*_args: object, **kwargs: Any) -> SimpleNamespace:
        calls.append(kwargs)
        return SimpleNamespace(exit_code=0, stdout="", stderr="")

    monkeypatch.setattr(repo_materialization, "run_sandbox_command_logged", _capture_command)
    repo_config = _repo_config(env_vars={"API_BASE_URL": "https://example.test"})

    await repo_materialization._apply_repo_env_vars(
        object(),
        object(),
        runtime_context=object(),
        repo_path="/home/user/workspace/repos/acme/rocket",
        repo_config=repo_config,
        managed_sandbox_id=uuid.uuid4(),
    )

    assert calls
    call = calls[0]
    assert call["label"] == "managed_repo_apply_env_vars"
    assert call["envs"]["PROLIFERATE_HAS_SESSION_ENV"] == "1"
    assert (
        "export API_BASE_URL='https://example.test'"
        in call["envs"]["PROLIFERATE_SESSION_ENV_CONTENTS"]
    )
    command = call["command"]
    assert ".proliferate/env/session.env" in command
    assert "chmod 600" in command
    assert "Refusing to materialize repo env vars through a symlink." in command


@pytest.mark.asyncio
async def test_clone_dirty_check_allows_managed_materialization_paths(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls: list[dict[str, Any]] = []

    async def _capture_command(*_args: object, **kwargs: Any) -> SimpleNamespace:
        calls.append(kwargs)
        return SimpleNamespace(exit_code=0, stdout="", stderr="")

    monkeypatch.setattr(repo_materialization, "run_sandbox_command_logged", _capture_command)
    repo_config = _repo_config(
        tracked_files=(
            _repo_file(".env.example"),
            _repo_file("config/app.env"),
        )
    )

    await repo_materialization._clone_or_update_repo(
        object(),
        object(),
        runtime_context=object(),
        repo_config=repo_config,
        repo_path="/home/user/workspace/repos/acme/rocket",
        managed_sandbox_id=uuid.uuid4(),
    )

    assert calls
    assert "envs" not in calls[0]
    command = calls[0]["command"]
    assert "proliferate-git-credential-helper" in command
    assert ".proliferate/git/github.com/token" in command
    assert ".proliferate/git/github.com/meta.json" in command
    assert "github_app_user_to_server" in command
    assert "GitHub credentials are not ready in the managed sandbox." in command
    assert ".proliferate/env/session.env" in command
    assert ".env.example" in command
    assert "config/app.env" in command
    assert "status --porcelain=v1 -z --untracked-files=all" in command
    assert "Repository has unmanaged local changes" in command
