// GENERATED by scripts/vendor-provider-registry.mjs — do not edit by hand.
// Provider marks vendored from https://models.dev/logos/<id>.svg (models.dev
// is MIT; the marks are unaltered). Imported as asset URLs so the SVG bytes
// are emitted as files, never inlined into a JS chunk. Only the lazily
// loaded provider picker imports this module.

import logo0 from "../assets/provider-logos/302ai.svg?no-inline";
import logo1 from "../assets/provider-logos/abacus.svg?no-inline";
import logo2 from "../assets/provider-logos/abliteration-ai.svg?no-inline";
import logo3 from "../assets/provider-logos/ai-router.svg?no-inline";
import logo4 from "../assets/provider-logos/aiand.svg?no-inline";
import logo5 from "../assets/provider-logos/aihubmix.svg?no-inline";
import logo6 from "../assets/provider-logos/aki-io.svg?no-inline";
import logo7 from "../assets/provider-logos/alibaba.svg?no-inline";
import logo8 from "../assets/provider-logos/alibaba-cn.svg?no-inline";
import logo9 from "../assets/provider-logos/alibaba-coding-plan.svg?no-inline";
import logo10 from "../assets/provider-logos/alibaba-coding-plan-cn.svg?no-inline";
import logo11 from "../assets/provider-logos/alibaba-token-plan.svg?no-inline";
import logo12 from "../assets/provider-logos/alibaba-token-plan-cn.svg?no-inline";
import logo13 from "../assets/provider-logos/amazon-bedrock.svg?no-inline";
import logo14 from "../assets/provider-logos/ambient.svg?no-inline";
import logo15 from "../assets/provider-logos/anthropic.svg?no-inline";
import logo16 from "../assets/provider-logos/anyapi.svg?no-inline";
import logo17 from "../assets/provider-logos/atomic-chat.svg?no-inline";
import logo18 from "../assets/provider-logos/auriko.svg?no-inline";
import logo19 from "../assets/provider-logos/azure.svg?no-inline";
import logo20 from "../assets/provider-logos/azure-cognitive-services.svg?no-inline";
import logo21 from "../assets/provider-logos/bailing.svg?no-inline";
import logo22 from "../assets/provider-logos/baseten.svg?no-inline";
import logo23 from "../assets/provider-logos/berget.svg?no-inline";
import logo24 from "../assets/provider-logos/blueclaw.svg?no-inline";
import logo25 from "../assets/provider-logos/cerebras.svg?no-inline";
import logo26 from "../assets/provider-logos/chutes.svg?no-inline";
import logo27 from "../assets/provider-logos/clarifai.svg?no-inline";
import logo28 from "../assets/provider-logos/claudinio.svg?no-inline";
import logo29 from "../assets/provider-logos/cline-pass.svg?no-inline";
import logo30 from "../assets/provider-logos/cloudferro-sherlock.svg?no-inline";
import logo31 from "../assets/provider-logos/cloudflare-ai-gateway.svg?no-inline";
import logo32 from "../assets/provider-logos/cloudflare-workers-ai.svg?no-inline";
import logo33 from "../assets/provider-logos/cohere.svg?no-inline";
import logo34 from "../assets/provider-logos/cortecs.svg?no-inline";
import logo35 from "../assets/provider-logos/crof.svg?no-inline";
import logo36 from "../assets/provider-logos/crossmodel.svg?no-inline";
import logo37 from "../assets/provider-logos/daoxe.svg?no-inline";
import logo38 from "../assets/provider-logos/databricks.svg?no-inline";
import logo39 from "../assets/provider-logos/deepinfra.svg?no-inline";
import logo40 from "../assets/provider-logos/deepseek.svg?no-inline";
import logo41 from "../assets/provider-logos/digitalocean.svg?no-inline";
import logo42 from "../assets/provider-logos/dinference.svg?no-inline";
import logo43 from "../assets/provider-logos/drun.svg?no-inline";
import logo44 from "../assets/provider-logos/ebcloud.svg?no-inline";
import logo45 from "../assets/provider-logos/empiriolabs.svg?no-inline";
import logo46 from "../assets/provider-logos/evroc.svg?no-inline";
import logo47 from "../assets/provider-logos/fastrouter.svg?no-inline";
import logo48 from "../assets/provider-logos/fireworks-ai.svg?no-inline";
import logo49 from "../assets/provider-logos/freemodel.svg?no-inline";
import logo50 from "../assets/provider-logos/friendli.svg?no-inline";
import logo51 from "../assets/provider-logos/frogbot.svg?no-inline";
import logo52 from "../assets/provider-logos/github-copilot.svg?no-inline";
import logo53 from "../assets/provider-logos/github-models.svg?no-inline";
import logo54 from "../assets/provider-logos/gitlab.svg?no-inline";
import logo55 from "../assets/provider-logos/gmicloud.svg?no-inline";
import logo56 from "../assets/provider-logos/google.svg?no-inline";
import logo57 from "../assets/provider-logos/google-vertex.svg?no-inline";
import logo58 from "../assets/provider-logos/google-vertex-anthropic.svg?no-inline";
import logo59 from "../assets/provider-logos/groq.svg?no-inline";
import logo60 from "../assets/provider-logos/helicone.svg?no-inline";
import logo61 from "../assets/provider-logos/hetzner.svg?no-inline";
import logo62 from "../assets/provider-logos/hpc-ai.svg?no-inline";
import logo63 from "../assets/provider-logos/huggingface.svg?no-inline";
import logo64 from "../assets/provider-logos/iflowcn.svg?no-inline";
import logo65 from "../assets/provider-logos/inception.svg?no-inline";
import logo66 from "../assets/provider-logos/inceptron.svg?no-inline";
import logo67 from "../assets/provider-logos/inference.svg?no-inline";
import logo68 from "../assets/provider-logos/inferx.svg?no-inline";
import logo69 from "../assets/provider-logos/io-net.svg?no-inline";
import logo70 from "../assets/provider-logos/jiekou.svg?no-inline";
import logo71 from "../assets/provider-logos/kenari.svg?no-inline";
import logo72 from "../assets/provider-logos/kilo.svg?no-inline";
import logo73 from "../assets/provider-logos/kimi-for-coding.svg?no-inline";
import logo74 from "../assets/provider-logos/kuae-cloud-coding-plan.svg?no-inline";
import logo75 from "../assets/provider-logos/lilac.svg?no-inline";
import logo76 from "../assets/provider-logos/llama.svg?no-inline";
import logo77 from "../assets/provider-logos/llmgateway.svg?no-inline";
import logo78 from "../assets/provider-logos/llmtr.svg?no-inline";
import logo79 from "../assets/provider-logos/lmstudio.svg?no-inline";
import logo80 from "../assets/provider-logos/longcat.svg?no-inline";
import logo81 from "../assets/provider-logos/lucidquery.svg?no-inline";
import logo82 from "../assets/provider-logos/lynkr.svg?no-inline";
import logo83 from "../assets/provider-logos/meganova.svg?no-inline";
import logo84 from "../assets/provider-logos/merge-gateway.svg?no-inline";
import logo85 from "../assets/provider-logos/meta.svg?no-inline";
import logo86 from "../assets/provider-logos/minimax.svg?no-inline";
import logo87 from "../assets/provider-logos/minimax-cn.svg?no-inline";
import logo88 from "../assets/provider-logos/minimax-cn-coding-plan.svg?no-inline";
import logo89 from "../assets/provider-logos/minimax-coding-plan.svg?no-inline";
import logo90 from "../assets/provider-logos/mistral.svg?no-inline";
import logo91 from "../assets/provider-logos/mixlayer.svg?no-inline";
import logo92 from "../assets/provider-logos/moark.svg?no-inline";
import logo93 from "../assets/provider-logos/model-oracle-ai.svg?no-inline";
import logo94 from "../assets/provider-logos/modelscope.svg?no-inline";
import logo95 from "../assets/provider-logos/moonshotai.svg?no-inline";
import logo96 from "../assets/provider-logos/moonshotai-cn.svg?no-inline";
import logo97 from "../assets/provider-logos/morph.svg?no-inline";
import logo98 from "../assets/provider-logos/nano-gpt.svg?no-inline";
import logo99 from "../assets/provider-logos/nearai.svg?no-inline";
import logo100 from "../assets/provider-logos/nebius.svg?no-inline";
import logo101 from "../assets/provider-logos/neon.svg?no-inline";
import logo102 from "../assets/provider-logos/neuralwatt.svg?no-inline";
import logo103 from "../assets/provider-logos/nova.svg?no-inline";
import logo104 from "../assets/provider-logos/novita-ai.svg?no-inline";
import logo105 from "../assets/provider-logos/nvidia.svg?no-inline";
import logo106 from "../assets/provider-logos/ofox.svg?no-inline";
import logo107 from "../assets/provider-logos/ollama-cloud.svg?no-inline";
import logo108 from "../assets/provider-logos/openai.svg?no-inline";
import logo109 from "../assets/provider-logos/opencode.svg?no-inline";
import logo110 from "../assets/provider-logos/opencode-go.svg?no-inline";
import logo111 from "../assets/provider-logos/openrouter.svg?no-inline";
import logo112 from "../assets/provider-logos/orcarouter.svg?no-inline";
import logo113 from "../assets/provider-logos/ovhcloud.svg?no-inline";
import logo114 from "../assets/provider-logos/perplexity.svg?no-inline";
import logo115 from "../assets/provider-logos/perplexity-agent.svg?no-inline";
import logo116 from "../assets/provider-logos/pioneer.svg?no-inline";
import logo117 from "../assets/provider-logos/poe.svg?no-inline";
import logo118 from "../assets/provider-logos/poolside.svg?no-inline";
import logo119 from "../assets/provider-logos/privatemode-ai.svg?no-inline";
import logo120 from "../assets/provider-logos/qihang-ai.svg?no-inline";
import logo121 from "../assets/provider-logos/qiniu-ai.svg?no-inline";
import logo122 from "../assets/provider-logos/regolo-ai.svg?no-inline";
import logo123 from "../assets/provider-logos/requesty.svg?no-inline";
import logo124 from "../assets/provider-logos/routing-run.svg?no-inline";
import logo125 from "../assets/provider-logos/sakana.svg?no-inline";
import logo126 from "../assets/provider-logos/sap-ai-core.svg?no-inline";
import logo127 from "../assets/provider-logos/sarvam.svg?no-inline";
import logo128 from "../assets/provider-logos/scaleway.svg?no-inline";
import logo129 from "../assets/provider-logos/siliconflow.svg?no-inline";
import logo130 from "../assets/provider-logos/siliconflow-cn.svg?no-inline";
import logo131 from "../assets/provider-logos/snowflake-cortex.svg?no-inline";
import logo132 from "../assets/provider-logos/stackit.svg?no-inline";
import logo133 from "../assets/provider-logos/stepfun.svg?no-inline";
import logo134 from "../assets/provider-logos/stepfun-ai.svg?no-inline";
import logo135 from "../assets/provider-logos/stepfun-ai-step-plan.svg?no-inline";
import logo136 from "../assets/provider-logos/stepfun-step-plan.svg?no-inline";
import logo137 from "../assets/provider-logos/subconscious.svg?no-inline";
import logo138 from "../assets/provider-logos/submodel.svg?no-inline";
import logo139 from "../assets/provider-logos/synthetic.svg?no-inline";
import logo140 from "../assets/provider-logos/tencent-coding-plan.svg?no-inline";
import logo141 from "../assets/provider-logos/tencent-token-plan.svg?no-inline";
import logo142 from "../assets/provider-logos/tencent-tokenhub.svg?no-inline";
import logo143 from "../assets/provider-logos/the-grid-ai.svg?no-inline";
import logo144 from "../assets/provider-logos/thinkingmachines.svg?no-inline";
import logo145 from "../assets/provider-logos/tinfoil.svg?no-inline";
import logo146 from "../assets/provider-logos/togetherai.svg?no-inline";
import logo147 from "../assets/provider-logos/trustedrouter.svg?no-inline";
import logo148 from "../assets/provider-logos/umans-ai.svg?no-inline";
import logo149 from "../assets/provider-logos/umans-ai-coding-plan.svg?no-inline";
import logo150 from "../assets/provider-logos/unorouter.svg?no-inline";
import logo151 from "../assets/provider-logos/upstage.svg?no-inline";
import logo152 from "../assets/provider-logos/v0.svg?no-inline";
import logo153 from "../assets/provider-logos/venice.svg?no-inline";
import logo154 from "../assets/provider-logos/vercel.svg?no-inline";
import logo155 from "../assets/provider-logos/vivgrid.svg?no-inline";
import logo156 from "../assets/provider-logos/vultr.svg?no-inline";
import logo157 from "../assets/provider-logos/wafer.ai.svg?no-inline";
import logo158 from "../assets/provider-logos/wandb.svg?no-inline";
import logo159 from "../assets/provider-logos/xai.svg?no-inline";
import logo160 from "../assets/provider-logos/xiaomi.svg?no-inline";
import logo161 from "../assets/provider-logos/xiaomi-token-plan-ams.svg?no-inline";
import logo162 from "../assets/provider-logos/xiaomi-token-plan-cn.svg?no-inline";
import logo163 from "../assets/provider-logos/xiaomi-token-plan-sgp.svg?no-inline";
import logo164 from "../assets/provider-logos/xpersona.svg?no-inline";
import logo165 from "../assets/provider-logos/zai.svg?no-inline";
import logo166 from "../assets/provider-logos/zai-coding-plan.svg?no-inline";
import logo167 from "../assets/provider-logos/zeldoc.svg?no-inline";
import logo168 from "../assets/provider-logos/zenifra.svg?no-inline";
import logo169 from "../assets/provider-logos/zenmux.svg?no-inline";
import logo170 from "../assets/provider-logos/zhipuai.svg?no-inline";
import logo171 from "../assets/provider-logos/zhipuai-coding-plan.svg?no-inline";

export const PROVIDER_LOGO_URLS: Readonly<Record<string, string>> = {
  "302ai": logo0,
  "abacus": logo1,
  "abliteration-ai": logo2,
  "ai-router": logo3,
  "aiand": logo4,
  "aihubmix": logo5,
  "aki-io": logo6,
  "alibaba": logo7,
  "alibaba-cn": logo8,
  "alibaba-coding-plan": logo9,
  "alibaba-coding-plan-cn": logo10,
  "alibaba-token-plan": logo11,
  "alibaba-token-plan-cn": logo12,
  "amazon-bedrock": logo13,
  "ambient": logo14,
  "anthropic": logo15,
  "anyapi": logo16,
  "atomic-chat": logo17,
  "auriko": logo18,
  "azure": logo19,
  "azure-cognitive-services": logo20,
  "bailing": logo21,
  "baseten": logo22,
  "berget": logo23,
  "blueclaw": logo24,
  "cerebras": logo25,
  "chutes": logo26,
  "clarifai": logo27,
  "claudinio": logo28,
  "cline-pass": logo29,
  "cloudferro-sherlock": logo30,
  "cloudflare-ai-gateway": logo31,
  "cloudflare-workers-ai": logo32,
  "cohere": logo33,
  "cortecs": logo34,
  "crof": logo35,
  "crossmodel": logo36,
  "daoxe": logo37,
  "databricks": logo38,
  "deepinfra": logo39,
  "deepseek": logo40,
  "digitalocean": logo41,
  "dinference": logo42,
  "drun": logo43,
  "ebcloud": logo44,
  "empiriolabs": logo45,
  "evroc": logo46,
  "fastrouter": logo47,
  "fireworks-ai": logo48,
  "freemodel": logo49,
  "friendli": logo50,
  "frogbot": logo51,
  "github-copilot": logo52,
  "github-models": logo53,
  "gitlab": logo54,
  "gmicloud": logo55,
  "google": logo56,
  "google-vertex": logo57,
  "google-vertex-anthropic": logo58,
  "groq": logo59,
  "helicone": logo60,
  "hetzner": logo61,
  "hpc-ai": logo62,
  "huggingface": logo63,
  "iflowcn": logo64,
  "inception": logo65,
  "inceptron": logo66,
  "inference": logo67,
  "inferx": logo68,
  "io-net": logo69,
  "jiekou": logo70,
  "kenari": logo71,
  "kilo": logo72,
  "kimi-for-coding": logo73,
  "kuae-cloud-coding-plan": logo74,
  "lilac": logo75,
  "llama": logo76,
  "llmgateway": logo77,
  "llmtr": logo78,
  "lmstudio": logo79,
  "longcat": logo80,
  "lucidquery": logo81,
  "lynkr": logo82,
  "meganova": logo83,
  "merge-gateway": logo84,
  "meta": logo85,
  "minimax": logo86,
  "minimax-cn": logo87,
  "minimax-cn-coding-plan": logo88,
  "minimax-coding-plan": logo89,
  "mistral": logo90,
  "mixlayer": logo91,
  "moark": logo92,
  "model-oracle-ai": logo93,
  "modelscope": logo94,
  "moonshotai": logo95,
  "moonshotai-cn": logo96,
  "morph": logo97,
  "nano-gpt": logo98,
  "nearai": logo99,
  "nebius": logo100,
  "neon": logo101,
  "neuralwatt": logo102,
  "nova": logo103,
  "novita-ai": logo104,
  "nvidia": logo105,
  "ofox": logo106,
  "ollama-cloud": logo107,
  "openai": logo108,
  "opencode": logo109,
  "opencode-go": logo110,
  "openrouter": logo111,
  "orcarouter": logo112,
  "ovhcloud": logo113,
  "perplexity": logo114,
  "perplexity-agent": logo115,
  "pioneer": logo116,
  "poe": logo117,
  "poolside": logo118,
  "privatemode-ai": logo119,
  "qihang-ai": logo120,
  "qiniu-ai": logo121,
  "regolo-ai": logo122,
  "requesty": logo123,
  "routing-run": logo124,
  "sakana": logo125,
  "sap-ai-core": logo126,
  "sarvam": logo127,
  "scaleway": logo128,
  "siliconflow": logo129,
  "siliconflow-cn": logo130,
  "snowflake-cortex": logo131,
  "stackit": logo132,
  "stepfun": logo133,
  "stepfun-ai": logo134,
  "stepfun-ai-step-plan": logo135,
  "stepfun-step-plan": logo136,
  "subconscious": logo137,
  "submodel": logo138,
  "synthetic": logo139,
  "tencent-coding-plan": logo140,
  "tencent-token-plan": logo141,
  "tencent-tokenhub": logo142,
  "the-grid-ai": logo143,
  "thinkingmachines": logo144,
  "tinfoil": logo145,
  "togetherai": logo146,
  "trustedrouter": logo147,
  "umans-ai": logo148,
  "umans-ai-coding-plan": logo149,
  "unorouter": logo150,
  "upstage": logo151,
  "v0": logo152,
  "venice": logo153,
  "vercel": logo154,
  "vivgrid": logo155,
  "vultr": logo156,
  "wafer.ai": logo157,
  "wandb": logo158,
  "xai": logo159,
  "xiaomi": logo160,
  "xiaomi-token-plan-ams": logo161,
  "xiaomi-token-plan-cn": logo162,
  "xiaomi-token-plan-sgp": logo163,
  "xpersona": logo164,
  "zai": logo165,
  "zai-coding-plan": logo166,
  "zeldoc": logo167,
  "zenifra": logo168,
  "zenmux": logo169,
  "zhipuai": logo170,
  "zhipuai-coding-plan": logo171,
};
