import type { AgentReadinessState } from "@anyharness/sdk";

export const AGENTS_PAGE_COPY = {
  title: "Agents",
  description: "Install and manage agent runtimes and authentication.",
  runtimeSectionTitle: "Runtime",
  runtimeSectionDescription: "Local AnyHarness connection and agent reconciliation.",
  runtimeStatusLabel: "AnyHarness runtime",
  runtimeConnectedLabel: "Connected",
  runtimeConnectedDescription: "Connected to the local AnyHarness runtime.",
  runtimeConnectingLabel: "Connecting",
  runtimeUnavailableLabel: "Unavailable",
  runtimeVersionPrefix: "Runtime v",
  reconnectTitle: "Could not connect to the AnyHarness runtime.",
  reconnectLoadingMessage: "Starting runtime",
  reconnectLoadingSubtext: "Connecting to AnyHarness...",
  loadingMessage: "Loading agents",
  loadingSubtext: "Fetching available agent runtimes...",
  loadErrorTitle: "Could not load agent state.",
  empty: "No agents available",
  needsSetupSectionTitle: "Needs setup",
  needsSetupSectionDescription: "Agents that need installation, credentials, or login before they can run.",
  configuredSectionTitle: "Configured",
  configuredSectionDescription: "Agents ready to use in new sessions.",
  unavailableSectionTitle: "Unavailable",
  unavailableSectionDescription: "Agents blocked by runtime compatibility or setup failures.",
  reconcileLabel: "Agent reconciliation",
  reconcileDescription: "Reinstall the available runtimes and refresh their setup state.",
  reconcileAction: "Reinstall All",
  reconcileLoadingAction: "Installing...",
  reconcileSeedHydratingAction: "Finishing setup...",
  reconcileError: "Could not reinstall the available agents.",
  setupAction: "Setup",
  manageAction: "Manage",
  detailsAction: "Details",
} as const;

export const AGENT_SETUP_COPY = {
  docs: "Docs",
  install: "Install",
  retryInstall: "Retry Install",
  installFailed: "Install failed",
  justInstalled: "Just installed",
  installing: "Installing...",
  seedHydrating: "Finishing setup...",
  apiKeys: "API Keys",
  cliLogin: "CLI Login",
  saveCredential: "Save",
  savedInKeychain: "Saved in Keychain",
  changeSavedCredential: "Change",
  loginAction: "Get login command",
  refreshLoginAction: "Refresh login command",
  noCredentials: "This agent has no configurable credentials.",
  savedChangesNotice: "Saved credentials will apply after the runtime restarts.",
  applyAndRestart: "Apply & Restart Runtime",
  applying: "Applying...",
  done: "Done",
  close: "Close",
  credentialPlaceholder: "Paste API key",
  subtitles: {
    ready: "Update authentication credentials",
    unsupported: "Runtime compatibility issue",
    retryInstall: "Retry installation",
    install: "Install and configure",
    credentials: "Configure credentials",
  },
} as const;

export const AGENT_READINESS_LABELS: Record<AgentReadinessState, string> = {
  ready: "Configured",
  install_required: "Install required",
  credentials_required: "Credentials required",
  login_required: "Login required",
  unsupported: "Unsupported",
  error: "Unavailable",
};
