export const HOME_SCREEN_LABELS = {
  eyebrow: "Workspace hub",
  title: "Pick up where you left off",
  subtitle:
    "Open a repository, resume recent work, or finish setup before starting a fresh session.",
  localLabel: "local",
  cloudLabel: "cloud",
  supportPrefix: "Need help?",
  supportAction: "Let us know",
  agentsConfiguredSuffix: "configured.",
  agentsSetupPrefix: "Finish",
  agentsSetupSuffix: "setup in",
  agentsAction: "Agents",
  addRepositoryTitle: "Add repository",
  addRepositoryDescription: "Choose a Git repository from disk and configure it for future sessions.",
  resumeWorkspaceTitle: "Resume last workspace",
  resumeWorkspaceDescriptionPrefix: "Return to",
  addAnotherTitle: "Add another repository",
  addAnotherDescription: "Choose a different Git repository and configure it before starting a workspace.",
  agentSettingsTitle: "Finish agent setup",
  agentSettingsDescription: "Configure at least one harness before starting a new chat.",
  manageAgentsTitle: "Manage agents",
  manageAgentsDescription: "Review installed harnesses, credentials, and availability.",
  repositorySettingsTitle: "Repository settings",
  repositorySettingsDescription: "Review setup scripts, defaults, and repository-specific preferences.",
} as const;
