import type { ConnectorCatalogEntry } from "@/lib/domain/mcp/types";

export const CONNECTOR_CATALOG: readonly ConnectorCatalogEntry[] = [
  {
    id: "github",
    name: "GitHub",
    oneLiner: "Search repositories, issues, pull requests, and code on GitHub.",
    description:
      "Use GitHub to inspect repositories, review pull requests, follow issues, and pull in docs without leaving Proliferate.",
    docsUrl:
      "https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens",
    availability: "universal",
    cloudSecretSync: true,
    transport: "http",
    authKind: "secret",
    authStyle: { kind: "bearer" },
    authFieldId: "personal_access_token",
    url: "https://api.githubcopilot.com/mcp/",
    serverNameBase: "github",
    iconId: "github",
    requiredFields: [
      {
        id: "personal_access_token",
        label: "Personal access token",
        placeholder: "github_pat_...",
        helperText: "Use a fine-grained personal access token.",
        getTokenInstructions:
          "Open GitHub Settings, create a fine-grained personal access token, copy it, and paste it here. If you need organization or private-repo access, GitHub may require extra approval.",
        prefixHint: "github_pat_",
      },
    ],
    capabilities: [
      "Search code across repositories you can access",
      "Read pull requests, reviews, and discussions",
      "Browse issues, labels, and milestones",
      "Pull in README and doc content from repos",
    ],
  },
  {
    id: "context7",
    name: "Context7",
    oneLiner: "Pull current library docs into every session.",
    description:
      "Use Context7 when Proliferate needs current, version-specific documentation and code examples for the libraries in your project.",
    docsUrl: "https://context7.com/docs/howto/api-keys",
    availability: "universal",
    cloudSecretSync: true,
    transport: "http",
    authKind: "secret",
    authStyle: { kind: "bearer" },
    authFieldId: "api_key",
    url: "https://mcp.context7.com/mcp",
    serverNameBase: "context7",
    iconId: "context7",
    requiredFields: [
      {
        id: "api_key",
        label: "API key",
        placeholder: "ctx7sk-...",
        helperText: "Create a key in your Context7 dashboard.",
        getTokenInstructions:
          "Open the Context7 dashboard, click Create API Key, give it a name like “Proliferate”, copy the key immediately, and paste it here.",
        prefixHint: "ctx7sk-",
      },
    ],
    capabilities: [
      "Look up current, version-specific library docs",
      "Pull example snippets from official sources",
      "Resolve ambiguous API usage with live references",
    ],
  },
  {
    id: "brave_search",
    name: "Brave Search",
    oneLiner: "Search the web with Brave's independent index.",
    description:
      "Use Brave Search for current web results, news, and general lookups without routing through a browser.",
    docsUrl:
      "https://api-dashboard.search.brave.com/documentation/guides/authentication",
    availability: "universal",
    cloudSecretSync: true,
    transport: "http",
    authKind: "secret",
    authStyle: { kind: "header", headerName: "X-Subscription-Token" },
    authFieldId: "api_key",
    url: "",
    serverNameBase: "brave_search",
    iconId: "brave",
    requiredFields: [
      {
        id: "api_key",
        label: "API key",
        placeholder: "Paste your Brave Search API key",
        helperText: "Create a key in your Brave Search API dashboard.",
        getTokenInstructions:
          "Choose a Brave Search API plan, open the API Keys section in your dashboard, create a key, then paste it here.",
      },
    ],
    capabilities: [
      "Search the open web with Brave's independent index",
      "Pull news and recent articles",
      "Look up unfamiliar terms and references",
    ],
  },
  {
    id: "tavily",
    name: "Tavily",
    oneLiner: "Search, extract, and research the web.",
    description:
      "Use Tavily when Proliferate needs web search plus extraction and crawl tools for deeper research tasks.",
    docsUrl: "https://docs.tavily.com/guides/quickstart",
    availability: "universal",
    cloudSecretSync: true,
    transport: "http",
    authKind: "secret",
    authStyle: { kind: "bearer" },
    authFieldId: "api_key",
    url: "https://mcp.tavily.com/mcp",
    serverNameBase: "tavily",
    iconId: "globe",
    requiredFields: [
      {
        id: "api_key",
        label: "API key",
        placeholder: "tvly-...",
        helperText: "Get a free key from Tavily.",
        getTokenInstructions:
          "Open the Tavily dashboard, copy one of your API keys, and paste it here.",
        prefixHint: "tvly-",
      },
    ],
    capabilities: [
      "Run focused web searches",
      "Extract clean text from pages",
      "Crawl linked pages for deeper research",
    ],
  },
  {
    id: "openweather",
    name: "OpenWeather",
    oneLiner: "Fetch current weather and forecasts anywhere.",
    description:
      "Use OpenWeather for live conditions, short-term forecasts, and weather lookups without leaving the session.",
    docsUrl: "https://openweathermap.org/appid",
    availability: "universal",
    cloudSecretSync: true,
    transport: "http",
    authKind: "secret",
    authStyle: { kind: "query", parameterName: "appid" },
    authFieldId: "api_key",
    url: "",
    serverNameBase: "openweather",
    iconId: "openweather",
    requiredFields: [
      {
        id: "api_key",
        label: "API key",
        placeholder: "Paste your OpenWeather API key",
        helperText: "Create an API key in your OpenWeather account.",
        getTokenInstructions:
          "Sign up for OpenWeather, find your API key on the API key tab of your account page, then paste it here.",
      },
    ],
    capabilities: [
      "Look up current weather conditions anywhere",
      "Pull short-term forecasts",
      "Check wind, humidity, and pressure for a location",
    ],
  },
  {
    id: "linear",
    name: "Linear",
    oneLiner: "Search issues, projects, and teams in Linear.",
    description:
      "Use Linear to inspect issues, projects, cycles, and team state through the hosted remote MCP server.",
    docsUrl: "https://linear.app/docs/mcp",
    availability: "universal",
    cloudSecretSync: false,
    transport: "http",
    authKind: "oauth",
    url: "https://mcp.linear.app/mcp",
    serverNameBase: "linear",
    iconId: "globe",
    requiredFields: [],
    capabilities: [
      "Search issues, projects, and cycles",
      "Inspect team workloads and states",
      "Follow up on ticket status and ownership",
    ],
  },
  {
    id: "supabase",
    name: "Supabase",
    oneLiner: "Inspect and manage a single Supabase project.",
    description:
      "Use Supabase to inspect schema, SQL, storage, and project configuration for one project at a time. Start in read-only mode unless you explicitly need write access.",
    docsUrl: "https://supabase.com/docs/guides/getting-started/mcp",
    availability: "universal",
    cloudSecretSync: false,
    transport: "http",
    authKind: "oauth",
    url: "https://mcp.supabase.com/mcp",
    serverNameBase: "supabase",
    iconId: "supabase",
    requiredFields: [],
    capabilities: [
      "Inspect schema, tables, and views",
      "Run SQL against a selected project",
      "Browse storage buckets and project config",
      "Start read-only until you explicitly open write access",
    ],
  },
  {
    id: "notion",
    name: "Notion",
    oneLiner: "Read and update selected pages and databases in Notion.",
    description:
      "Use Notion to search and work with the pages and databases you authorize during the browser consent flow.",
    docsUrl: "https://developers.notion.com/guides/mcp/get-started-with-mcp",
    availability: "universal",
    cloudSecretSync: false,
    transport: "http",
    authKind: "oauth",
    url: "https://mcp.notion.com/mcp",
    serverNameBase: "notion",
    iconId: "notion",
    requiredFields: [],
    capabilities: [
      "Search authorized pages and databases",
      "Read and update selected records",
      "Navigate the workspaces you grant access to",
    ],
  },
  {
    id: "filesystem",
    name: "Filesystem",
    oneLiner: "Read and write files inside the current workspace.",
    description:
      "Use the Filesystem server when Proliferate should inspect or edit files directly through MCP against the active workspace path.",
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    availability: "local_only",
    cloudSecretSync: false,
    transport: "stdio",
    command: "mcp-server-filesystem",
    args: [{ source: { kind: "workspace_path" } }],
    env: [],
    serverNameBase: "filesystem",
    iconId: "folder",
    requiredFields: [],
    capabilities: [
      "Read files inside the active workspace",
      "Create new files in the workspace",
      "Make targeted edits without leaving the session",
    ],
  },
  {
    id: "playwright",
    name: "Playwright",
    oneLiner: "Drive and inspect the browser with Playwright tools.",
    description:
      "Use Playwright when Proliferate needs browser automation, DOM inspection, and page interaction over MCP.",
    docsUrl: "https://github.com/microsoft/playwright-mcp",
    availability: "local_only",
    cloudSecretSync: false,
    transport: "stdio",
    command: "playwright-mcp",
    args: [],
    env: [],
    serverNameBase: "playwright",
    iconId: "playwright",
    requiredFields: [],
    capabilities: [
      "Launch a headless browser session",
      "Click, type, and navigate pages",
      "Capture DOM state and page snapshots",
    ],
  },
] as const;
