export const WORKSPACE_ARRIVAL_LABELS = {
  newWorktreeBadge: "New worktree",
  worktreeBadge: "Worktree",
  newWorkspaceBadge: "New workspace",
  newCloudWorkspaceBadge: "Cloud workspace",
  workspaceBadge: "Workspace",
  worktreeCreatedEyebrow: "Ready to open",
  workspaceCreatedEyebrow: "Ready to start",
  cloudWorkspaceCreatedEyebrow: "Ready in cloud",
  worktreeCreatedSubtitlePrefix: "Created in",
  worktreeCreatedSubtitleFromInfix: "from",
  createdWorkspaceSubtitle: "Created locally and ready for chat",
  createdCloudWorkspaceSubtitle: "Provisioned in the cloud and ready for chat",
  repoLabel: "Repository",
  worktreeBranchLabel: "Worktree branch",
  basedOn: "Based on",
  locationLabel: "Location",
  openButtonPrefix: "Open in",
  openFallbackAction: "Open folder",
  setupTitle: "Repository setup",
  setupMissing: "No setup script configured yet",
  setupConfigured: "Setup script configured",
  setupRunning: "Setup script running...",
  setupQueued: "Setup script queued...",
  setupSucceeded: "Setup completed successfully",
  setupFailed: "Setup failed",
  setupStatusReady: "Ready",
  setupStatusRunning: "Running",
  setupStatusQueued: "Queued",
  setupStatusConfigured: "Configured",
  setupStatusOptional: "Optional",
  rerunSetup: "Rerun setup",
  addSetup: "Add setup script",
  seeTerminal: "See terminal",
  repositorySettings: "Repository settings",
  dismiss: "Dismiss",
  noWorkspaceTitle: "Select a workspace",
  noWorkspaceBody: "Choose a workspace from the sidebar to start chatting.",
} as const;
