export const AGENTS_PAGE_COPY = {
  title: "Agents",
  description: "Install and manage coding agents and authentication.",
  reconnectTitle: "Could not connect to the local agent service.",
  reconnectLoadingMessage: "Loading agents",
  reconnectLoadingSubtext: "Connecting to the local agent service...",
  loadingMessage: "Loading agents",
  loadingSubtext: "Fetching available agents...",
  connectionUnavailableTitle: "Agents unavailable",
  loadErrorTitle: "Could not load agent state.",
  empty: "No agents available",
  needsSetupSectionTitle: "Needs setup",
  needsSetupSectionDescription: "Agents that need installation, credentials, or login before they can run.",
  configuredSectionTitle: "Configured",
  configuredSectionDescription: "Agents ready to use in new sessions.",
  unavailableSectionTitle: "Unavailable",
  unavailableSectionDescription: "Agents blocked by runtime compatibility or setup failures.",
  defaultsSectionTitle: "Agent defaults",
  defaultsSectionDescription: "Choose launch defaults after agents are installed and configured.",
  defaultsLabel: "Launch defaults",
  defaultsDescription: "Set default harnesses, models, permissions, and live controls for new sessions.",
  defaultsAction: "Open Agent Defaults",
  reconcileSectionTitle: "Agent reconciliation",
  reconcileSectionDescription: "Repair agent setup if installed agents look stale or broken.",
  reconcileLabel: "Repair setup",
  reconcileDescription: "Reinstall available agents and refresh their setup state.",
  reconcileAction: "Reinstall agents",
  reconcileLoadingAction: "Installing...",
  reconcileSeedHydratingAction: "Finishing setup...",
  reconcileError: "Could not reinstall the available agents.",
  installAction: "Install",
  retryInstallAction: "Retry Install",
  reinstallAction: "Reinstall",
  installLoadingAction: "Installing...",
  setupAction: "Setup",
  manageAction: "Manage",
  detailsAction: "Details",
} as const;

export const AGENT_SETUP_COPY = {
  docs: "Docs",
  install: "Install",
  retryInstall: "Retry Install",
  installFailed: "Install failed",
  justInstalled: "Just installed",
  installing: "Installing...",
  seedHydrating: "Finishing setup...",
  apiKeys: "API Keys",
  cliLogin: "CLI Login",
  saveCredential: "Save",
  savedInKeychain: "Saved in Keychain",
  changeSavedCredential: "Change",
  loginAction: "Get login command",
  refreshLoginAction: "Refresh login command",
  noCredentials: "This agent has no configurable credentials.",
  savedChangesNotice: "Saved credentials will apply after the runtime restarts.",
  applyAndRestart: "Apply & Restart Runtime",
  applying: "Applying...",
  done: "Done",
  close: "Close",
  credentialPlaceholder: "Paste API key",
  subtitles: {
    ready: "Update authentication credentials",
    unsupported: "Runtime compatibility issue",
    retryInstall: "Retry installation",
    install: "Install and configure",
    credentials: "Configure credentials",
  },
} as const;
