use utoipa::OpenApi;

use anyharness_contract::v1::{
    AdvanceReplaySessionResponse, AgentCredentialState, AgentInstallState, AgentReadinessState,
    AgentSeedFailureKind, AgentSeedHealth, AgentSeedLastAction, AgentSeedOwnership,
    AgentSeedSource, AgentSeedStatus, AgentSummary, ArtifactStatus, AvailableCommandsUpdatePayload,
    ChildSubagentSummary, CommitRequest, CommitResponse, ConfigApplyState,
    ConfigOptionUpdatePayload, ContentPart, CoworkArtifactDetailResponse,
    CoworkArtifactManifestResponse, CoworkArtifactSummary, CoworkArtifactType,
    CoworkCodingSessionSummary, CoworkManagedWorkspaceSummary, CoworkManagedWorkspacesResponse,
    CoworkRoot, CoworkStatus, CoworkThread, CreateCoworkThreadRequest, CreateCoworkThreadResponse,
    CreatePullRequestRequest, CreatePullRequestResponse, CreateReplaySessionRequest,
    CreateReplaySessionResponse, CreateSessionRequest, CreateTerminalRequest,
    CreateWorkspaceRequest, CreateWorktreeWorkspaceRequest, CreateWorktreeWorkspaceResponse,
    CurrentModeUpdatePayload, CurrentPullRequestResponse, DestroyWorkspaceMobilitySourceRequest,
    DestroyWorkspaceMobilitySourceResponse, DetectProjectSetupResponse, EditPendingPromptRequest,
    ErrorEvent, ErrorEventDetails, ExportReplayRecordingRequest, ExportReplayRecordingResponse,
    ExportWorkspaceMobilityArchiveRequest, FileChangeOperation, FileOpenTarget, FileReadScope,
    GetSessionLiveConfigResponse, GetSetupStatusResponse, GitActionAvailability, GitBranchRef,
    GitChangedFile, GitDiffResponse, GitFileStatus, GitIncludedState, GitOperation,
    GitStatusSnapshot, GitStatusSummary, HandoffPlanRequest, HandoffPlanResponse, HealthResponse,
    InstallAgentRequest, InstallAgentResponse, InstallWorkspaceMobilityArchiveRequest,
    InstallWorkspaceMobilityArchiveResponse, InteractionDecision, InteractionKind,
    InteractionOutcome, InteractionPayload, InteractionRequestedEvent, InteractionResolvedEvent,
    InteractionSource, ItemCompletedEvent, ItemDeltaEvent, ItemStartedEvent,
    ListProposedPlansResponse, ListReplayRecordingsResponse, LoginCommand,
    MarkReviewRevisionReadyRequest, McpElicitationBooleanField, McpElicitationField,
    McpElicitationFieldBase, McpElicitationFormPayload, McpElicitationInteractionPayload,
    McpElicitationMode, McpElicitationMultiSelectField, McpElicitationNumberField,
    McpElicitationOption, McpElicitationSelectField, McpElicitationSubmittedField,
    McpElicitationSubmittedValue, McpElicitationTextField, McpElicitationTextFormat,
    McpElicitationUrlPayload, McpElicitationUrlRevealResponse, MobilityPendingConfigChangeRecord,
    MobilityPendingPromptRecord, MobilitySessionEventRecord, MobilitySessionLinkCompletionRecord,
    MobilitySessionLinkRecord, MobilitySessionLinkWakeScheduleRecord,
    MobilitySessionLiveConfigSnapshotRecord, MobilitySessionRawNotificationRecord,
    MobilitySessionRecord, ModelCatalogStatus, ModelEntry, ModelLaunchRemediation,
    ModelLaunchRemediationKind, ModelRegistry, ModelRegistryModel, NormalizedSessionControl,
    NormalizedSessionControlValue, NormalizedSessionControls, OriginContext, OriginEntrypoint,
    OriginKind, ParentSubagentLinkSummary, PendingInteractionPayloadSummary,
    PendingInteractionSource, PendingInteractionSummary, PendingPromptAddedPayload,
    PendingPromptRemovalReason, PendingPromptRemovedPayload, PendingPromptSummary,
    PendingPromptUpdatedPayload, PermissionInteractionContext, PermissionInteractionOption,
    PermissionInteractionOptionKind, PermissionInteractionPayload, PlanDecisionRequest,
    PlanDecisionResponse, PlanEntry, PlanHandoffPromptStatus,
    PrepareRepoRootMobilityDestinationRequest, PrepareRepoRootMobilityDestinationResponse,
    ProblemDetails, PromptInputBlock, PromptProvenance, PromptSessionRequest,
    PromptSessionResponse, PromptSessionStatus, ProposedPlanDecisionState, ProposedPlanDetail,
    ProposedPlanDocumentResponse, ProposedPlanNativeResolutionState, ProposedPlanSummary,
    ProviderConfig, PullRequestState, PullRequestSummary, PushRequest, PushResponse,
    RawSessionConfigOption, RawSessionConfigValue, ReadWorkspaceFileResponse, ReasoningVisibility,
    ReconcileAgentResult, ReconcileAgentsRequest, ReconcileAgentsResponse, ReconcileJobStatus,
    ReconcileOutcome, ReplayRecordingSummary, RepoRoot, RepoRootKind, ResizeTerminalRequest,
    ResolveInteractionRequest, ResolveRepoRootFromPathRequest, ResolveWorkspaceFromPathRequest,
    ResolveWorkspaceResponse, ResumeSessionRequest, RetryReviewAssignmentRequest,
    ReviewAssignmentDetail, ReviewAssignmentStatus, ReviewCritiqueResponse,
    ReviewFeedbackDeliveryDetail, ReviewFeedbackDeliveryState, ReviewKind,
    ReviewModeVerificationStatus, ReviewPersonaRequest, ReviewRoundDetail, ReviewRoundStatus,
    ReviewRunDetail, ReviewRunResponse, ReviewRunStatus, ReviewRunUpdatedPayload,
    RunCommandRequest, RunCommandResponse, RuntimeCapabilities, Session, SessionEndReason,
    SessionEndedEvent, SessionEvent, SessionEventEnvelope, SessionExecutionPhase,
    SessionExecutionSummary, SessionInfoUpdatePayload, SessionLiveConfigSnapshot,
    SessionMcpBindingNotAppliedReason, SessionMcpBindingOutcome, SessionMcpBindingSummary,
    SessionMcpEnvVar, SessionMcpHeader, SessionMcpHttpServer, SessionMcpServer,
    SessionMcpStdioServer, SessionMcpTransport, SessionRawNotificationEnvelope,
    SessionReviewsResponse, SessionStartedEvent, SessionStateUpdatePayload, SessionStatus,
    SessionSubagentsResponse, SetSessionConfigOptionRequest, SetSessionConfigOptionResponse,
    SetupHint, SetupHintCategory, SetupScriptExecution, SetupScriptStatus, StagePathsRequest,
    StartAgentLoginRequest, StartAgentLoginResponse, StartCodeReviewRequest,
    StartPlanReviewRequest, StartWorkspaceSetupRequest, StopReason, SubagentCompletionSummary,
    SubagentTurnCompletedPayload, SubagentTurnOutcome, TerminalLifecycleEvent, TerminalPurpose,
    TerminalRecord, TerminalStatus, TranscriptItemDeltaPayload, TranscriptItemKind,
    TranscriptItemPayload, TranscriptItemStatus, TurnEndedEvent, TurnStartedEvent,
    UnstagePathsRequest, UpdateSessionTitleRequest, UpdateTerminalTitleRequest,
    UpdateWorkspaceDisplayNameRequest, UpdateWorkspaceMobilityRuntimeStateRequest,
    UsageUpdatePayload, UserInputInteractionPayload, UserInputQuestion, UserInputQuestionOption,
    UserInputSubmittedAnswer, Workspace, WorkspaceExecutionPhase, WorkspaceExecutionSummary,
    WorkspaceFileKind, WorkspaceKind, WorkspaceMobilityArchive, WorkspaceMobilityBlocker,
    WorkspaceMobilityFileEntry, WorkspaceMobilityPreflightResponse, WorkspaceMobilityRuntimeMode,
    WorkspaceMobilityRuntimeState, WorkspaceMobilitySessionBundle,
    WorkspaceMobilitySessionCandidate, WorkspaceSessionLaunchAgent, WorkspaceSessionLaunchCatalog,
    WorkspaceSessionLaunchModel, WorkspaceSurface,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "AnyHarness Runtime API",
        version = "0.1.0",
        description = "Local sidecar runtime for managing coding agent installations, credentials, and ACP sessions."
    ),
    paths(
        super::http::health::get_health,
        super::http::agents::list_agents,
        super::http::agents::get_agent,
        super::http::agents::install_agent,
        super::http::agents::start_agent_login,
        super::http::agents::get_reconcile_status,
        super::http::agents::reconcile_agents,
        super::http::model_registries::list_model_registries,
        super::http::model_registries::get_model_registry,
        super::http::provider_configs::list_provider_configs,
        super::http::git::get_git_status,
        super::http::git::get_git_diff,
        super::http::git::list_git_branches,
        super::http::git::stage_paths,
        super::http::git::unstage_paths,
        super::http::git::commit,
        super::http::git::push,
        super::http::hosting::get_current_pull_request,
        super::http::hosting::create_pull_request,
        super::http::processes::run_command,
        super::http::terminals::list_terminals,
        super::http::terminals::create_terminal,
        super::http::terminals::get_terminal,
        super::http::terminals::update_terminal_title,
        super::http::terminals::resize_terminal,
        super::http::terminals::delete_terminal,
        super::http::repo_roots::list_repo_roots,
        super::http::repo_roots::get_repo_root,
        super::http::repo_roots::resolve_repo_root,
        super::http::repo_roots::list_repo_root_git_branches,
        super::http::repo_roots::read_repo_root_file,
        super::http::repo_roots::detect_repo_root_setup,
        super::http::repo_roots::prepare_repo_root_mobility_destination,
        super::http::cowork::get_cowork_status,
        super::http::cowork::enable_cowork,
        super::http::cowork::list_cowork_threads,
        super::http::cowork::create_cowork_thread,
        super::http::cowork::get_cowork_managed_workspaces,
        super::http::cowork::get_cowork_manifest,
        super::http::cowork::get_cowork_artifact,
        super::http::workspaces::resolve_workspace,
        super::http::workspaces::create_workspace,
        super::http::workspaces::create_worktree,
        super::http::workspaces::list_workspaces,
        super::http::workspaces::get_workspace,
        super::http::workspaces::update_workspace_display_name,
        super::http::workspaces::get_workspace_session_launch_catalog,
        super::http::workspaces::detect_project_setup,
        super::http::workspaces::get_setup_status,
        super::http::workspaces::rerun_setup,
        super::http::workspaces::start_setup,
        super::http::mobility::preflight_workspace_mobility,
        super::http::mobility::update_workspace_mobility_runtime_state,
        super::http::mobility::export_workspace_mobility_archive,
        super::http::mobility::install_workspace_mobility_archive,
        super::http::mobility::destroy_workspace_mobility_source,
        super::http::sessions::create_session,
        super::http::sessions::update_session_title,
        super::http::sessions::get_live_session_config,
        super::http::sessions::set_session_config_option,
        super::http::sessions::prompt_session,
        super::http::sessions::edit_pending_prompt,
        super::http::sessions::delete_pending_prompt,
        super::http::sessions::get_prompt_attachment,
        super::http::sessions::resume_session,
        super::http::sessions::cancel_session,
        super::http::sessions::close_session,
        super::http::sessions::dismiss_session,
        super::http::sessions::restore_dismissed_session,
        super::http::sessions::list_sessions,
        super::http::sessions::get_session,
        super::http::subagents::get_session_subagents,
        super::http::sessions::list_session_events,
        super::http::sessions::list_session_raw_notifications,
        super::http::sessions::resolve_interaction,
        super::http::sessions::reveal_mcp_elicitation_url,
        super::http::replay::list_replay_recordings,
        super::http::replay::export_replay_recording,
        super::http::replay::create_replay_session,
        super::http::replay::advance_replay_session,
        super::http::plans::list_workspace_plans,
        super::http::plans::get_plan,
        super::http::plans::get_plan_document,
        super::http::plans::approve_plan,
        super::http::plans::reject_plan,
        super::http::plans::handoff_plan,
        super::http::reviews::start_plan_review,
        super::http::reviews::start_code_review,
        super::http::reviews::get_session_reviews,
        super::http::reviews::get_review_assignment_critique,
        super::http::reviews::retry_review_assignment,
        super::http::reviews::stop_review,
        super::http::reviews::send_review_feedback,
        super::http::reviews::mark_review_revision_ready,
    ),
    components(schemas(
        HealthResponse,
        RuntimeCapabilities,
        AgentSeedHealth,
        AgentSeedStatus,
        AgentSeedSource,
        AgentSeedOwnership,
        AgentSeedLastAction,
        AgentSeedFailureKind,
        AgentInstallState,
        AgentCredentialState,
        AgentReadinessState,
        ArtifactStatus,
        AgentSummary,
        InstallAgentRequest,
        InstallAgentResponse,
        LoginCommand,
        StartAgentLoginRequest,
        StartAgentLoginResponse,
        ProblemDetails,
        RepoRootKind,
        RepoRoot,
        ResolveRepoRootFromPathRequest,
        WorkspaceFileKind,
        ReadWorkspaceFileResponse,
        PrepareRepoRootMobilityDestinationRequest,
        PrepareRepoRootMobilityDestinationResponse,
        CoworkRoot,
        CoworkStatus,
        CoworkArtifactType,
        CoworkArtifactSummary,
        CoworkArtifactManifestResponse,
        CoworkArtifactDetailResponse,
        CoworkThread,
        CreateCoworkThreadRequest,
        CreateCoworkThreadResponse,
        CoworkManagedWorkspacesResponse,
        CoworkManagedWorkspaceSummary,
        CoworkCodingSessionSummary,
        OriginKind,
        OriginEntrypoint,
        OriginContext,
        WorkspaceKind,
        WorkspaceSurface,
        WorkspaceExecutionPhase,
        WorkspaceExecutionSummary,
        Workspace,
        ResolveWorkspaceFromPathRequest,
        ResolveWorkspaceResponse,
        CreateWorkspaceRequest,
        CreateWorktreeWorkspaceRequest,
        SetupScriptStatus,
        SetupScriptExecution,
        CreateWorktreeWorkspaceResponse,
        UpdateWorkspaceDisplayNameRequest,
        WorkspaceSessionLaunchModel,
        WorkspaceSessionLaunchAgent,
        WorkspaceSessionLaunchCatalog,
        SessionStatus,
        SessionExecutionPhase,
        PendingInteractionSummary,
        PendingInteractionSource,
        PendingInteractionPayloadSummary,
        SessionExecutionSummary,
        Session,
        SessionMcpEnvVar,
        SessionMcpHeader,
        SessionMcpHttpServer,
        SessionMcpStdioServer,
        SessionMcpServer,
        SessionMcpTransport,
        SessionMcpBindingOutcome,
        SessionMcpBindingNotAppliedReason,
        SessionMcpBindingSummary,
        SessionSubagentsResponse,
        ParentSubagentLinkSummary,
        ChildSubagentSummary,
        SubagentCompletionSummary,
        CreateSessionRequest,
        ResumeSessionRequest,
        UpdateSessionTitleRequest,
        PromptInputBlock,
        PromptSessionRequest,
        PromptSessionResponse,
        PromptSessionStatus,
        PendingPromptSummary,
        EditPendingPromptRequest,
        InteractionDecision,
        ResolveInteractionRequest,
        RawSessionConfigValue,
        anyharness_contract::v1::SessionConfigOptionType,
        RawSessionConfigOption,
        NormalizedSessionControlValue,
        NormalizedSessionControl,
        NormalizedSessionControls,
        SessionLiveConfigSnapshot,
        GetSessionLiveConfigResponse,
        SetSessionConfigOptionRequest,
        ConfigApplyState,
        SetSessionConfigOptionResponse,
        ReplayRecordingSummary,
        ListReplayRecordingsResponse,
        ExportReplayRecordingRequest,
        ExportReplayRecordingResponse,
        CreateReplaySessionRequest,
        CreateReplaySessionResponse,
        AdvanceReplaySessionResponse,
        SessionEventEnvelope,
        SessionRawNotificationEnvelope,
        SessionEvent,
        SessionStartedEvent,
        SessionEndedEvent,
        SessionEndReason,
        TurnStartedEvent,
        TurnEndedEvent,
        ItemStartedEvent,
        ItemDeltaEvent,
        ItemCompletedEvent,
        TranscriptItemPayload,
        PromptProvenance,
        TranscriptItemKind,
        TranscriptItemStatus,
        TranscriptItemDeltaPayload,
        ContentPart,
        ReasoningVisibility,
        TerminalLifecycleEvent,
        FileReadScope,
        FileOpenTarget,
        FileChangeOperation,
        PlanEntry,
        ProposedPlanDecisionState,
        ProposedPlanNativeResolutionState,
        ProposedPlanSummary,
        ProposedPlanDetail,
        ListProposedPlansResponse,
        ProposedPlanDocumentResponse,
        PlanDecisionRequest,
        PlanDecisionResponse,
        HandoffPlanRequest,
        PlanHandoffPromptStatus,
        HandoffPlanResponse,
        ReviewKind,
        ReviewRunStatus,
        ReviewRoundStatus,
        ReviewAssignmentStatus,
        ReviewFeedbackDeliveryState,
        ReviewModeVerificationStatus,
        ReviewPersonaRequest,
        StartPlanReviewRequest,
        StartCodeReviewRequest,
        MarkReviewRevisionReadyRequest,
        RetryReviewAssignmentRequest,
        ReviewAssignmentDetail,
        ReviewCritiqueResponse,
        ReviewFeedbackDeliveryDetail,
        ReviewRoundDetail,
        ReviewRunDetail,
        ReviewRunResponse,
        SessionReviewsResponse,
        AvailableCommandsUpdatePayload,
        CurrentModeUpdatePayload,
        ConfigOptionUpdatePayload,
        SessionStateUpdatePayload,
        SessionInfoUpdatePayload,
        SubagentTurnCompletedPayload,
        ReviewRunUpdatedPayload,
        SubagentTurnOutcome,
        UsageUpdatePayload,
        PendingPromptAddedPayload,
        PendingPromptUpdatedPayload,
        PendingPromptRemovedPayload,
        PendingPromptRemovalReason,
        InteractionRequestedEvent,
        InteractionResolvedEvent,
        InteractionKind,
        InteractionSource,
        InteractionPayload,
        InteractionOutcome,
        PermissionInteractionPayload,
        PermissionInteractionContext,
        PermissionInteractionOption,
        PermissionInteractionOptionKind,
        UserInputInteractionPayload,
        UserInputQuestion,
        UserInputQuestionOption,
        UserInputSubmittedAnswer,
        McpElicitationInteractionPayload,
        McpElicitationMode,
        McpElicitationFormPayload,
        McpElicitationUrlPayload,
        McpElicitationField,
        McpElicitationFieldBase,
        McpElicitationTextField,
        McpElicitationTextFormat,
        McpElicitationNumberField,
        McpElicitationBooleanField,
        McpElicitationSelectField,
        McpElicitationMultiSelectField,
        McpElicitationOption,
        McpElicitationSubmittedField,
        McpElicitationSubmittedValue,
        McpElicitationUrlRevealResponse,
        ErrorEvent,
        ErrorEventDetails,
        StopReason,
        ReconcileOutcome,
        ReconcileJobStatus,
        ReconcileAgentsRequest,
        ReconcileAgentResult,
        ReconcileAgentsResponse,
        ProviderConfig,
        ModelCatalogStatus,
        ModelEntry,
        ModelLaunchRemediation,
        ModelLaunchRemediationKind,
        ModelRegistry,
        ModelRegistryModel,
        GitStatusSnapshot,
        GitStatusSummary,
        GitActionAvailability,
        GitChangedFile,
        GitFileStatus,
        GitIncludedState,
        GitOperation,
        GitDiffResponse,
        GitBranchRef,
        StagePathsRequest,
        UnstagePathsRequest,
        CommitRequest,
        CommitResponse,
        PushRequest,
        PushResponse,
        CurrentPullRequestResponse,
        PullRequestSummary,
        PullRequestState,
        CreatePullRequestRequest,
        CreatePullRequestResponse,
        RunCommandRequest,
        RunCommandResponse,
        TerminalPurpose,
        TerminalStatus,
        TerminalRecord,
        CreateTerminalRequest,
        ResizeTerminalRequest,
        UpdateTerminalTitleRequest,
        DetectProjectSetupResponse,
        SetupHint,
        SetupHintCategory,
        GetSetupStatusResponse,
        StartWorkspaceSetupRequest,
        WorkspaceMobilityRuntimeMode,
        WorkspaceMobilityRuntimeState,
        UpdateWorkspaceMobilityRuntimeStateRequest,
        WorkspaceMobilityBlocker,
        WorkspaceMobilitySessionCandidate,
        WorkspaceMobilityPreflightResponse,
        ExportWorkspaceMobilityArchiveRequest,
        InstallWorkspaceMobilityArchiveRequest,
        InstallWorkspaceMobilityArchiveResponse,
        DestroyWorkspaceMobilitySourceRequest,
        DestroyWorkspaceMobilitySourceResponse,
        WorkspaceMobilityArchive,
        WorkspaceMobilityFileEntry,
        WorkspaceMobilitySessionBundle,
        MobilitySessionRecord,
        MobilitySessionLiveConfigSnapshotRecord,
        MobilityPendingConfigChangeRecord,
        MobilityPendingPromptRecord,
        MobilitySessionEventRecord,
        MobilitySessionLinkRecord,
        MobilitySessionLinkCompletionRecord,
        MobilitySessionLinkWakeScheduleRecord,
        MobilitySessionRawNotificationRecord,
    ))
)]
pub struct ApiDoc;

pub fn openapi_json() -> String {
    ApiDoc::openapi()
        .to_pretty_json()
        .expect("OpenAPI serialization should not fail")
}

#[cfg(test)]
mod tests {
    use serde_json::Value;

    use super::openapi_json;

    #[test]
    fn openapi_registers_workspace_and_session_paths() {
        let spec: Value = serde_json::from_str(&openapi_json()).expect("parse OpenAPI JSON");
        let paths = spec["paths"]
            .as_object()
            .expect("OpenAPI paths should be an object");

        for path in [
            "/v1/workspaces/resolve",
            "/v1/workspaces",
            "/v1/workspaces/worktrees",
            "/v1/workspaces/{workspace_id}",
            "/v1/workspaces/{workspace_id}/display-name",
            "/v1/workspaces/{workspace_id}/session-launch",
            "/v1/workspaces/{workspace_id}/detect-setup",
            "/v1/workspaces/{workspace_id}/setup-status",
            "/v1/workspaces/{workspace_id}/setup-rerun",
            "/v1/workspaces/{workspace_id}/setup-start",
            "/v1/sessions",
            "/v1/sessions/{session_id}",
            "/v1/sessions/{session_id}/title",
            "/v1/sessions/{session_id}/live-config",
            "/v1/sessions/{session_id}/config-options",
            "/v1/sessions/{session_id}/prompt",
            "/v1/sessions/{session_id}/resume",
            "/v1/sessions/{session_id}/cancel",
            "/v1/sessions/{session_id}/close",
            "/v1/sessions/{session_id}/dismiss",
            "/v1/sessions/{session_id}/subagents",
            "/v1/workspaces/{workspace_id}/sessions/restore",
            "/v1/sessions/{session_id}/events",
            "/v1/sessions/{session_id}/raw-notifications",
            "/v1/sessions/{session_id}/interactions/{request_id}/resolve",
            "/v1/sessions/{session_id}/interactions/{request_id}/mcp-url/reveal",
            "/v1/replay/recordings",
            "/v1/replay/sessions",
            "/v1/replay/sessions/{session_id}/advance",
            "/v1/repo-roots/{repo_root_id}/files/file",
            "/v1/workspaces/{workspace_id}/terminals",
            "/v1/terminals/{terminal_id}",
            "/v1/terminals/{terminal_id}/title",
            "/v1/terminals/{terminal_id}/resize",
        ] {
            assert!(paths.contains_key(path), "missing OpenAPI path: {path}");
        }
    }

    #[test]
    fn openapi_registers_workspace_session_and_event_schemas() {
        let spec: Value = serde_json::from_str(&openapi_json()).expect("parse OpenAPI JSON");
        let schemas = spec["components"]["schemas"]
            .as_object()
            .expect("OpenAPI schemas should be an object");

        for schema in [
            "OriginKind",
            "OriginEntrypoint",
            "OriginContext",
            "WorkspaceKind",
            "WorkspaceExecutionPhase",
            "WorkspaceExecutionSummary",
            "Workspace",
            "ResolveWorkspaceFromPathRequest",
            "CreateWorkspaceRequest",
            "CreateWorktreeWorkspaceRequest",
            "SetupScriptStatus",
            "SetupScriptExecution",
            "CreateWorktreeWorkspaceResponse",
            "SetupHintCategory",
            "SetupHint",
            "DetectProjectSetupResponse",
            "GetSetupStatusResponse",
            "StartWorkspaceSetupRequest",
            "UpdateWorkspaceDisplayNameRequest",
            "WorkspaceSessionLaunchModel",
            "WorkspaceSessionLaunchAgent",
            "WorkspaceSessionLaunchCatalog",
            "SessionStatus",
            "SessionExecutionPhase",
            "PendingInteractionSummary",
            "PendingInteractionSource",
            "PendingInteractionPayloadSummary",
            "SessionExecutionSummary",
            "Session",
            "SessionMcpEnvVar",
            "SessionMcpHeader",
            "SessionMcpHttpServer",
            "SessionMcpStdioServer",
            "SessionMcpServer",
            "SessionMcpTransport",
            "SessionMcpBindingOutcome",
            "SessionMcpBindingNotAppliedReason",
            "SessionMcpBindingSummary",
            "CreateSessionRequest",
            "ResumeSessionRequest",
            "UpdateSessionTitleRequest",
            "PromptInputBlock",
            "PromptSessionRequest",
            "PromptSessionResponse",
            "PromptSessionStatus",
            "PendingPromptSummary",
            "EditPendingPromptRequest",
            "InteractionDecision",
            "ResolveInteractionRequest",
            "RawSessionConfigValue",
            "SessionConfigOptionType",
            "RawSessionConfigOption",
            "NormalizedSessionControlValue",
            "NormalizedSessionControl",
            "NormalizedSessionControls",
            "SessionLiveConfigSnapshot",
            "GetSessionLiveConfigResponse",
            "SetSessionConfigOptionRequest",
            "ConfigApplyState",
            "SetSessionConfigOptionResponse",
            "ReplayRecordingSummary",
            "ListReplayRecordingsResponse",
            "ExportReplayRecordingRequest",
            "ExportReplayRecordingResponse",
            "CreateReplaySessionRequest",
            "CreateReplaySessionResponse",
            "AdvanceReplaySessionResponse",
            "SessionEventEnvelope",
            "SessionRawNotificationEnvelope",
            "SessionEvent",
            "SessionStartedEvent",
            "SessionEndedEvent",
            "SessionEndReason",
            "TurnStartedEvent",
            "TurnEndedEvent",
            "ItemStartedEvent",
            "ItemDeltaEvent",
            "ItemCompletedEvent",
            "TranscriptItemPayload",
            "TranscriptItemKind",
            "TranscriptItemStatus",
            "TranscriptItemDeltaPayload",
            "ContentPart",
            "ReasoningVisibility",
            "TerminalLifecycleEvent",
            "TerminalPurpose",
            "TerminalStatus",
            "TerminalRecord",
            "CreateTerminalRequest",
            "ResizeTerminalRequest",
            "UpdateTerminalTitleRequest",
            "FileReadScope",
            "FileOpenTarget",
            "FileChangeOperation",
            "PlanEntry",
            "AvailableCommandsUpdatePayload",
            "CurrentModeUpdatePayload",
            "ConfigOptionUpdatePayload",
            "SessionStateUpdatePayload",
            "SessionInfoUpdatePayload",
            "SubagentTurnCompletedPayload",
            "ReviewRunUpdatedPayload",
            "SubagentTurnOutcome",
            "UsageUpdatePayload",
            "PendingPromptAddedPayload",
            "PendingPromptUpdatedPayload",
            "PendingPromptRemovedPayload",
            "PendingPromptRemovalReason",
            "InteractionRequestedEvent",
            "InteractionResolvedEvent",
            "InteractionKind",
            "InteractionSource",
            "InteractionPayload",
            "InteractionOutcome",
            "PermissionInteractionPayload",
            "PermissionInteractionOption",
            "PermissionInteractionOptionKind",
            "UserInputInteractionPayload",
            "UserInputQuestion",
            "UserInputQuestionOption",
            "McpElicitationInteractionPayload",
            "McpElicitationMode",
            "McpElicitationFormPayload",
            "McpElicitationUrlPayload",
            "McpElicitationField",
            "McpElicitationFieldBase",
            "McpElicitationTextField",
            "McpElicitationTextFormat",
            "McpElicitationNumberField",
            "McpElicitationBooleanField",
            "McpElicitationSelectField",
            "McpElicitationMultiSelectField",
            "McpElicitationOption",
            "McpElicitationSubmittedField",
            "McpElicitationSubmittedValue",
            "McpElicitationUrlRevealResponse",
            "ErrorEvent",
            "StopReason",
            "RuntimeCapabilities",
            "AgentSeedHealth",
            "AgentSeedStatus",
            "WorkspaceFileKind",
            "ReadWorkspaceFileResponse",
        ] {
            assert!(
                schemas.contains_key(schema),
                "missing OpenAPI schema: {schema}"
            );
        }
    }
}
