use utoipa::OpenApi;

use anyharness_contract::v1::{
    AgentCredentialState, AgentInstallState, AgentReadinessState, AgentSummary, ArtifactStatus,
    AvailableCommandsUpdatePayload, CommitRequest, CommitResponse, ConfigApplyState,
    ConfigOptionUpdatePayload, ContentPart, CoworkArtifactDetailResponse,
    CoworkArtifactManifestResponse, CoworkArtifactSummary, CoworkArtifactType, CoworkRoot,
    CoworkStatus, CoworkThread, CreateCoworkThreadRequest, CreateCoworkThreadResponse,
    CreatePullRequestRequest, CreatePullRequestResponse, CreateSessionRequest,
    CreateWorkspaceRequest, CreateWorktreeWorkspaceRequest, CreateWorktreeWorkspaceResponse,
    CurrentModeUpdatePayload, CurrentPullRequestResponse, DestroyWorkspaceMobilitySourceRequest,
    DestroyWorkspaceMobilitySourceResponse, DetectProjectSetupResponse, EditPendingPromptRequest,
    ErrorEvent, ExportWorkspaceMobilityArchiveRequest, FileChangeOperation, FileOpenTarget,
    FileReadScope, GetSessionLiveConfigResponse, GetSetupStatusResponse, GitActionAvailability,
    GitBranchRef, GitChangedFile, GitDiffResponse, GitFileStatus, GitIncludedState, GitOperation,
    GitStatusSnapshot, GitStatusSummary, HealthResponse, InstallAgentRequest, InstallAgentResponse,
    InstallWorkspaceMobilityArchiveRequest, InstallWorkspaceMobilityArchiveResponse,
    ItemCompletedEvent, ItemDeltaEvent, ItemStartedEvent, LoginCommand,
    MobilityPendingConfigChangeRecord, MobilityPendingPromptRecord, MobilitySessionEventRecord,
    MobilitySessionLiveConfigSnapshotRecord, MobilitySessionRawNotificationRecord,
    MobilitySessionRecord, ModelEntry, ModelRegistry, ModelRegistryModel, NormalizedSessionControl,
    NormalizedSessionControlValue, NormalizedSessionControls, PendingApprovalSummary,
    PendingPromptAddedPayload, PendingPromptRemovalReason, PendingPromptRemovedPayload,
    PendingPromptSummary, PendingPromptUpdatedPayload, PermissionDecision, PermissionOutcome,
    PermissionRequestedEvent, PermissionResolvedEvent, PlanEntry,
    PrepareRepoRootMobilityDestinationRequest, PrepareRepoRootMobilityDestinationResponse,
    ProblemDetails, PromptInputBlock, PromptSessionRequest, PromptSessionResponse,
    PromptSessionStatus, ProviderConfig, PullRequestState, PullRequestSummary, PushRequest,
    PushResponse, RawSessionConfigOption, RawSessionConfigValue, ReasoningVisibility,
    ReconcileAgentResult, ReconcileAgentsRequest, ReconcileAgentsResponse, ReconcileJobStatus,
    ReconcileOutcome, RepoRoot, RepoRootKind, ResolvePermissionRequest,
    ResolveRepoRootFromPathRequest, ResolveWorkspaceFromPathRequest, ResolveWorkspaceResponse,
    RunCommandRequest, RunCommandResponse, Session, SessionEndReason, SessionEndedEvent,
    SessionEvent, SessionEventEnvelope, SessionExecutionPhase, SessionExecutionSummary,
    SessionInfoUpdatePayload, SessionLiveConfigSnapshot, SessionMcpEnvVar, SessionMcpHeader,
    SessionMcpHttpServer, SessionMcpServer, SessionMcpStdioServer, SessionRawNotificationEnvelope,
    SessionStartedEvent, SessionStateUpdatePayload, SessionStatus, SetSessionConfigOptionRequest,
    SetSessionConfigOptionResponse, SetupHint, SetupHintCategory, SetupScriptExecution,
    SetupScriptStatus, StagePathsRequest, StartAgentLoginRequest, StartAgentLoginResponse,
    StartWorkspaceSetupRequest, StopReason, TerminalLifecycleEvent, TranscriptItemDeltaPayload,
    TranscriptItemKind, TranscriptItemPayload, TranscriptItemStatus, TurnEndedEvent,
    TurnStartedEvent, UnstagePathsRequest, UpdateSessionTitleRequest,
    UpdateWorkspaceDisplayNameRequest, UpdateWorkspaceMobilityRuntimeStateRequest,
    UsageUpdatePayload, Workspace, WorkspaceExecutionPhase, WorkspaceExecutionSummary,
    WorkspaceKind, WorkspaceMobilityArchive, WorkspaceMobilityBlocker, WorkspaceMobilityFileEntry,
    WorkspaceMobilityPreflightResponse, WorkspaceMobilityRuntimeMode,
    WorkspaceMobilityRuntimeState, WorkspaceMobilitySessionBundle,
    WorkspaceMobilitySessionCandidate, WorkspaceSessionLaunchAgent, WorkspaceSessionLaunchCatalog,
    WorkspaceSessionLaunchModel, WorkspaceSurface,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "AnyHarness Runtime API",
        version = "0.1.0",
        description = "Local sidecar runtime for managing coding agent installations, credentials, and ACP sessions."
    ),
    paths(
        super::http::health::get_health,
        super::http::agents::list_agents,
        super::http::agents::get_agent,
        super::http::agents::install_agent,
        super::http::agents::start_agent_login,
        super::http::agents::get_reconcile_status,
        super::http::agents::reconcile_agents,
        super::http::model_registries::list_model_registries,
        super::http::model_registries::get_model_registry,
        super::http::provider_configs::list_provider_configs,
        super::http::git::get_git_status,
        super::http::git::get_git_diff,
        super::http::git::list_git_branches,
        super::http::git::stage_paths,
        super::http::git::unstage_paths,
        super::http::git::commit,
        super::http::git::push,
        super::http::hosting::get_current_pull_request,
        super::http::hosting::create_pull_request,
        super::http::processes::run_command,
        super::http::repo_roots::list_repo_roots,
        super::http::repo_roots::get_repo_root,
        super::http::repo_roots::resolve_repo_root,
        super::http::repo_roots::list_repo_root_git_branches,
        super::http::repo_roots::detect_repo_root_setup,
        super::http::repo_roots::prepare_repo_root_mobility_destination,
        super::http::cowork::get_cowork_status,
        super::http::cowork::enable_cowork,
        super::http::cowork::list_cowork_threads,
        super::http::cowork::create_cowork_thread,
        super::http::cowork::get_cowork_manifest,
        super::http::cowork::get_cowork_artifact,
        super::http::workspaces::resolve_workspace,
        super::http::workspaces::create_workspace,
        super::http::workspaces::create_worktree,
        super::http::workspaces::list_workspaces,
        super::http::workspaces::get_workspace,
        super::http::workspaces::update_workspace_display_name,
        super::http::workspaces::get_workspace_session_launch_catalog,
        super::http::workspaces::detect_project_setup,
        super::http::workspaces::get_setup_status,
        super::http::workspaces::rerun_setup,
        super::http::workspaces::start_setup,
        super::http::mobility::preflight_workspace_mobility,
        super::http::mobility::update_workspace_mobility_runtime_state,
        super::http::mobility::export_workspace_mobility_archive,
        super::http::mobility::install_workspace_mobility_archive,
        super::http::mobility::destroy_workspace_mobility_source,
        super::http::sessions::create_session,
        super::http::sessions::update_session_title,
        super::http::sessions::get_live_session_config,
        super::http::sessions::set_session_config_option,
        super::http::sessions::prompt_session,
        super::http::sessions::edit_pending_prompt,
        super::http::sessions::delete_pending_prompt,
        super::http::sessions::resume_session,
        super::http::sessions::cancel_session,
        super::http::sessions::close_session,
        super::http::sessions::dismiss_session,
        super::http::sessions::restore_dismissed_session,
        super::http::sessions::list_sessions,
        super::http::sessions::get_session,
        super::http::sessions::list_session_events,
        super::http::sessions::list_session_raw_notifications,
        super::http::sessions::resolve_permission,
    ),
    components(schemas(
        HealthResponse,
        AgentInstallState,
        AgentCredentialState,
        AgentReadinessState,
        ArtifactStatus,
        AgentSummary,
        InstallAgentRequest,
        InstallAgentResponse,
        LoginCommand,
        StartAgentLoginRequest,
        StartAgentLoginResponse,
        ProblemDetails,
        RepoRootKind,
        RepoRoot,
        ResolveRepoRootFromPathRequest,
        PrepareRepoRootMobilityDestinationRequest,
        PrepareRepoRootMobilityDestinationResponse,
        CoworkRoot,
        CoworkStatus,
        CoworkArtifactType,
        CoworkArtifactSummary,
        CoworkArtifactManifestResponse,
        CoworkArtifactDetailResponse,
        CoworkThread,
        CreateCoworkThreadRequest,
        CreateCoworkThreadResponse,
        WorkspaceKind,
        WorkspaceSurface,
        WorkspaceExecutionPhase,
        WorkspaceExecutionSummary,
        Workspace,
        ResolveWorkspaceFromPathRequest,
        ResolveWorkspaceResponse,
        CreateWorkspaceRequest,
        CreateWorktreeWorkspaceRequest,
        SetupScriptStatus,
        SetupScriptExecution,
        CreateWorktreeWorkspaceResponse,
        UpdateWorkspaceDisplayNameRequest,
        WorkspaceSessionLaunchModel,
        WorkspaceSessionLaunchAgent,
        WorkspaceSessionLaunchCatalog,
        SessionStatus,
        SessionExecutionPhase,
        PendingApprovalSummary,
        SessionExecutionSummary,
        Session,
        SessionMcpEnvVar,
        SessionMcpHeader,
        SessionMcpHttpServer,
        SessionMcpStdioServer,
        SessionMcpServer,
        CreateSessionRequest,
        UpdateSessionTitleRequest,
        PromptInputBlock,
        PromptSessionRequest,
        PromptSessionResponse,
        PromptSessionStatus,
        PendingPromptSummary,
        EditPendingPromptRequest,
        PermissionDecision,
        ResolvePermissionRequest,
        RawSessionConfigValue,
        anyharness_contract::v1::SessionConfigOptionType,
        RawSessionConfigOption,
        NormalizedSessionControlValue,
        NormalizedSessionControl,
        NormalizedSessionControls,
        SessionLiveConfigSnapshot,
        GetSessionLiveConfigResponse,
        SetSessionConfigOptionRequest,
        ConfigApplyState,
        SetSessionConfigOptionResponse,
        SessionEventEnvelope,
        SessionRawNotificationEnvelope,
        SessionEvent,
        SessionStartedEvent,
        SessionEndedEvent,
        SessionEndReason,
        TurnStartedEvent,
        TurnEndedEvent,
        ItemStartedEvent,
        ItemDeltaEvent,
        ItemCompletedEvent,
        TranscriptItemPayload,
        TranscriptItemKind,
        TranscriptItemStatus,
        TranscriptItemDeltaPayload,
        ContentPart,
        ReasoningVisibility,
        TerminalLifecycleEvent,
        FileReadScope,
        FileOpenTarget,
        FileChangeOperation,
        PlanEntry,
        AvailableCommandsUpdatePayload,
        CurrentModeUpdatePayload,
        ConfigOptionUpdatePayload,
        SessionStateUpdatePayload,
        SessionInfoUpdatePayload,
        UsageUpdatePayload,
        PendingPromptAddedPayload,
        PendingPromptUpdatedPayload,
        PendingPromptRemovedPayload,
        PendingPromptRemovalReason,
        PermissionRequestedEvent,
        PermissionResolvedEvent,
        PermissionOutcome,
        ErrorEvent,
        StopReason,
        ReconcileOutcome,
        ReconcileJobStatus,
        ReconcileAgentsRequest,
        ReconcileAgentResult,
        ReconcileAgentsResponse,
        ProviderConfig,
        ModelEntry,
        ModelRegistry,
        ModelRegistryModel,
        GitStatusSnapshot,
        GitStatusSummary,
        GitActionAvailability,
        GitChangedFile,
        GitFileStatus,
        GitIncludedState,
        GitOperation,
        GitDiffResponse,
        GitBranchRef,
        StagePathsRequest,
        UnstagePathsRequest,
        CommitRequest,
        CommitResponse,
        PushRequest,
        PushResponse,
        CurrentPullRequestResponse,
        PullRequestSummary,
        PullRequestState,
        CreatePullRequestRequest,
        CreatePullRequestResponse,
        RunCommandRequest,
        RunCommandResponse,
        DetectProjectSetupResponse,
        SetupHint,
        SetupHintCategory,
        GetSetupStatusResponse,
        StartWorkspaceSetupRequest,
        WorkspaceMobilityRuntimeMode,
        WorkspaceMobilityRuntimeState,
        UpdateWorkspaceMobilityRuntimeStateRequest,
        WorkspaceMobilityBlocker,
        WorkspaceMobilitySessionCandidate,
        WorkspaceMobilityPreflightResponse,
        ExportWorkspaceMobilityArchiveRequest,
        InstallWorkspaceMobilityArchiveRequest,
        InstallWorkspaceMobilityArchiveResponse,
        DestroyWorkspaceMobilitySourceRequest,
        DestroyWorkspaceMobilitySourceResponse,
        WorkspaceMobilityArchive,
        WorkspaceMobilityFileEntry,
        WorkspaceMobilitySessionBundle,
        MobilitySessionRecord,
        MobilitySessionLiveConfigSnapshotRecord,
        MobilityPendingConfigChangeRecord,
        MobilityPendingPromptRecord,
        MobilitySessionEventRecord,
        MobilitySessionRawNotificationRecord,
    ))
)]
pub struct ApiDoc;

pub fn openapi_json() -> String {
    ApiDoc::openapi()
        .to_pretty_json()
        .expect("OpenAPI serialization should not fail")
}

#[cfg(test)]
mod tests {
    use serde_json::Value;

    use super::openapi_json;

    #[test]
    fn openapi_registers_workspace_and_session_paths() {
        let spec: Value = serde_json::from_str(&openapi_json()).expect("parse OpenAPI JSON");
        let paths = spec["paths"]
            .as_object()
            .expect("OpenAPI paths should be an object");

        for path in [
            "/v1/workspaces/resolve",
            "/v1/workspaces",
            "/v1/workspaces/worktrees",
            "/v1/workspaces/{workspace_id}",
            "/v1/workspaces/{workspace_id}/display-name",
            "/v1/workspaces/{workspace_id}/session-launch",
            "/v1/workspaces/{workspace_id}/detect-setup",
            "/v1/workspaces/{workspace_id}/setup-status",
            "/v1/workspaces/{workspace_id}/setup-rerun",
            "/v1/workspaces/{workspace_id}/setup-start",
            "/v1/sessions",
            "/v1/sessions/{session_id}",
            "/v1/sessions/{session_id}/title",
            "/v1/sessions/{session_id}/live-config",
            "/v1/sessions/{session_id}/config-options",
            "/v1/sessions/{session_id}/prompt",
            "/v1/sessions/{session_id}/resume",
            "/v1/sessions/{session_id}/cancel",
            "/v1/sessions/{session_id}/close",
            "/v1/sessions/{session_id}/dismiss",
            "/v1/workspaces/{workspace_id}/sessions/restore",
            "/v1/sessions/{session_id}/events",
            "/v1/sessions/{session_id}/raw-notifications",
            "/v1/sessions/{session_id}/permissions/{request_id}/resolve",
        ] {
            assert!(paths.contains_key(path), "missing OpenAPI path: {path}");
        }
    }

    #[test]
    fn openapi_registers_workspace_session_and_event_schemas() {
        let spec: Value = serde_json::from_str(&openapi_json()).expect("parse OpenAPI JSON");
        let schemas = spec["components"]["schemas"]
            .as_object()
            .expect("OpenAPI schemas should be an object");

        for schema in [
            "WorkspaceKind",
            "WorkspaceExecutionPhase",
            "WorkspaceExecutionSummary",
            "Workspace",
            "ResolveWorkspaceFromPathRequest",
            "CreateWorkspaceRequest",
            "CreateWorktreeWorkspaceRequest",
            "SetupScriptStatus",
            "SetupScriptExecution",
            "CreateWorktreeWorkspaceResponse",
            "SetupHintCategory",
            "SetupHint",
            "DetectProjectSetupResponse",
            "GetSetupStatusResponse",
            "StartWorkspaceSetupRequest",
            "UpdateWorkspaceDisplayNameRequest",
            "WorkspaceSessionLaunchModel",
            "WorkspaceSessionLaunchAgent",
            "WorkspaceSessionLaunchCatalog",
            "SessionStatus",
            "SessionExecutionPhase",
            "PendingApprovalSummary",
            "SessionExecutionSummary",
            "Session",
            "SessionMcpEnvVar",
            "SessionMcpHeader",
            "SessionMcpHttpServer",
            "SessionMcpStdioServer",
            "SessionMcpServer",
            "CreateSessionRequest",
            "UpdateSessionTitleRequest",
            "PromptInputBlock",
            "PromptSessionRequest",
            "PromptSessionResponse",
            "PromptSessionStatus",
            "PendingPromptSummary",
            "EditPendingPromptRequest",
            "PermissionDecision",
            "ResolvePermissionRequest",
            "RawSessionConfigValue",
            "SessionConfigOptionType",
            "RawSessionConfigOption",
            "NormalizedSessionControlValue",
            "NormalizedSessionControl",
            "NormalizedSessionControls",
            "SessionLiveConfigSnapshot",
            "GetSessionLiveConfigResponse",
            "SetSessionConfigOptionRequest",
            "ConfigApplyState",
            "SetSessionConfigOptionResponse",
            "SessionEventEnvelope",
            "SessionRawNotificationEnvelope",
            "SessionEvent",
            "SessionStartedEvent",
            "SessionEndedEvent",
            "SessionEndReason",
            "TurnStartedEvent",
            "TurnEndedEvent",
            "ItemStartedEvent",
            "ItemDeltaEvent",
            "ItemCompletedEvent",
            "TranscriptItemPayload",
            "TranscriptItemKind",
            "TranscriptItemStatus",
            "TranscriptItemDeltaPayload",
            "ContentPart",
            "ReasoningVisibility",
            "TerminalLifecycleEvent",
            "FileReadScope",
            "FileOpenTarget",
            "FileChangeOperation",
            "PlanEntry",
            "AvailableCommandsUpdatePayload",
            "CurrentModeUpdatePayload",
            "ConfigOptionUpdatePayload",
            "SessionStateUpdatePayload",
            "SessionInfoUpdatePayload",
            "UsageUpdatePayload",
            "PendingPromptAddedPayload",
            "PendingPromptUpdatedPayload",
            "PendingPromptRemovedPayload",
            "PendingPromptRemovalReason",
            "PermissionRequestedEvent",
            "PermissionResolvedEvent",
            "PermissionOutcome",
            "ErrorEvent",
            "StopReason",
        ] {
            assert!(
                schemas.contains_key(schema),
                "missing OpenAPI schema: {schema}"
            );
        }
    }
}
