use utoipa::OpenApi;

use anyharness_contract::v1::{
    AgentCredentialState, AgentInstallState, AgentReadinessState, AgentSummary, ArtifactStatus,
    CommitRequest, CommitResponse, CreatePullRequestRequest, CreatePullRequestResponse,
    CurrentPullRequestResponse, DetectProjectSetupResponse, GetSetupStatusResponse,
    GitActionAvailability, GitBranchRef, GitChangedFile, GitDiffResponse, GitFileStatus,
    GitIncludedState, GitOperation, GitStatusSnapshot, GitStatusSummary, HealthResponse,
    InstallAgentRequest, InstallAgentResponse, LoginCommand, ModelEntry, ModelRegistry,
    ModelRegistryModel, ProblemDetails, ProviderConfig, PullRequestState, PullRequestSummary,
    PushRequest, PushResponse, ReconcileAgentResult, ReconcileAgentsRequest,
    ReconcileAgentsResponse, ReconcileJobStatus, ReconcileOutcome, RegisterRepoWorkspaceRequest,
    RunCommandRequest, RunCommandResponse, SetupHint, SetupHintCategory, StagePathsRequest,
    StartAgentLoginRequest, StartAgentLoginResponse, StartWorkspaceSetupRequest,
    UnstagePathsRequest, Workspace,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "AnyHarness Runtime API",
        version = "0.1.0",
        description = "Local sidecar runtime for managing coding agent installations, credentials, and ACP sessions."
    ),
    paths(
        super::http::health::get_health,
        super::http::agents::list_agents,
        super::http::agents::get_agent,
        super::http::agents::install_agent,
        super::http::agents::start_agent_login,
        super::http::agents::get_reconcile_status,
        super::http::agents::reconcile_agents,
        super::http::model_registries::list_model_registries,
        super::http::model_registries::get_model_registry,
        super::http::provider_configs::list_provider_configs,
        super::http::git::get_git_status,
        super::http::git::get_git_diff,
        super::http::git::list_git_branches,
        super::http::git::stage_paths,
        super::http::git::unstage_paths,
        super::http::git::commit,
        super::http::git::push,
        super::http::hosting::get_current_pull_request,
        super::http::hosting::create_pull_request,
        super::http::processes::run_command,
        super::http::workspaces::register_repo_workspace,
        super::http::workspaces::detect_project_setup,
        super::http::workspaces::get_setup_status,
        super::http::workspaces::rerun_setup,
        super::http::workspaces::start_setup,
    ),
    components(schemas(
        HealthResponse,
        AgentInstallState,
        AgentCredentialState,
        AgentReadinessState,
        ArtifactStatus,
        AgentSummary,
        InstallAgentRequest,
        InstallAgentResponse,
        LoginCommand,
        StartAgentLoginRequest,
        StartAgentLoginResponse,
        ProblemDetails,
        Workspace,
        RegisterRepoWorkspaceRequest,
        ReconcileOutcome,
        ReconcileJobStatus,
        ReconcileAgentsRequest,
        ReconcileAgentResult,
        ReconcileAgentsResponse,
        ProviderConfig,
        ModelEntry,
        ModelRegistry,
        ModelRegistryModel,
        GitStatusSnapshot,
        GitStatusSummary,
        GitActionAvailability,
        GitChangedFile,
        GitFileStatus,
        GitIncludedState,
        GitOperation,
        GitDiffResponse,
        GitBranchRef,
        StagePathsRequest,
        UnstagePathsRequest,
        CommitRequest,
        CommitResponse,
        PushRequest,
        PushResponse,
        CurrentPullRequestResponse,
        PullRequestSummary,
        PullRequestState,
        CreatePullRequestRequest,
        CreatePullRequestResponse,
        RunCommandRequest,
        RunCommandResponse,
        DetectProjectSetupResponse,
        SetupHint,
        SetupHintCategory,
        GetSetupStatusResponse,
        StartWorkspaceSetupRequest,
    ))
)]
pub struct ApiDoc;

pub fn openapi_json() -> String {
    ApiDoc::openapi()
        .to_pretty_json()
        .expect("OpenAPI serialization should not fail")
}
