import type { TranscriptState } from "@anyharness/sdk";

export const PLAYGROUND_SUBAGENT_PARENT_SEND_TRANSCRIPT: TranscriptState = {
  sessionMeta: {
    sessionId: "playground-subagent-child",
    title: "Runtime Survey child",
    updatedAt: "2026-04-21T02:36:00Z",
    nativeSessionId: null,
    sourceAgentKind: "codex",
  },
  turnOrder: ["turn-parent-send"],
  turnsById: {
    "turn-parent-send": {
      turnId: "turn-parent-send",
      itemOrder: ["parent-sent-message", "child-response"],
      startedAt: "2026-04-21T02:35:00Z",
      completedAt: "2026-04-21T02:36:00Z",
      stopReason: "end_turn",
      fileBadges: [],
    },
  },
  itemsById: {
    "parent-sent-message": {
      kind: "user_message",
      itemId: "parent-sent-message",
      turnId: "turn-parent-send",
      status: "completed",
      sourceAgentKind: "system",
      messageId: null,
      title: null,
      nativeToolName: null,
      parentToolCallId: null,
      rawInput: undefined,
      rawOutput: undefined,
      contentParts: [],
      timestamp: "2026-04-21T02:35:00Z",
      startedSeq: 1,
      lastUpdatedSeq: 1,
      completedSeq: 1,
      completedAt: "2026-04-21T02:35:00Z",
      text: "Please inspect the runtime server SDK path for delegated-work regressions.",
      isStreaming: false,
      promptProvenance: {
        type: "agentSession",
        sourceSessionId: "playground-parent-session",
        sessionLinkId: "link-runtime-survey",
        label: "Parent delegation session",
      },
    },
    "child-response": {
      kind: "assistant_prose",
      itemId: "child-response",
      turnId: "turn-parent-send",
      status: "completed",
      sourceAgentKind: "codex",
      messageId: null,
      title: null,
      nativeToolName: null,
      parentToolCallId: null,
      rawInput: undefined,
      rawOutput: undefined,
      contentParts: [],
      timestamp: "2026-04-21T02:36:00Z",
      startedSeq: 2,
      lastUpdatedSeq: 2,
      completedSeq: 2,
      completedAt: "2026-04-21T02:36:00Z",
      text: "I will inspect the delegated-work identity path and report back.",
      isStreaming: false,
    },
  },
  openAssistantItemId: null,
  openThoughtItemId: null,
  pendingInteractions: [],
  availableCommands: [],
  liveConfig: null,
  currentModeId: null,
  usageState: null,
  unknownEvents: [],
  isStreaming: false,
  lastSeq: 2,
  pendingPrompts: [],
  linkCompletionsByCompletionId: {},
  latestLinkCompletionBySessionLinkId: {},
};
