import { attach, shot } from './helper.mjs';
const { browser, ctx } = await attach();
const pages = ctx.pages().filter(p => p.url().startsWith('https://app.slack.com/client'));
const page = pages[pages.length - 1];
await page.bringToFront();
await page.keyboard.press('Escape');
await page.waitForTimeout(1000);
await shot(page, 'alerts-final');
console.log('URL:', page.url());
await browser.close();
process.exit(0);
