#!/usr/bin/env bash
#
# Self-host smoke, phase 1: boots the production compose stack the same way an
# operator does (bootstrap.sh: generated secrets, migrate, health gate) with an
# http-only Caddy site address so no DNS or TLS issuance is needed, then
# asserts the deployment responds. Later phases extend the assertions with the
# first-run claim, login, and invite journey as those server features land.
#
# Requirements: Docker with Compose v2.24.4+ (for the port overrides in
# smoke/docker-compose.smoke.yml) and curl. Nothing else.
#
# Usage:
#   server/deploy/smoke/run-smoke.sh
#
# Environment:
#   PROLIFERATE_SMOKE_IMAGE       Prebuilt server image (repository:tag). When
#                                 unset, builds proliferate-server:smoke from
#                                 server/Dockerfile.
#   PROLIFERATE_SMOKE_HTTP_PORT   Host port for the http-only Caddy site
#                                 (default 8080).
#   PROLIFERATE_SMOKE_API_PORT    Host port mapped to the API container
#                                 (default 18000).
#   PROLIFERATE_SMOKE_KEEP_STACK  true|1 leaves the stack and work dir up for
#                                 inspection instead of tearing down.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$DEPLOY_DIR/../.." && pwd)"

SMOKE_IMAGE="${PROLIFERATE_SMOKE_IMAGE:-}"
HTTP_PORT="${PROLIFERATE_SMOKE_HTTP_PORT:-8080}"
API_PORT="${PROLIFERATE_SMOKE_API_PORT:-18000}"
KEEP_STACK="${PROLIFERATE_SMOKE_KEEP_STACK:-false}"

export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-proliferate-smoke}"

log() { printf '[smoke] %s\n' "$*"; }

fail() {
  printf '[smoke] FAIL: %s\n' "$*" >&2
  exit 1
}

command -v docker >/dev/null 2>&1 || fail "Docker is required."
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required."
command -v curl >/dev/null 2>&1 || fail "curl is required."

# --- Server image -----------------------------------------------------------

if [[ -z "$SMOKE_IMAGE" ]]; then
  SMOKE_IMAGE="proliferate-server:smoke"
  log "PROLIFERATE_SMOKE_IMAGE not set; building $SMOKE_IMAGE from server/Dockerfile"
  docker build -f "$REPO_ROOT/server/Dockerfile" -t "$SMOKE_IMAGE" "$REPO_ROOT"
fi

IMAGE_REPOSITORY="${SMOKE_IMAGE%:*}"
IMAGE_TAG="${SMOKE_IMAGE##*:}"
if [[ "$IMAGE_TAG" == "$SMOKE_IMAGE" || "$IMAGE_TAG" == */* ]]; then
  fail "PROLIFERATE_SMOKE_IMAGE must be a repository:tag reference, got: $SMOKE_IMAGE"
fi

# --- Stage an operator-style install dir ------------------------------------
# The deploy bundle is copied to a scratch dir so generated env files never
# touch the checkout, mirroring an operator install of server/deploy/**.

WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/proliferate-smoke.XXXXXX")"
STACK_DIR="$WORK_DIR/deploy"
BIN_DIR="$WORK_DIR/bin"

cp -R "$DEPLOY_DIR" "$STACK_DIR"
mkdir -p "$BIN_DIR"

# Drop any env state copied from a previously bootstrapped checkout.
find "$STACK_DIR" -maxdepth 1 -name ".env*" ! -name ".env.production.example" -exec rm -f {} +

OVERRIDE_FILE="$STACK_DIR/smoke/docker-compose.smoke.yml"
RUNTIME_ENV_FILE="$STACK_DIR/.env.runtime"

read_env_value() {
  local file="$1"
  local key="$2"
  local line

  if [[ ! -f "$file" ]]; then
    return 0
  fi

  line="$(grep -m1 "^${key}=" "$file" || true)"
  if [[ -z "$line" ]]; then
    return 0
  fi

  printf '%s' "${line#*=}"
}

compose_stack() {
  docker compose \
    --env-file "$RUNTIME_ENV_FILE" \
    -f "$STACK_DIR/docker-compose.production.yml" \
    -f "$OVERRIDE_FILE" \
    "$@"
}

cleanup() {
  local exit_code=$?
  trap - EXIT

  if (( exit_code != 0 )); then
    log "Smoke failed; dumping stack logs."
    docker compose -p "$COMPOSE_PROJECT_NAME" logs --no-color --tail=200 >&2 || true
  fi

  if [[ "$KEEP_STACK" == "true" || "$KEEP_STACK" == "1" ]]; then
    log "PROLIFERATE_SMOKE_KEEP_STACK set; stack '$COMPOSE_PROJECT_NAME' and $WORK_DIR left in place."
  else
    docker compose -p "$COMPOSE_PROJECT_NAME" down --volumes --remove-orphans >/dev/null 2>&1 || true
    rm -rf "$WORK_DIR"
  fi

  exit "$exit_code"
}
trap cleanup EXIT

# Operator flow: .env.static is the reviewed copy of the example; the
# smoke-specific values ride the .env.local override channel ensure-secrets.sh
# already honors. The http:// site address keeps Caddy from provisioning
# certificates, so the stack boots without DNS while still proxying through
# the production Caddyfile.
cp "$STACK_DIR/.env.production.example" "$STACK_DIR/.env.static"
cat >"$STACK_DIR/.env.local" <<EOF
# Smoke overrides (generated by run-smoke.sh).
SITE_ADDRESS=http://localhost
PROLIFERATE_PUBLIC_HEALTHCHECK_URL=http://localhost:${HTTP_PORT}/health
PROLIFERATE_SERVER_IMAGE=${IMAGE_REPOSITORY}
PROLIFERATE_SERVER_IMAGE_TAG=${IMAGE_TAG}
PROLIFERATE_HOST_BIN_DIR=${BIN_DIR}
PROLIFERATE_SMOKE_HTTP_PORT=${HTTP_PORT}
PROLIFERATE_SMOKE_API_PORT=${API_PORT}
PROLIFERATE_ANONYMOUS_TELEMETRY_DISABLED=true
EOF

# --- Bootstrap (secrets, migrate, boot, health gate) -------------------------

log "Bootstrapping stack (project: $COMPOSE_PROJECT_NAME, image: $SMOKE_IMAGE)"
PROLIFERATE_COMPOSE_OVERRIDE_FILE="$OVERRIDE_FILE" \
  PROLIFERATE_HEALTHCHECK_URL="http://127.0.0.1:${API_PORT}/health" \
  "$STACK_DIR/bootstrap.sh"

# --- Assertions ---------------------------------------------------------------
# Phase 1: unauthenticated health through the production proxy path.
# Phase 2 (after first-run claim lands): POST /setup claim + login.
# Phase 3 (after invite-as-allowlist lands): invite + register + org checks.

LAST_RESPONSE_BODY=""

assert_http_200() {
  local label="$1"
  local url="$2"
  local status
  local body_file="$WORK_DIR/response.body"

  status="$(curl -sS -o "$body_file" -w '%{http_code}' "$url" || true)"
  if [[ "$status" != "200" ]]; then
    fail "$label: expected HTTP 200 from $url, got ${status:-no response} $(cat "$body_file" 2>/dev/null || true)"
  fi
  LAST_RESPONSE_BODY="$(cat "$body_file")"
  log "PASS  $label: GET $url -> 200 $LAST_RESPONSE_BODY"
}

assert_migrations_applied() {
  local db_user db_name versions

  db_user="$(read_env_value "$RUNTIME_ENV_FILE" POSTGRES_USER)"
  db_name="$(read_env_value "$RUNTIME_ENV_FILE" POSTGRES_DB)"
  versions="$(compose_stack exec -T db psql -U "${db_user:-proliferate}" \
    -d "${db_name:-proliferate}" -tAc "select count(*) from alembic_version")" \
    || fail "migrations: could not query alembic_version"
  if [[ ! "$versions" =~ ^[1-9] ]]; then
    fail "migrations: alembic_version is empty; migrate did not run"
  fi
  log "PASS  migrations applied (alembic_version populated)"
}

phase_health() {
  assert_http_200 "health via Caddy (http-only)" "http://localhost:${HTTP_PORT}/health"
  if [[ "$LAST_RESPONSE_BODY" != *'"status":"ok"'* ]]; then
    fail "health body missing status ok: $LAST_RESPONSE_BODY"
  fi
  assert_http_200 "health direct from API" "http://127.0.0.1:${API_PORT}/health"
  assert_migrations_applied
}

phase_health

log "SMOKE OK: production compose stack booted, migrated, and serves /health."
