export { AnyHarnessClient, AnyHarnessError } from "./client/core.js";
export type { AnyHarnessClientOptions, AnyHarnessRequestOptions } from "./client/core.js";

export type {
  HealthResponse,
  RuntimeCapabilities,
  AgentSeedHealth,
  AgentSeedStatus,
  AgentSeedSource,
  AgentSeedOwnership,
  AgentSeedLastAction,
  AgentSeedFailureKind,
  ProblemDetails,
} from "./types/runtime.js";

export type {
  ReplayRecordingSummary,
  ListReplayRecordingsResponse,
  ExportReplayRecordingRequest,
  ExportReplayRecordingResponse,
  CreateReplaySessionRequest,
  CreateReplaySessionResponse,
  AdvanceReplaySessionResponse,
} from "./types/replay.js";

export type {
  AgentInstallState,
  AgentCredentialState,
  AgentReadinessState,
  ArtifactStatus,
  AgentSummary,
  InstallAgentRequest,
  InstallAgentResponse,
  LoginCommand,
  StartAgentLoginResponse,
  ReconcileOutcome,
  ReconcileJobStatus,
  ReconcileAgentsRequest,
  ReconcileAgentResult,
  ReconcileAgentsResponse,
} from "./types/agents.js";

export type {
  ModelCatalogStatus,
  ModelLaunchRemediation,
  ModelLaunchRemediationKind,
  ModelRegistry,
  ModelRegistryModel,
} from "./types/model-registries.js";

export type {
  ProviderConfig,
  ModelEntry,
} from "./types/providers.js";

export type {
  RepoRootKind,
  RepoRoot,
  ResolveRepoRootFromPathRequest,
  PrepareRepoRootMobilityDestinationRequest,
  PrepareRepoRootMobilityDestinationResponse,
  GitBranchRef as RepoRootGitBranchRef,
  DetectProjectSetupResponse as RepoRootDetectProjectSetupResponse,
} from "./types/repo-roots.js";

export type {
  WorkspaceMobilityRuntimeMode,
  WorkspaceMobilityRuntimeState,
  UpdateWorkspaceMobilityRuntimeStateRequest,
  WorkspaceMobilityBlocker,
  WorkspaceMobilitySessionCandidate,
  WorkspaceMobilityPreflightResponse,
  ExportWorkspaceMobilityArchiveRequest,
  InstallWorkspaceMobilityArchiveRequest,
  InstallWorkspaceMobilityArchiveResponse,
  DestroyWorkspaceMobilitySourceRequest,
  DestroyWorkspaceMobilitySourceResponse,
  WorkspaceMobilityArchive,
  WorkspaceMobilityFileEntry,
  WorkspaceMobilitySessionBundle,
  MobilitySessionRecord,
  MobilitySessionLiveConfigSnapshotRecord,
  MobilityPendingConfigChangeRecord,
  MobilityPendingPromptRecord,
  MobilitySessionEventRecord,
  MobilitySessionRawNotificationRecord,
} from "./types/mobility.js";

export type {
  CoworkRoot,
  CoworkStatus,
  CoworkArtifactType,
  CoworkArtifactSummary,
  CoworkArtifactManifestResponse,
  CoworkArtifactDetailResponse,
  CoworkThread,
  CreateCoworkThreadRequest,
  CreateCoworkThreadResponse,
  CoworkManagedWorkspacesResponse,
  CoworkManagedWorkspaceSummary,
  CoworkCodingSessionSummary,
} from "./types/cowork.js";

export type {
  WorkspaceKind,
  WorkspaceSurface,
  WorkspaceExecutionPhase,
  WorkspaceExecutionSummary,
  OriginKind,
  OriginEntrypoint,
  OriginContext,
  WorkspaceCreatorContext,
  Workspace,
  ResolveWorkspaceResponse,
  WorkspaceSessionLaunchModel,
  WorkspaceSessionLaunchAgent,
  WorkspaceSessionLaunchCatalog,
  ResolveWorkspaceFromPathRequest,
  CreateWorkspaceRequest,
  CreateWorktreeWorkspaceRequest,
  SetupScriptStatus,
  SetupScriptExecution,
  CreateWorktreeWorkspaceResponse,
  SetupHintCategory,
  SetupHint,
  DetectProjectSetupResponse,
  GetSetupStatusResponse,
  StartWorkspaceSetupRequest,
  UpdateWorkspaceDisplayNameRequest,
} from "./types/workspaces.js";

export type {
  SessionStatus,
  SessionExecutionPhase,
  PendingInteractionSummary,
  PendingInteractionSource,
  PendingInteractionPayloadSummary,
  SessionExecutionSummary,
  Session,
  SessionMcpEnvVar,
  RawSessionConfigValue,
  RawSessionConfigOption,
  SessionConfigOptionType,
  SessionMcpHeader,
  SessionMcpHttpServer,
  SessionMcpStdioServer,
  SessionMcpServer,
  SessionMcpTransport,
  SessionMcpBindingOutcome,
  SessionMcpBindingNotAppliedReason,
  SessionMcpBindingSummary,
  ResumeSessionRequest,
  NormalizedSessionControlValue,
  NormalizedSessionControl,
  NormalizedSessionControls,
  SessionLiveConfigSnapshot,
  PromptCapabilities,
  GetSessionLiveConfigResponse,
  SetSessionConfigOptionRequest,
  SetSessionConfigOptionResponse,
  ConfigApplyState,
  CreateSessionRequest,
  UpdateSessionTitleRequest,
  PromptInputBlock,
  PromptSessionRequest,
  PromptSessionResponse,
  PromptSessionStatus,
  PendingPromptSummary,
  EditPendingPromptRequest,
  SessionSubagentsResponse,
  ParentSubagentLinkSummary,
  ChildSubagentSummary,
  SubagentCompletionSummary,
  InteractionDecision,
  ListSessionEventsOptions,
  McpElicitationUrlRevealResponse,
  ResolveInteractionRequest,
} from "./types/sessions.js";

export type {
  ProposedPlanSummary,
  ProposedPlanDetail,
  ListProposedPlansResponse,
  ProposedPlanDocumentResponse,
  PlanDecisionRequest,
  PlanDecisionResponse,
  HandoffPlanRequest,
  HandoffPlanResponse,
  PlanHandoffPromptStatus,
  ProposedPlanDecisionState,
  ProposedPlanNativeResolutionState,
} from "./types/plans.js";

export type {
  ReviewKind,
  ReviewRunStatus,
  ReviewRoundStatus,
  ReviewAssignmentStatus,
  ReviewFeedbackDeliveryState,
  ReviewModeVerificationStatus,
  ReviewPersonaRequest,
  StartPlanReviewRequest,
  StartCodeReviewRequest,
  MarkReviewRevisionReadyRequest,
  ReviewAssignmentDetail,
  ReviewCritiqueResponse,
  ReviewFeedbackDeliveryDetail,
  ReviewRoundDetail,
  ReviewRunDetail,
  ReviewRunResponse,
  SessionReviewsResponse,
} from "./types/reviews.js";

export type {
  SessionEventEnvelope,
  SessionRawNotificationEnvelope,
  SessionEvent,
  SessionStartedEvent,
  SessionEndedEvent,
  SessionEndReason,
  TurnStartedEvent,
  TurnEndedEvent,
  StopReason,
  ItemStartedEvent,
  ItemDeltaEvent,
  ItemCompletedEvent,
  TranscriptItemPayload,
  TranscriptItemKind,
  TranscriptItemStatus,
  TranscriptItemDeltaPayload,
  PromptProvenance,
  SubagentTurnOutcome,
  ContentPart,
  TextContentPart,
  ReasoningContentPart,
  ReasoningVisibility,
  ToolCallContentPart,
  TerminalOutputContentPart,
  TerminalLifecycleEvent,
  FileReadContentPart,
  FileReadScope,
  FileChangeContentPart,
  FileChangeOperation,
  FileOpenTarget,
  PlanContentPart,
  ProposedPlanContentPart,
  PlanReferenceContentPart,
  ProposedPlanDecisionContentPart,
  ToolInputTextContentPart,
  ToolResultTextContentPart,
  PlanEntry,
  AvailableCommandsUpdateEvent,
  CurrentModeUpdateEvent,
  ConfigOptionUpdateEvent,
  SessionStateUpdateEvent,
  SessionInfoUpdateEvent,
  UsageUpdateEvent,
  PendingPromptAddedEvent,
  PendingPromptUpdatedEvent,
  PendingPromptRemovedEvent,
  PendingPromptRemovalReason,
  InteractionKind,
  InteractionSource,
  InteractionPayload,
  InteractionOutcome,
  PermissionInteractionPayload,
  PermissionInteractionContext,
  PermissionInteractionOption,
  PermissionInteractionOptionKind,
  UserInputInteractionPayload,
  UserInputQuestion,
  UserInputQuestionOption,
  UserInputSubmittedAnswer,
  McpElicitationInteractionPayload,
  McpElicitationMode,
  McpElicitationFormPayload,
  McpElicitationUrlPayload,
  McpElicitationField,
  McpElicitationFieldBase,
  McpElicitationTextField,
  McpElicitationTextFormat,
  McpElicitationNumberField,
  McpElicitationBooleanField,
  McpElicitationSelectField,
  McpElicitationMultiSelectField,
  McpElicitationOption,
  McpElicitationSubmittedField,
  McpElicitationSubmittedValue,
  InteractionRequestedEvent,
  InteractionResolvedEvent,
  ErrorEvent,
} from "./types/events.js";

export type {
  TranscriptState,
  TurnRecord,
  FileBadge,
  TranscriptItem,
  TranscriptBaseItem,
  UserMessageItem,
  AssistantProseItem,
  ThoughtItem,
  ToolCallItem,
  ToolCallSemanticKind,
  PlanItem,
  ProposedPlanItem,
  CanonicalPlan,
  CanonicalPlanSourceKind,
  ErrorItem,
  UnknownItem,
  PendingInteraction,
  PendingApproval,
  PendingPermissionInteraction,
  PendingUserInputInteraction,
  PendingMcpElicitationInteraction,
  PendingPromptEntry,
  UsageState,
} from "./types/reducer.js";

export {
  createTranscriptState,
  reduceEvent,
  reduceEvents,
  selectPendingApprovalInteraction,
  selectPendingMcpElicitationInteraction,
  selectPendingUserInputInteraction,
  selectPrimaryPendingInteraction,
  isFileReadPart,
  isFileChangePart,
} from "./reducer/transcript.js";
export type { ReduceOptions } from "./reducer/transcript.js";
export type {
  ToolBackgroundWorkMetadata,
  ToolBackgroundWorkState,
  ToolBackgroundWorkTrackerKind,
} from "./reducer/background-work.js";
export { parseToolBackgroundWork } from "./reducer/background-work.js";

export { deriveCanonicalPlan } from "./reducer/canonical-plan.js";

export type {
  WorkspaceFileKind,
  WorkspaceFileEntry,
  ListWorkspaceFilesResponse,
  WorkspaceFileSearchResult,
  SearchWorkspaceFilesResponse,
  ReadWorkspaceFileResponse,
  WriteWorkspaceFileRequest,
  WriteWorkspaceFileResponse,
  StatWorkspaceFileResponse,
} from "./types/files.js";

export type {
  GitOperation,
  GitFileStatus,
  GitIncludedState,
  GitStatusSummary,
  GitActionAvailability,
  GitChangedFile,
  GitStatusSnapshot,
  GitDiffScope,
  GitDiffFile,
  GitDiffResponse,
  GitBranchDiffFilesResponse,
  GitDiffOptions,
  ListBranchDiffFilesOptions,
  GitBranchRef,
  RenameBranchRequest,
  RenameBranchResponse,
  StagePathsRequest,
  UnstagePathsRequest,
  CommitRequest,
  CommitResponse,
  PushRequest,
  PushResponse,
} from "./types/git.js";

export type {
  PullRequestState,
  PullRequestSummary,
  CurrentPullRequestResponse,
  CreatePullRequestRequest,
  CreatePullRequestResponse,
} from "./types/hosting.js";

export type {
  TerminalPurpose,
  TerminalStatus,
  TerminalRecord,
  CreateTerminalRequest,
  ResizeTerminalRequest,
  UpdateTerminalTitleRequest,
} from "./types/terminals.js";

export type {
  RunCommandRequest,
  RunCommandResponse,
} from "./types/processes.js";

export { connectTerminal } from "./streams/terminals.js";
export type { TerminalStreamOptions, TerminalStreamHandle } from "./streams/terminals.js";

export { streamSession } from "./streams/sessions.js";
export type { SessionStreamOptions, SessionStreamHandle } from "./streams/sessions.js";
