use std::{collections::BTreeMap, path::Path};

use crate::error::WorkerError;

use super::files::{materialization_error, write_file};

pub fn write_env_file(
    workspace_root: &Path,
    repo_env_vars: &BTreeMap<String, String>,
) -> Result<usize, WorkerError> {
    let mut contents = String::from("# Generated by Proliferate Worker. Do not edit.\n");
    for (name, value) in repo_env_vars {
        validate_env_name(name)?;
        contents.push_str("export ");
        contents.push_str(name);
        contents.push('=');
        contents.push_str(&single_quote(value));
        contents.push('\n');
    }
    write_file(
        &workspace_root
            .join(".proliferate")
            .join("env")
            .join("session.env"),
        contents.as_bytes(),
        true,
    )?;
    Ok(repo_env_vars.len())
}

fn validate_env_name(name: &str) -> Result<(), WorkerError> {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return Err(materialization_error("empty environment variable name"));
    };
    if !(first == '_' || first.is_ascii_alphabetic()) {
        return Err(materialization_error(format!(
            "invalid environment variable name: {name}"
        )));
    }
    if !chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric()) {
        return Err(materialization_error(format!(
            "invalid environment variable name: {name}"
        )));
    }
    Ok(())
}

fn single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::single_quote;

    #[test]
    fn quotes_shell_values() {
        assert_eq!(single_quote("abc"), "'abc'");
        assert_eq!(single_quote("a'b"), "'a'\\''b'");
    }
}
