"""AI magic constants."""

SESSION_TITLE_RATE_LIMIT_REQUESTS = 20
SESSION_TITLE_RATE_LIMIT_WINDOW_SECONDS = 60 * 10
SESSION_TITLE_MAX_PROMPT_CHARS = 4000
SESSION_TITLE_MAX_TITLE_CHARS = 80

WORKSPACE_NAME_RATE_LIMIT_REQUESTS = 20
WORKSPACE_NAME_RATE_LIMIT_WINDOW_SECONDS = 60 * 10
WORKSPACE_NAME_MAX_PROMPT_CHARS = 4000
WORKSPACE_NAME_MAX_NAME_CHARS = 60

GIT_PUBLISH_RATE_LIMIT_REQUESTS = 20
GIT_PUBLISH_RATE_LIMIT_WINDOW_SECONDS = 60 * 10
GIT_PUBLISH_MAX_PROMPT_CHARS = 8000
GIT_PUBLISH_MAX_INSTRUCTIONS_CHARS = 2000
GIT_PUBLISH_MAX_COMMIT_MESSAGE_CHARS = 500
GIT_PUBLISH_MAX_PR_TITLE_CHARS = 72
GIT_PUBLISH_MAX_PR_BODY_CHARS = 2000
