"""AI magic constants."""

SESSION_TITLE_RATE_LIMIT_REQUESTS = 20
SESSION_TITLE_RATE_LIMIT_WINDOW_SECONDS = 60 * 10
SESSION_TITLE_MAX_PROMPT_CHARS = 4000
SESSION_TITLE_MAX_TITLE_CHARS = 80

WORKSPACE_NAME_RATE_LIMIT_REQUESTS = 20
WORKSPACE_NAME_RATE_LIMIT_WINDOW_SECONDS = 60 * 10
WORKSPACE_NAME_MAX_PROMPT_CHARS = 4000
WORKSPACE_NAME_MAX_NAME_CHARS = 60

COMMIT_MESSAGE_RATE_LIMIT_REQUESTS = 30
COMMIT_MESSAGE_RATE_LIMIT_WINDOW_SECONDS = 60 * 10
COMMIT_MESSAGE_MAX_DIFF_EXCERPT_CHARS = 20000
COMMIT_MESSAGE_MAX_DIFF_STAT_CHARS = 2000
COMMIT_MESSAGE_MAX_MESSAGE_CHARS = 500
