"""AI magic constants."""

SESSION_TITLE_RATE_LIMIT_REQUESTS = 20
SESSION_TITLE_RATE_LIMIT_WINDOW_SECONDS = 60 * 10
SESSION_TITLE_MAX_PROMPT_CHARS = 4000
SESSION_TITLE_MAX_TITLE_CHARS = 80

WORKSPACE_NAME_RATE_LIMIT_REQUESTS = 20
WORKSPACE_NAME_RATE_LIMIT_WINDOW_SECONDS = 60 * 10
WORKSPACE_NAME_MAX_PROMPT_CHARS = 4000
WORKSPACE_NAME_MAX_NAME_CHARS = 60
