"""Auth-related constants."""

# PKCE
SUPPORTED_CODE_CHALLENGE_METHODS = frozenset({"S256"})

# Token lifetimes
JWT_LIFETIME_SECONDS = 60 * 60 * 24 * 7  # 7 days
REFRESH_TOKEN_LIFETIME_SECONDS = 60 * 60 * 24 * 30  # 30 days
AUTH_CODE_LIFETIME_SECONDS = 60

# Password auth
PASSWORD_EMAIL_MAX_LENGTH = 320
PASSWORD_MIN_LENGTH = 12
PASSWORD_MAX_LENGTH = 256
PASSWORD_LOGIN_FAILURE_LIMIT = 5
PASSWORD_LOGIN_WINDOW_SECONDS = 15 * 60
PASSWORD_LOGIN_BLOCK_SECONDS = 15 * 60
PASSWORD_LOGIN_EMAIL_BUCKET = "email"
PASSWORD_LOGIN_IP_BUCKET = "ip"

# Desktop auth flow
DESKTOP_REDIRECT_SCHEME = "proliferate"
DESKTOP_REDIRECT_SCHEMES = frozenset({DESKTOP_REDIRECT_SCHEME, "proliferate-local"})
DESKTOP_DEEP_LINK_LAUNCH_ENABLED = True
DESKTOP_CALLBACK_PATH = "/auth/callback"
DESKTOP_GITHUB_CSRF_COOKIE = "desktop_github_csrf"
GITHUB_OAUTH_SCOPES = ["repo", "user", "user:email"]
