"""Shared hardcoded constants for automation definitions and runs."""

from __future__ import annotations

from typing import Final

from dateutil.rrule import DAILY, HOURLY

AUTOMATION_TARGET_MODE_LOCAL: Final = "local"
AUTOMATION_TARGET_MODE_PERSONAL_CLOUD: Final = "personal_cloud"
AUTOMATION_TARGET_MODE_SHARED_CLOUD: Final = "shared_cloud"
SUPPORTED_AUTOMATION_TARGET_MODES: Final = frozenset(
    {
        AUTOMATION_TARGET_MODE_LOCAL,
        AUTOMATION_TARGET_MODE_PERSONAL_CLOUD,
        AUTOMATION_TARGET_MODE_SHARED_CLOUD,
    }
)
AUTOMATION_EXECUTION_TARGET_CLOUD: Final = "cloud"
AUTOMATION_EXECUTION_TARGET_LOCAL: Final = AUTOMATION_TARGET_MODE_LOCAL

AUTOMATION_OWNER_SCOPE_PERSONAL: Final = "personal"
AUTOMATION_OWNER_SCOPE_ORGANIZATION: Final = "organization"
SUPPORTED_AUTOMATION_OWNER_SCOPES: Final = frozenset(
    {
        AUTOMATION_OWNER_SCOPE_PERSONAL,
        AUTOMATION_OWNER_SCOPE_ORGANIZATION,
    }
)

CLOUD_AGENT_RUN_CONFIG_OWNER_SCOPE_SYSTEM: Final = "system"
CLOUD_AGENT_RUN_CONFIG_OWNER_SCOPE_PERSONAL: Final = "personal"
CLOUD_AGENT_RUN_CONFIG_OWNER_SCOPE_ORGANIZATION: Final = "organization"
SUPPORTED_CLOUD_AGENT_RUN_CONFIG_OWNER_SCOPES: Final = frozenset(
    {
        CLOUD_AGENT_RUN_CONFIG_OWNER_SCOPE_SYSTEM,
        CLOUD_AGENT_RUN_CONFIG_OWNER_SCOPE_PERSONAL,
        CLOUD_AGENT_RUN_CONFIG_OWNER_SCOPE_ORGANIZATION,
    }
)
CLOUD_AGENT_RUN_CONFIG_STATUS_ACTIVE: Final = "active"
CLOUD_AGENT_RUN_CONFIG_STATUS_ARCHIVED: Final = "archived"

AUTOMATION_RUN_TRIGGER_MANUAL: Final = "manual"
AUTOMATION_RUN_TRIGGER_SCHEDULED: Final = "scheduled"

AUTOMATION_RUN_STATUS_QUEUED: Final = "queued"
AUTOMATION_RUN_STATUS_CLAIMED: Final = "claimed"
AUTOMATION_RUN_STATUS_CREATING_WORKSPACE: Final = "creating_workspace"
AUTOMATION_RUN_STATUS_PROVISIONING_WORKSPACE: Final = "provisioning_workspace"
AUTOMATION_RUN_STATUS_CREATING_SESSION: Final = "creating_session"
AUTOMATION_RUN_STATUS_DISPATCHING: Final = "dispatching"
AUTOMATION_RUN_STATUS_DISPATCHED: Final = "dispatched"
AUTOMATION_RUN_STATUS_FAILED: Final = "failed"
AUTOMATION_RUN_STATUS_CANCELLED: Final = "cancelled"

AUTOMATION_EXECUTOR_KIND_CLOUD: Final = "cloud"
AUTOMATION_EXECUTOR_KIND_DESKTOP: Final = "desktop"

AUTOMATION_SHORT_TEXT_MAX_LENGTH: Final = 255
AUTOMATION_TITLE_MAX_LENGTH: Final = AUTOMATION_SHORT_TEXT_MAX_LENGTH
AUTOMATION_REPO_PART_MAX_LENGTH: Final = AUTOMATION_SHORT_TEXT_MAX_LENGTH
AUTOMATION_OPTIONAL_TEXT_MAX_LENGTH: Final = AUTOMATION_SHORT_TEXT_MAX_LENGTH
AUTOMATION_EXTERNAL_ID_MAX_LENGTH: Final = AUTOMATION_SHORT_TEXT_MAX_LENGTH
AUTOMATION_LOCAL_ERROR_CODE_MAX_LENGTH: Final = 64
AUTOMATION_LOCAL_CLAIM_TTL_SECONDS: Final = 300.0
AUTOMATION_LOCAL_CLAIM_MAX_LIMIT: Final = 1
AUTOMATION_LOCAL_REPOSITORY_IDENTITIES_MAX_LIMIT: Final = 200
AUTOMATION_LOCAL_FALLBACK_ERROR_CODE: Final = "local_unexpected_executor_error"
AUTOMATION_LOCAL_SHARED_ERROR_CODES: Final = frozenset(
    {
        "agent_not_configured",
        "dispatch_uncertain",
        "stale_claim",
    }
)

AUTOMATION_RUN_LIST_DEFAULT_LIMIT: Final = 50
AUTOMATION_RUN_LIST_MAX_LIMIT: Final = 100

AUTOMATION_SCHEDULE_ANCHOR_YEAR: Final = 2020
SUPPORTED_AUTOMATION_RRULE_FREQS: Final = frozenset({HOURLY, DAILY})
SUPPORTED_AUTOMATION_RRULE_KEYS: Final = frozenset(
    {
        "FREQ",
        "INTERVAL",
        "BYDAY",
        "BYHOUR",
        "BYMINUTE",
    }
)
AUTOMATION_WEEKDAY_LABELS: Final = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
