"""Billing-related constants."""

FREE_INCLUDED_GRANT_TYPE = "free_included"
UNLIMITED_CLOUD_ENTITLEMENT = "unlimited_cloud"

BILLING_MODE_OFF = "off"
BILLING_MODE_OBSERVE = "observe"
BILLING_MODE_ENFORCE = "enforce"
BILLING_MODES: frozenset[str] = frozenset(
    {BILLING_MODE_OFF, BILLING_MODE_OBSERVE, BILLING_MODE_ENFORCE}
)
USAGE_SEGMENT_RECENT_LOOKBACK_DAYS = 90

ACTIVE_SANDBOX_STATUSES: frozenset[str] = frozenset({"allocating", "provisioning", "running"})

USAGE_SEGMENT_OPENED_BY_PROVISION = "provision"
USAGE_SEGMENT_OPENED_BY_RESUME = "resume"
USAGE_SEGMENT_OPENED_BY_WEBHOOK_RESUMED = "webhook_resumed"
USAGE_SEGMENT_OPENED_BY_RECONCILER_REPAIR = "reconciler_repair"
USAGE_SEGMENT_OPENED_BY_VALUES: frozenset[str] = frozenset(
    {
        USAGE_SEGMENT_OPENED_BY_PROVISION,
        USAGE_SEGMENT_OPENED_BY_RESUME,
        USAGE_SEGMENT_OPENED_BY_WEBHOOK_RESUMED,
        USAGE_SEGMENT_OPENED_BY_RECONCILER_REPAIR,
    }
)

USAGE_SEGMENT_CLOSED_BY_MANUAL_STOP = "manual_stop"
USAGE_SEGMENT_CLOSED_BY_DESTROY = "destroy"
USAGE_SEGMENT_CLOSED_BY_WEBHOOK_PAUSED = "webhook_paused"
USAGE_SEGMENT_CLOSED_BY_WEBHOOK_KILLED = "webhook_killed"
USAGE_SEGMENT_CLOSED_BY_RECONCILER = "reconciler"
USAGE_SEGMENT_CLOSED_BY_PROVISION_FAILURE = "provision_failure"
USAGE_SEGMENT_CLOSED_BY_QUOTA_ENFORCEMENT = "quota_enforcement"
USAGE_SEGMENT_CLOSED_BY_VALUES: frozenset[str] = frozenset(
    {
        USAGE_SEGMENT_CLOSED_BY_MANUAL_STOP,
        USAGE_SEGMENT_CLOSED_BY_DESTROY,
        USAGE_SEGMENT_CLOSED_BY_WEBHOOK_PAUSED,
        USAGE_SEGMENT_CLOSED_BY_WEBHOOK_KILLED,
        USAGE_SEGMENT_CLOSED_BY_RECONCILER,
        USAGE_SEGMENT_CLOSED_BY_PROVISION_FAILURE,
        USAGE_SEGMENT_CLOSED_BY_QUOTA_ENFORCEMENT,
    }
)

PROVIDER_EVENT_KIND_CREATED = "created"
PROVIDER_EVENT_KIND_RESUMED = "resumed"
PROVIDER_EVENT_KIND_PAUSED = "paused"
PROVIDER_EVENT_KIND_KILLED = "killed"
PROVIDER_EVENT_KIND_PRECEDENCE: dict[str, int] = {
    PROVIDER_EVENT_KIND_CREATED: 1,
    PROVIDER_EVENT_KIND_RESUMED: 2,
    PROVIDER_EVENT_KIND_PAUSED: 3,
    PROVIDER_EVENT_KIND_KILLED: 4,
}

WORKSPACE_ACTION_BLOCK_KIND_BILLING_QUOTA = "billing_quota"

BILLING_RECONCILE_INTERVAL_SECONDS = 900

# Single global advisory lock for the billing reconciler loop.
BILLING_RECONCILER_LOCK_KEY = 4_203_901
