"""Billing-related constants."""

FREE_INCLUDED_GRANT_TYPE = "free_included"
FREE_TRIAL_V2_GRANT_TYPE = "free_trial_v2"
MONTHLY_CLOUD_GRANT_TYPE = "cloud_monthly"
PRO_PERIOD_GRANT_TYPE = "pro_period"
PRO_SEAT_PRORATION_GRANT_TYPE = "pro_seat_proration"
REFILL_10H_GRANT_TYPE = "refill_10h"
UNLIMITED_CLOUD_ENTITLEMENT = "unlimited_cloud"

BILLING_PLAN_FREE = "free"
BILLING_PLAN_PRO = "pro"
BILLING_PLAN_LEGACY_CLOUD = "legacy_cloud"
BILLING_PRICE_CLASS_PRO = "pro"
BILLING_PRICE_CLASS_LEGACY_CLOUD = "legacy_cloud"
BILLING_PRICE_CLASS_UNKNOWN = "unknown"

PRO_SEAT_MONTHLY_AMOUNT_CENTS = 2000
PRO_INCLUDED_MANAGED_CLOUD_HOURS_PER_SEAT = 20.0
PRO_OVERAGE_PRICE_PER_HOUR_CENTS = 200
PRO_DEFAULT_OVERAGE_CAP_CENTS_PER_SEAT = 2000
PRO_ACTIVE_ENVIRONMENTS_PER_SEAT = 2
PRO_REPO_ENVIRONMENTS_PER_SEAT = 4
PRO_FREE_TRIAL_HOURS = 1.0
PRO_FREE_ACTIVE_ENVIRONMENT_LIMIT = 1
PRO_OVERAGE_CAP_CENTS_PER_SEAT_MAX = 1_000_000

BILLING_SUBJECT_KIND_PERSONAL = "personal"
BILLING_SUBJECT_KIND_ORGANIZATION = "organization"
BILLING_HOLD_KIND_PAYMENT_FAILED = "payment_failed"
BILLING_HOLD_KIND_ADMIN_HOLD = "admin_hold"
BILLING_HOLD_KIND_EXTERNAL_BILLING_HOLD = "external_billing_hold"
BILLING_HOLD_STATUS_ACTIVE = "active"

BILLING_MODE_OFF = "off"
BILLING_MODE_OBSERVE = "observe"
BILLING_MODE_ENFORCE = "enforce"
BILLING_MODES: frozenset[str] = frozenset(
    {BILLING_MODE_OFF, BILLING_MODE_OBSERVE, BILLING_MODE_ENFORCE}
)
USAGE_SEGMENT_RECENT_LOOKBACK_DAYS = 90

ACTIVE_SANDBOX_STATUSES: frozenset[str] = frozenset({"allocating", "provisioning", "running"})

USAGE_SEGMENT_OPENED_BY_PROVISION = "provision"
USAGE_SEGMENT_OPENED_BY_RESUME = "resume"
USAGE_SEGMENT_OPENED_BY_WEBHOOK_RESUMED = "webhook_resumed"
USAGE_SEGMENT_OPENED_BY_RECONCILER_REPAIR = "reconciler_repair"
USAGE_SEGMENT_OPENED_BY_VALUES: frozenset[str] = frozenset(
    {
        USAGE_SEGMENT_OPENED_BY_PROVISION,
        USAGE_SEGMENT_OPENED_BY_RESUME,
        USAGE_SEGMENT_OPENED_BY_WEBHOOK_RESUMED,
        USAGE_SEGMENT_OPENED_BY_RECONCILER_REPAIR,
    }
)

USAGE_SEGMENT_CLOSED_BY_MANUAL_STOP = "manual_stop"
USAGE_SEGMENT_CLOSED_BY_DESTROY = "destroy"
USAGE_SEGMENT_CLOSED_BY_WEBHOOK_PAUSED = "webhook_paused"
USAGE_SEGMENT_CLOSED_BY_WEBHOOK_KILLED = "webhook_killed"
USAGE_SEGMENT_CLOSED_BY_RECONCILER = "reconciler"
USAGE_SEGMENT_CLOSED_BY_PROVISION_FAILURE = "provision_failure"
USAGE_SEGMENT_CLOSED_BY_QUOTA_ENFORCEMENT = "quota_enforcement"
USAGE_SEGMENT_CLOSED_BY_VALUES: frozenset[str] = frozenset(
    {
        USAGE_SEGMENT_CLOSED_BY_MANUAL_STOP,
        USAGE_SEGMENT_CLOSED_BY_DESTROY,
        USAGE_SEGMENT_CLOSED_BY_WEBHOOK_PAUSED,
        USAGE_SEGMENT_CLOSED_BY_WEBHOOK_KILLED,
        USAGE_SEGMENT_CLOSED_BY_RECONCILER,
        USAGE_SEGMENT_CLOSED_BY_PROVISION_FAILURE,
        USAGE_SEGMENT_CLOSED_BY_QUOTA_ENFORCEMENT,
    }
)

PROVIDER_EVENT_KIND_CREATED = "created"
PROVIDER_EVENT_KIND_RESUMED = "resumed"
PROVIDER_EVENT_KIND_PAUSED = "paused"
PROVIDER_EVENT_KIND_KILLED = "killed"
PROVIDER_EVENT_KIND_PRECEDENCE: dict[str, int] = {
    PROVIDER_EVENT_KIND_CREATED: 1,
    PROVIDER_EVENT_KIND_RESUMED: 2,
    PROVIDER_EVENT_KIND_PAUSED: 3,
    PROVIDER_EVENT_KIND_KILLED: 4,
}

WORKSPACE_ACTION_BLOCK_KIND_BILLING_QUOTA = "billing_quota"
WORKSPACE_ACTION_BLOCK_KIND_CONCURRENCY_LIMIT = "concurrency_limit"
WORKSPACE_ACTION_BLOCK_KIND_CREDITS_EXHAUSTED = "credits_exhausted"
WORKSPACE_ACTION_BLOCK_KIND_OVERAGE_DISABLED = "overage_disabled"
WORKSPACE_ACTION_BLOCK_KIND_CAP_EXHAUSTED = "cap_exhausted"
WORKSPACE_ACTION_BLOCK_KIND_PAYMENT_FAILED = "payment_failed"
WORKSPACE_ACTION_BLOCK_KIND_ADMIN_HOLD = "admin_hold"
WORKSPACE_ACTION_BLOCK_KIND_EXTERNAL_BILLING_HOLD = "external_billing_hold"

BILLING_DECISION_AUTHORIZE_START = "authorize_start"
BILLING_DECISION_ENFORCE_ACTIVE_SPEND = "enforce_active_spend"
BILLING_DECISION_OVERAGE_EXPORT = "overage_export"

BILLING_USAGE_EXPORT_STATUS_PENDING = "pending"
BILLING_USAGE_EXPORT_STATUS_OBSERVED = "observed"
BILLING_USAGE_EXPORT_STATUS_SENDING = "sending"
BILLING_USAGE_EXPORT_STATUS_SUCCEEDED = "succeeded"
BILLING_USAGE_EXPORT_STATUS_FAILED_RETRYABLE = "failed_retryable"
BILLING_USAGE_EXPORT_STATUS_FAILED_TERMINAL = "failed_terminal"
BILLING_USAGE_EXPORT_STATUS_WRITTEN_OFF = "written_off"

BILLING_RECONCILE_INTERVAL_SECONDS = 900
BILLING_SEAT_ADJUSTMENT_MAX_ATTEMPTS = 3

# Single global advisory lock for the billing reconciler loop.
BILLING_RECONCILER_LOCK_KEY = 4_203_901
