"""Organization-domain constants."""

ORGANIZATION_ROLE_OWNER = "owner"
ORGANIZATION_ROLE_ADMIN = "admin"
ORGANIZATION_ROLE_MEMBER = "member"
ORGANIZATION_ROLES: frozenset[str] = frozenset(
    {
        ORGANIZATION_ROLE_OWNER,
        ORGANIZATION_ROLE_ADMIN,
        ORGANIZATION_ROLE_MEMBER,
    }
)

ORGANIZATION_MEMBERSHIP_STATUS_ACTIVE = "active"
ORGANIZATION_MEMBERSHIP_STATUS_REMOVED = "removed"
ORGANIZATION_MEMBERSHIP_STATUSES: frozenset[str] = frozenset(
    {
        ORGANIZATION_MEMBERSHIP_STATUS_ACTIVE,
        ORGANIZATION_MEMBERSHIP_STATUS_REMOVED,
    }
)

ORGANIZATION_STATUS_PENDING_CHECKOUT = "pending_checkout"
ORGANIZATION_STATUS_ACTIVE = "active"
ORGANIZATION_STATUS_SUSPENDED = "suspended"
ORGANIZATION_STATUS_ARCHIVED = "archived"
ORGANIZATION_STATUSES: frozenset[str] = frozenset(
    {
        ORGANIZATION_STATUS_PENDING_CHECKOUT,
        ORGANIZATION_STATUS_ACTIVE,
        ORGANIZATION_STATUS_SUSPENDED,
        ORGANIZATION_STATUS_ARCHIVED,
    }
)
ORGANIZATION_CURRENT_STATUSES: frozenset[str] = frozenset(
    {
        ORGANIZATION_STATUS_ACTIVE,
        ORGANIZATION_STATUS_SUSPENDED,
    }
)

ORGANIZATION_CHECKOUT_INTENT_STATUS_PENDING = "pending"
ORGANIZATION_CHECKOUT_INTENT_STATUS_COMPLETED = "completed"
ORGANIZATION_CHECKOUT_INTENT_STATUS_EXPIRED = "expired"
ORGANIZATION_CHECKOUT_INTENT_STATUS_CANCELLED = "cancelled"
ORGANIZATION_CHECKOUT_INTENT_STATUS_FAILED = "failed"
ORGANIZATION_CHECKOUT_INTENT_STATUSES: frozenset[str] = frozenset(
    {
        ORGANIZATION_CHECKOUT_INTENT_STATUS_PENDING,
        ORGANIZATION_CHECKOUT_INTENT_STATUS_COMPLETED,
        ORGANIZATION_CHECKOUT_INTENT_STATUS_EXPIRED,
        ORGANIZATION_CHECKOUT_INTENT_STATUS_CANCELLED,
        ORGANIZATION_CHECKOUT_INTENT_STATUS_FAILED,
    }
)
ORGANIZATION_CHECKOUT_INTENT_NON_TERMINAL_STATUSES: frozenset[str] = frozenset(
    {
        ORGANIZATION_CHECKOUT_INTENT_STATUS_PENDING,
    }
)

ORGANIZATION_CHECKOUT_ACTIVATION_NOT_STARTED = "not_started"
ORGANIZATION_CHECKOUT_ACTIVATION_ACTIVATING = "activating"
ORGANIZATION_CHECKOUT_ACTIVATION_ACTIVATED = "activated"
ORGANIZATION_CHECKOUT_ACTIVATION_FAILED_BUSINESS_STATE = "failed_business_state"
ORGANIZATION_CHECKOUT_ACTIVATION_FAILED_BILLING_STATE = "failed_billing_state"
ORGANIZATION_CHECKOUT_ACTIVATION_FAILED_INTERNAL = "failed_internal"
ORGANIZATION_CHECKOUT_ACTIVATION_STATUSES: frozenset[str] = frozenset(
    {
        ORGANIZATION_CHECKOUT_ACTIVATION_NOT_STARTED,
        ORGANIZATION_CHECKOUT_ACTIVATION_ACTIVATING,
        ORGANIZATION_CHECKOUT_ACTIVATION_ACTIVATED,
        ORGANIZATION_CHECKOUT_ACTIVATION_FAILED_BUSINESS_STATE,
        ORGANIZATION_CHECKOUT_ACTIVATION_FAILED_BILLING_STATE,
        ORGANIZATION_CHECKOUT_ACTIVATION_FAILED_INTERNAL,
    }
)

ORGANIZATION_INVITATION_STATUS_PENDING = "pending"
ORGANIZATION_INVITATION_STATUS_ACCEPTED = "accepted"
ORGANIZATION_INVITATION_STATUS_REVOKED = "revoked"
ORGANIZATION_INVITATION_STATUS_EXPIRED = "expired"
ORGANIZATION_INVITATION_STATUSES: frozenset[str] = frozenset(
    {
        ORGANIZATION_INVITATION_STATUS_PENDING,
        ORGANIZATION_INVITATION_STATUS_ACCEPTED,
        ORGANIZATION_INVITATION_STATUS_REVOKED,
        ORGANIZATION_INVITATION_STATUS_EXPIRED,
    }
)

ORGANIZATION_INVITATION_DELIVERY_PENDING = "pending"
ORGANIZATION_INVITATION_DELIVERY_SENT = "sent"
ORGANIZATION_INVITATION_DELIVERY_FAILED = "failed"
ORGANIZATION_INVITATION_DELIVERY_SKIPPED = "skipped"
ORGANIZATION_INVITATION_DELIVERY_STATUSES: frozenset[str] = frozenset(
    {
        ORGANIZATION_INVITATION_DELIVERY_PENDING,
        ORGANIZATION_INVITATION_DELIVERY_SENT,
        ORGANIZATION_INVITATION_DELIVERY_FAILED,
        ORGANIZATION_INVITATION_DELIVERY_SKIPPED,
    }
)

ORGANIZATION_INVITE_EXPIRES_DAYS = 14
ORGANIZATION_NAME_MAX_LENGTH = 255
ORGANIZATION_LOGO_IMAGE_MAX_BYTES = 256 * 1024
ORGANIZATION_LOGO_IMAGE_MIME_TYPES: frozenset[str] = frozenset(
    {
        "image/gif",
        "image/jpeg",
        "image/png",
        "image/webp",
    }
)

PUBLIC_EMAIL_DOMAINS: frozenset[str] = frozenset(
    {
        "aol.com",
        "fastmail.com",
        "gmail.com",
        "googlemail.com",
        "hotmail.com",
        "icloud.com",
        "live.com",
        "me.com",
        "msn.com",
        "outlook.com",
        "pm.me",
        "proton.me",
        "protonmail.com",
        "yahoo.com",
    }
)
