"""Shared constants for the Slack bot integration."""

from __future__ import annotations

from typing import Final

SLACK_CONNECTION_STATUS_ACTIVE: Final = "active"
SLACK_CONNECTION_STATUS_REAUTH_REQUIRED: Final = "reauth_required"
SLACK_CONNECTION_STATUS_REVOKED: Final = "revoked"
SUPPORTED_SLACK_CONNECTION_STATUSES: Final = frozenset(
    {
        SLACK_CONNECTION_STATUS_ACTIVE,
        SLACK_CONNECTION_STATUS_REAUTH_REQUIRED,
        SLACK_CONNECTION_STATUS_REVOKED,
    }
)

SLACK_REPO_MODE_FIXED: Final = "fixed"
SLACK_REPO_MODE_AUTO: Final = "auto"
SUPPORTED_SLACK_REPO_MODES: Final = frozenset({SLACK_REPO_MODE_FIXED, SLACK_REPO_MODE_AUTO})

SLACK_THREAD_WORK_STATUS_ACTIVE: Final = "active"
SLACK_THREAD_WORK_STATUS_ARCHIVED: Final = "archived"
SUPPORTED_SLACK_THREAD_WORK_STATUSES: Final = frozenset(
    {SLACK_THREAD_WORK_STATUS_ACTIVE, SLACK_THREAD_WORK_STATUS_ARCHIVED}
)

SLACK_INBOUND_JOB_STATUS_QUEUED: Final = "queued"
SLACK_INBOUND_JOB_STATUS_PROCESSING: Final = "processing"
SLACK_INBOUND_JOB_STATUS_COMPLETED: Final = "completed"
SLACK_INBOUND_JOB_STATUS_FAILED: Final = "failed"
SUPPORTED_SLACK_INBOUND_JOB_STATUSES: Final = frozenset(
    {
        SLACK_INBOUND_JOB_STATUS_QUEUED,
        SLACK_INBOUND_JOB_STATUS_PROCESSING,
        SLACK_INBOUND_JOB_STATUS_COMPLETED,
        SLACK_INBOUND_JOB_STATUS_FAILED,
    }
)

SLACK_OUTBOUND_STATUS_QUEUED: Final = "queued"
SLACK_OUTBOUND_STATUS_SENDING: Final = "sending"
SLACK_OUTBOUND_STATUS_SENT: Final = "sent"
SLACK_OUTBOUND_STATUS_FAILED: Final = "failed"
SLACK_OUTBOUND_STATUS_DROPPED: Final = "dropped"
SUPPORTED_SLACK_OUTBOUND_STATUSES: Final = frozenset(
    {
        SLACK_OUTBOUND_STATUS_QUEUED,
        SLACK_OUTBOUND_STATUS_SENDING,
        SLACK_OUTBOUND_STATUS_SENT,
        SLACK_OUTBOUND_STATUS_FAILED,
        SLACK_OUTBOUND_STATUS_DROPPED,
    }
)

SLACK_OUTBOUND_SOURCE_ACK: Final = "ack"
SLACK_OUTBOUND_SOURCE_TURN: Final = "turn"
SLACK_OUTBOUND_SOURCE_INTERACTION: Final = "interaction"
SLACK_OUTBOUND_SOURCE_DONE: Final = "done"
SLACK_OUTBOUND_SOURCE_FAILED: Final = "failed"
SLACK_OUTBOUND_SOURCE_ADMIN: Final = "admin"
SUPPORTED_SLACK_OUTBOUND_SOURCES: Final = frozenset(
    {
        SLACK_OUTBOUND_SOURCE_ACK,
        SLACK_OUTBOUND_SOURCE_TURN,
        SLACK_OUTBOUND_SOURCE_INTERACTION,
        SLACK_OUTBOUND_SOURCE_DONE,
        SLACK_OUTBOUND_SOURCE_FAILED,
        SLACK_OUTBOUND_SOURCE_ADMIN,
    }
)

SLACK_SIGNATURE_TIMESTAMP_TOLERANCE_SECONDS: Final = 300
SLACK_EVENT_DEDUPE_RETENTION_DAYS: Final = 7
