use std::path::Path;
use std::process::Command;

use super::types::{DetectedHintCategory, DetectedSetupHint, ProjectSetupDetectionResult};

/// Detect project setup hints for a workspace root.
///
/// Returns build-tool install commands and gitignored secret/config files that
/// should be copied into new worktrees. All checks are cheap: `Path::exists()`
/// stat calls, one optional small JSON parse, and one `git ls-files` subprocess.
pub fn detect_project_setup(workspace_root: &Path) -> ProjectSetupDetectionResult {
    let mut hints = Vec::new();

    detect_build_tools(workspace_root, &mut hints);
    detect_ignored_secret_files(workspace_root, &mut hints);

    ProjectSetupDetectionResult { hints }
}

// ---------------------------------------------------------------------------
// Build-tool detection — multi-match, one hint per ecosystem
// ---------------------------------------------------------------------------

fn detect_build_tools(root: &Path, hints: &mut Vec<DetectedSetupHint>) {
    // Rust
    if root.join("Cargo.toml").exists() {
        hints.push(build_hint(
            "rust",
            "Rust project",
            "cargo build",
            "Cargo.toml",
        ));
    }

    // Node — 3-tier disambiguation following Railpack patterns
    if root.join("package.json").exists() {
        let cmd = resolve_node_install_command(root);
        hints.push(build_hint("node", "Node.js project", &cmd, "package.json"));
    }

    // Python — mutually exclusive within ecosystem
    if root.join("pyproject.toml").exists() {
        let cmd = if root.join("uv.lock").exists() {
            "uv sync"
        } else if root.join("poetry.lock").exists() {
            "poetry install"
        } else if root.join("pdm.lock").exists() {
            "pdm install"
        } else {
            "uv sync"
        };
        hints.push(build_hint(
            "python",
            "Python project",
            cmd,
            "pyproject.toml",
        ));
    } else if root.join("requirements.txt").exists() {
        hints.push(build_hint(
            "python",
            "Python project",
            "pip install -r requirements.txt",
            "requirements.txt",
        ));
    } else if root.join("Pipfile").exists() {
        hints.push(build_hint(
            "python",
            "Python project",
            "pipenv install",
            "Pipfile",
        ));
    }

    // Go
    if root.join("go.mod").exists() {
        hints.push(build_hint("go", "Go project", "go mod download", "go.mod"));
    }

    // Ruby
    if root.join("Gemfile").exists() {
        hints.push(build_hint(
            "ruby",
            "Ruby project",
            "bundle install",
            "Gemfile",
        ));
    }

    // Elixir
    if root.join("mix.exs").exists() {
        hints.push(build_hint(
            "elixir",
            "Elixir project",
            "mix deps.get",
            "mix.exs",
        ));
    }
}

fn build_hint(id: &str, label: &str, command: &str, file: &str) -> DetectedSetupHint {
    DetectedSetupHint {
        id: id.to_string(),
        label: label.to_string(),
        suggested_command: command.to_string(),
        detected_file: file.to_string(),
        category: DetectedHintCategory::BuildTool,
    }
}

// ---------------------------------------------------------------------------
// Node package manager disambiguation (Railpack 3-tier pattern)
// ---------------------------------------------------------------------------

fn resolve_node_install_command(root: &Path) -> String {
    // Tier 1: packageManager field in package.json
    if let Some(cmd) = read_package_manager_field(root) {
        return cmd;
    }

    // Tier 2: lockfile presence
    if root.join("pnpm-lock.yaml").exists() {
        return "pnpm install".into();
    }
    if root.join("bun.lockb").exists() || root.join("bun.lock").exists() {
        return "bun install".into();
    }
    if root.join("yarn.lock").exists() {
        return "yarn install".into();
    }

    // Tier 3: fallback
    "npm install".into()
}

fn read_package_manager_field(root: &Path) -> Option<String> {
    let content = std::fs::read_to_string(root.join("package.json")).ok()?;
    let parsed: serde_json::Value = serde_json::from_str(&content).ok()?;
    let pm_field = parsed.get("packageManager")?.as_str()?;
    let pm_name = pm_field.split('@').next()?;
    match pm_name {
        "pnpm" => Some("pnpm install".into()),
        "yarn" => Some("yarn install".into()),
        "bun" => Some("bun install".into()),
        "npm" => Some("npm install".into()),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Secret / ignored-file detection via git ls-files
// ---------------------------------------------------------------------------

/// Directories that contain build artifacts or caches — files here should be
/// regenerated by the build tool, not copied between worktrees.
const DOMINATED_DIRS: &[&str] = &[
    "node_modules",
    "target",
    "dist",
    "build",
    "__pycache__",
    ".venv",
    "venv",
    ".next",
    ".turbo",
    ".pytest_cache",
    ".mypy_cache",
    "vendor",
    ".git",
    ".tox",
    ".eggs",
    ".cargo",
    ".gradle",
    "coverage",
    ".parcel-cache",
];

fn detect_ignored_secret_files(root: &Path, hints: &mut Vec<DetectedSetupHint>) {
    let output = match Command::new("git")
        .args(["ls-files", "--others", "--ignored", "--exclude-standard"])
        .current_dir(root)
        .output()
    {
        Ok(output) if output.status.success() => output,
        _ => return,
    };

    let stdout = String::from_utf8_lossy(&output.stdout);

    for line in stdout.lines() {
        let file = line.trim();
        if file.is_empty() {
            continue;
        }

        // Skip files nested more than 1 level deep
        if file.matches('/').count() > 1 {
            continue;
        }

        // Skip files under dominated directories
        let top_component = file.split('/').next().unwrap_or(file);
        if DOMINATED_DIRS.contains(&top_component) {
            continue;
        }

        if !is_likely_secret_or_config(file) {
            continue;
        }

        let name = file.rsplit('/').next().unwrap_or(file);
        hints.push(DetectedSetupHint {
            id: format!("sync-{}", file.replace('/', "-")),
            label: name.to_string(),
            suggested_command: format!(
                "cp \"$PROLIFERATE_REPO_DIR/{file}\" \"$PROLIFERATE_WORKTREE_DIR/{file}\""
            ),
            detected_file: file.to_string(),
            category: DetectedHintCategory::SecretSync,
        });
    }
}

fn is_likely_secret_or_config(filename: &str) -> bool {
    let name = filename.rsplit('/').next().unwrap_or(filename);

    // .env family (but not .env.example / .env.sample / .env.template)
    if name.starts_with(".env") {
        return !name.ends_with(".example")
            && !name.ends_with(".sample")
            && !name.ends_with(".template");
    }

    // Known credential files
    if matches!(name, ".npmrc" | ".pypirc" | ".netrc" | ".vault-token") {
        return true;
    }

    // Key / cert files
    if name.ends_with(".pem") || name.ends_with(".key") || name.ends_with(".p12") {
        return true;
    }

    // Service account / credential JSON
    if name.contains("credential") || name.contains("serviceAccount") {
        return true;
    }

    // Local config overrides
    if name.contains("secret") {
        return true;
    }
    if name.ends_with("local.yml")
        || name.ends_with("local.yaml")
        || name.ends_with("local.toml")
        || name.ends_with("local.json")
    {
        return true;
    }

    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_likely_secret_or_config() {
        assert!(is_likely_secret_or_config(".env"));
        assert!(is_likely_secret_or_config(".env.local"));
        assert!(is_likely_secret_or_config(".env.development.local"));
        assert!(!is_likely_secret_or_config(".env.example"));
        assert!(!is_likely_secret_or_config(".env.sample"));
        assert!(!is_likely_secret_or_config(".env.template"));
        assert!(is_likely_secret_or_config(".npmrc"));
        assert!(is_likely_secret_or_config("server.key"));
        assert!(is_likely_secret_or_config("serviceAccountKey.json"));
        assert!(is_likely_secret_or_config("config/secrets.yml"));
        assert!(is_likely_secret_or_config("config/local.yml"));
        assert!(!is_likely_secret_or_config("README.md"));
        assert!(!is_likely_secret_or_config("package.json"));
    }

    #[test]
    fn test_resolve_node_fallback() {
        // With no real filesystem, this should fall through to npm
        let tmp = std::env::temp_dir().join("detector_test_empty");
        let _ = std::fs::create_dir_all(&tmp);
        assert_eq!(resolve_node_install_command(&tmp), "npm install");
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn test_build_hint_category() {
        let hint = build_hint("rust", "Rust project", "cargo build", "Cargo.toml");
        assert_eq!(hint.category, DetectedHintCategory::BuildTool);
        assert_eq!(hint.id, "rust");
    }
}
