import type { components } from "../generated/openapi.js";

export type AgentInstallState = components["schemas"]["AgentInstallState"];
export type AgentCredentialState = components["schemas"]["AgentCredentialState"];
export type AgentCliAuthState = components["schemas"]["AgentCliAuthState"];
export type AgentReadinessState = components["schemas"]["AgentReadinessState"];
export type ArtifactStatus = components["schemas"]["ArtifactStatus"];
export type AgentSummary = components["schemas"]["AgentSummary"];
// Kept alongside the hand-written SDK client until the Rust OpenAPI export can
// be regenerated by the owning build in CI. The wire shape is owned by
// anyharness-contract::v1::agents and covered by its OpenAPI schema test.
export interface HarnessLaunchModel {
  id: string;
  observedName: string | null;
  observedDescription: string | null;
}
export interface HarnessLaunchControlValue {
  value: string;
  observedLabel: string | null;
  observedDescription: string | null;
}
export interface HarnessLaunchControl {
  id: string;
  observedLabel: string | null;
  observedDescription: string | null;
  values: HarnessLaunchControlValue[];
}
export interface HarnessLaunchModelControls {
  modelId: string;
  controls: HarnessLaunchControl[];
  defaultControlValues: Record<string, string>;
}
export interface HarnessLaunchDefaults {
  modelId: string | null;
  controlValues: Record<string, string>;
}
export interface HarnessLaunchOptions {
  models: HarnessLaunchModel[];
  controls: HarnessLaunchControl[];
  defaults: HarnessLaunchDefaults;
  modelControls?: HarnessLaunchModelControls[];
}
export type HarnessLaunchOptionsState =
  | "detecting"
  | "refreshing"
  | "observed"
  | "observed_empty"
  | "last_good_after_failure"
  | "failed_without_observation";
/**
 * The launch-probe scheduler's live phase for a harness — the same lifecycle
 * the agent-auth summary reports.
 */
export type AgentAuthProbePhase = components["schemas"]["AgentAuthProbePhase"];
export interface HarnessLaunchOptionsResponse {
  harnessKind: string;
  basisRevision: string;
  revision: number;
  state: HarnessLaunchOptionsState;
  options: HarnessLaunchOptions | null;
  observedAt: string | null;
  probeAttemptedAt: string;
  probeFailureCode: string | null;
  readiness: AgentReadinessState;
  /**
   * Absent when the runtime that served this response cannot know the phase.
   * `detecting` on its own cannot tell a probe that is running apart from one
   * that will never run.
   */
  probePhase?: AgentAuthProbePhase;
}
export type InstallAgentRequest = components["schemas"]["InstallAgentRequest"];
export type InstallAgentResponse = components["schemas"]["InstallAgentResponse"];
export type LoginCommand = components["schemas"]["LoginCommand"];
export type StartAgentLoginResponse = components["schemas"]["StartAgentLoginResponse"];
export type AgentLoginTerminalStatus = components["schemas"]["AgentLoginTerminalStatus"];
export type AgentLoginTerminalRecord = components["schemas"]["AgentLoginTerminalRecord"];
export type StartAgentLoginTerminalResponse =
  components["schemas"]["StartAgentLoginTerminalResponse"];
export type ReconcileOutcome = components["schemas"]["ReconcileOutcome"];
export type ReconcileJobStatus = components["schemas"]["ReconcileJobStatus"];
export type AgentInstallProgressPhase =
  components["schemas"]["AgentInstallProgressPhase"];
export type AgentInstallProgressComponent =
  components["schemas"]["AgentInstallProgressComponent"];
export type AgentInstallProgress = components["schemas"]["AgentInstallProgress"];
export type ReconcileAgentsRequest = components["schemas"]["ReconcileAgentsRequest"];
export type ReconcileAgentResult = components["schemas"]["ReconcileAgentResult"];
export type ReconcileAgentsResponse = components["schemas"]["ReconcileAgentsResponse"];
