"""Agent gateway (LiteLLM-era agent auth) stores."""

from proliferate.db.store.agent_gateway.api_keys import (
    build_redacted_hint,
    create_agent_api_key,
    get_agent_api_key_decrypted,
    list_agent_api_keys,
    revoke_agent_api_key,
)
from proliferate.db.store.agent_gateway.catalog import (
    create_catalog_snapshot,
    delete_catalog_override,
    get_catalog_override,
    get_latest_catalog_snapshot,
    upsert_catalog_override,
)
from proliferate.db.store.agent_gateway.credits import (
    count_topup_grants,
    create_llm_credit_grant,
    get_remaining_credit_usd,
    sum_active_grants_usd,
    sum_usage_cost_usd,
)
from proliferate.db.store.agent_gateway.enrollments import (
    ensure_enrollment_row,
    get_enrollment_by_virtual_key_id,
    get_enrollment_for_organization,
    get_enrollment_for_user,
    get_enrollment_virtual_key_decrypted,
    list_active_enrollments_for_subject,
    list_billing_subject_ids_with_active_enrollments,
    list_enrollments_needing_sync,
    list_org_memberships_missing_enrollment,
    list_user_ids_missing_enrollment,
    mark_enrollment_failed,
    mark_enrollment_synced,
    revoke_enrollment,
    set_enrollment_budget_status,
)
from proliferate.db.store.agent_gateway.policy import (
    get_org_agent_policy,
    set_org_agent_policy,
)
from proliferate.db.store.agent_gateway.records import (
    AgentApiKeyRecord,
    AgentAuthRouteSelectionRecord,
    AgentCatalogOverrideRecord,
    AgentCatalogSnapshotRecord,
    AgentGatewayEnrollmentRecord,
    AgentLlmUsageImportCursorRecord,
    LlmCreditBalanceRecord,
    LlmCreditGrantRecord,
    OrgAgentPolicyRecord,
)
from proliferate.db.store.agent_gateway.route_selections import (
    delete_route_selection,
    get_route_selection,
    list_route_selections,
    upsert_route_selection,
    validate_route_selection,
)
from proliferate.db.store.agent_gateway.usage import (
    advance_usage_import_cursor,
    get_usage_import_cursor,
    insert_usage_event_once,
)

__all__ = [
    "AgentApiKeyRecord",
    "AgentAuthRouteSelectionRecord",
    "AgentCatalogOverrideRecord",
    "AgentCatalogSnapshotRecord",
    "AgentGatewayEnrollmentRecord",
    "AgentLlmUsageImportCursorRecord",
    "LlmCreditBalanceRecord",
    "LlmCreditGrantRecord",
    "OrgAgentPolicyRecord",
    "advance_usage_import_cursor",
    "build_redacted_hint",
    "count_topup_grants",
    "create_agent_api_key",
    "create_catalog_snapshot",
    "create_llm_credit_grant",
    "delete_catalog_override",
    "delete_route_selection",
    "ensure_enrollment_row",
    "get_agent_api_key_decrypted",
    "get_catalog_override",
    "get_enrollment_by_virtual_key_id",
    "get_enrollment_for_organization",
    "get_enrollment_for_user",
    "get_enrollment_virtual_key_decrypted",
    "get_latest_catalog_snapshot",
    "get_org_agent_policy",
    "get_remaining_credit_usd",
    "get_route_selection",
    "get_usage_import_cursor",
    "insert_usage_event_once",
    "list_active_enrollments_for_subject",
    "list_agent_api_keys",
    "list_billing_subject_ids_with_active_enrollments",
    "list_enrollments_needing_sync",
    "list_org_memberships_missing_enrollment",
    "list_route_selections",
    "list_user_ids_missing_enrollment",
    "mark_enrollment_failed",
    "mark_enrollment_synced",
    "revoke_agent_api_key",
    "revoke_enrollment",
    "set_enrollment_budget_status",
    "set_org_agent_policy",
    "sum_active_grants_usd",
    "sum_usage_cost_usd",
    "upsert_catalog_override",
    "upsert_route_selection",
    "validate_route_selection",
]
