"""Agent gateway (LiteLLM-era agent auth) stores."""

from proliferate.db.store.agent_gateway.api_keys import (
    build_redacted_hint,
    create_agent_api_key,
    create_agent_provider_config,
    create_agent_seat,
    get_agent_api_key_decrypted,
    get_agent_provider_config_decrypted,
    get_agent_seat_decrypted,
    get_agent_seat_decrypted_for_probe,
    list_active_agent_seats,
    list_agent_api_keys,
    list_agent_seats_decrypted,
    revoke_agent_api_key,
)
from proliferate.db.store.agent_gateway.credits import (
    count_topup_grants,
    create_llm_credit_grant,
    get_remaining_credit_usd,
    move_llm_credit_ledger,
    sum_active_grants_usd,
    sum_usage_cost_usd,
)
from proliferate.db.store.agent_gateway.delivery_acks import (
    get_delivery_ack,
    record_delivery_ack,
)
from proliferate.db.store.agent_gateway.enrollment_keys import (
    get_active_enrollment_key,
    get_enrollment_key_by_virtual_key_id,
    get_enrollment_key_virtual_key_decrypted,
    list_active_enrollment_keys,
    list_all_active_enrollment_keys,
    record_enrollment_key_verification,
    revoke_enrollment_keys,
    upsert_enrollment_key,
)
from proliferate.db.store.agent_gateway.enrollments import (
    ensure_enrollment_row,
    get_enrollment_by_id,
    get_enrollment_by_virtual_key_id,
    get_enrollment_for_organization,
    get_enrollment_virtual_key_decrypted,
    list_active_enrollments_for_subject,
    list_active_personal_enrollments,
    list_billing_subject_ids_with_active_enrollments,
    list_enrollments_needing_sync,
    list_org_memberships_missing_enrollment,
    list_organizations_with_limit_reached_enrollments,
    list_stale_identity_org_enrollments,
    mark_enrollment_failed,
    mark_enrollment_pending,
    mark_enrollment_synced,
    revoke_enrollment,
    set_enrollment_budget_status,
)
from proliferate.db.store.agent_gateway.harness_settings import (
    get_harness_settings,
    list_harness_settings_for_surface,
    put_harness_settings,
)
from proliferate.db.store.agent_gateway.policy import (
    OrgMemberRouteSelectionRecord,
    get_org_agent_policy,
    list_org_member_route_selections,
    set_org_agent_policy,
)
from proliferate.db.store.agent_gateway.records import (
    AgentApiKeyRecord,
    AgentAuthDeliveryAckRecord,
    AgentAuthSelectionRecord,
    AgentGatewayEnrollmentKeyRecord,
    AgentGatewayEnrollmentRecord,
    AgentLlmUsageImportCursorRecord,
    DesiredAuthSource,
    LlmCreditBalanceRecord,
    LlmCreditGrantRecord,
    OrgAgentPolicyRecord,
)

# Deliberately NOT re-exported here: the seat_usage store and its record
# (advisory-only, agent_auth spec flow 5). The launch/render path imports
# this package as `agent_gateway_store`; keeping the sample surface out of
# the package namespace means that alias can never reach it. Importers go to
# `.seat_usage` / `.records` directly and are pinned by the import-scan test.
from proliferate.db.store.agent_gateway.selections import (
    AgentApiKeyNotUsableError,
    AgentProviderConfigNotSupportedError,
    clear_auth_selections,
    get_scope_auth_selections,
    list_auth_selections,
    list_enabled_auth_selections,
    list_enabled_selections_referencing_key,
    put_auth_selections,
    touch_auth_selection_revisions,
)
from proliferate.db.store.agent_gateway.usage import (
    advance_usage_import_cursor,
    get_usage_import_cursor,
    insert_usage_event_once,
    llm_cost_usd_by_user,
    llm_cost_usd_in_window,
    llm_cost_usd_timeseries,
)

__all__ = [
    "AgentApiKeyNotUsableError",
    "AgentProviderConfigNotSupportedError",
    "AgentApiKeyRecord",
    "AgentAuthDeliveryAckRecord",
    "AgentAuthSelectionRecord",
    "AgentGatewayEnrollmentKeyRecord",
    "AgentGatewayEnrollmentRecord",
    "AgentLlmUsageImportCursorRecord",
    "DesiredAuthSource",
    "LlmCreditBalanceRecord",
    "LlmCreditGrantRecord",
    "OrgAgentPolicyRecord",
    "OrgMemberRouteSelectionRecord",
    "advance_usage_import_cursor",
    "build_redacted_hint",
    "clear_auth_selections",
    "count_topup_grants",
    "create_agent_api_key",
    "create_agent_provider_config",
    "create_agent_seat",
    "create_llm_credit_grant",
    "ensure_enrollment_row",
    "get_active_enrollment_key",
    "get_agent_api_key_decrypted",
    "get_agent_provider_config_decrypted",
    "get_agent_seat_decrypted",
    "get_agent_seat_decrypted_for_probe",
    "get_delivery_ack",
    "get_enrollment_by_id",
    "get_enrollment_by_virtual_key_id",
    "get_enrollment_for_organization",
    "get_enrollment_key_by_virtual_key_id",
    "get_enrollment_key_virtual_key_decrypted",
    "get_enrollment_virtual_key_decrypted",
    "get_org_agent_policy",
    "get_harness_settings",
    "get_remaining_credit_usd",
    "get_scope_auth_selections",
    "get_usage_import_cursor",
    "insert_usage_event_once",
    "list_active_enrollment_keys",
    "list_all_active_enrollment_keys",
    "record_enrollment_key_verification",
    "list_active_agent_seats",
    "list_active_enrollments_for_subject",
    "list_active_personal_enrollments",
    "list_agent_api_keys",
    "list_agent_seats_decrypted",
    "list_auth_selections",
    "list_billing_subject_ids_with_active_enrollments",
    "list_enabled_auth_selections",
    "list_enabled_selections_referencing_key",
    "list_harness_settings_for_surface",
    "list_enrollments_needing_sync",
    "list_org_member_route_selections",
    "list_org_memberships_missing_enrollment",
    "list_organizations_with_limit_reached_enrollments",
    "list_stale_identity_org_enrollments",
    "llm_cost_usd_by_user",
    "llm_cost_usd_in_window",
    "llm_cost_usd_timeseries",
    "move_llm_credit_ledger",
    "mark_enrollment_failed",
    "mark_enrollment_pending",
    "mark_enrollment_synced",
    "put_auth_selections",
    "put_harness_settings",
    "record_delivery_ack",
    "revoke_agent_api_key",
    "revoke_enrollment",
    "revoke_enrollment_keys",
    "set_enrollment_budget_status",
    "set_org_agent_policy",
    "sum_active_grants_usd",
    "sum_usage_cost_usd",
    "touch_auth_selection_revisions",
    "upsert_enrollment_key",
]
