#!/bin/sh
set -eu

operation="${1:-get}"
if [ "$operation" != "get" ]; then
  exit 0
fi

protocol=""
host=""
while IFS= read -r line; do
  [ -n "$line" ] || break
  case "$line" in
    protocol=*) protocol="${line#protocol=}" ;;
    host=*) host="${line#host=}" ;;
  esac
done

if [ "$protocol" != "https" ]; then
  exit 0
fi

case "$host" in
  github.com|www.github.com) ;;
  *) exit 0 ;;
esac

token_file="${PROLIFERATE_GIT_TOKEN_FILE:-${PROLIFERATE_GITHUB_TOKEN_FILE:-$HOME/.proliferate/git/github.com/token}}"
if [ ! -r "$token_file" ]; then
  exit 0
fi

token="$(sed -n '1p' "$token_file" | tr -d '\r\n')"
if [ -z "$token" ]; then
  exit 0
fi

printf 'username=x-access-token\n'
printf 'password=%s\n' "$token"
