import type { ShortcutDef } from "./types";

export const APP_SHORTCUTS = {
  openSettings: {
    id: "app.open-settings",
    label: "⌘,",
    nonMacLabel: "Ctrl+,",
    description: "Open settings",
    owner: "native-menu",
    match: { kind: "fixed", key: ",", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  goHome: {
    id: "app.go-home",
    label: "⌘⌥,",
    nonMacLabel: "Ctrl+Alt+,",
    description: "Go home",
    owner: "js",
    match: { kind: "fixed-code", code: "Comma", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  goPlugins: {
    id: "app.go-plugins",
    label: "⌘P",
    nonMacLabel: "Ctrl+P",
    description: "Go to integrations",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyP", meta: true, shift: false, alt: false },
    allowInInputs: false,
  },
  goAutomations: {
    id: "app.go-automations",
    label: "⌘U",
    nonMacLabel: "Ctrl+U",
    description: "Go to workflows",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyU", meta: true, shift: false, alt: false },
    allowInInputs: false,
  },
  openWebApp: {
    id: "app.open-web",
    label: "⌘⌃W",
    nonMacLabel: "Ctrl+Alt+Shift+W",
    description: "Open web app",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyW", meta: true, ctrl: true, shift: false, alt: false },
    nonMacMatch: { kind: "fixed-code", code: "KeyW", meta: true, shift: true, alt: true },
    allowInInputs: true,
  },
  openSupport: {
    id: "app.open-support",
    label: "⌘S",
    nonMacLabel: "Ctrl+S",
    description: "Open support",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyS", meta: true, shift: false, alt: false },
    allowInInputs: false,
  },
  showKeyboardShortcuts: {
    id: "app.show-keyboard-shortcuts",
    label: "⌘?",
    nonMacLabel: "Ctrl+?",
    description: "Show keyboard shortcuts",
    owner: "js",
    match: { kind: "fixed-code", code: "Slash", meta: true, shift: true, alt: false },
    allowInInputs: true,
  },
  increaseTextSize: {
    id: "app.increase-text-size",
    label: "⌘+",
    nonMacLabel: "Ctrl+Plus",
    description: "Increase text size",
    owner: "js",
    match: { kind: "fixed-code", code: "Equal", meta: true, shift: true, alt: false },
    allowInInputs: true,
  },
  increaseTextSizeEqualAlias: {
    id: "app.increase-text-size",
    label: "⌘=",
    nonMacLabel: "Ctrl+=",
    description: "Increase text size",
    owner: "js",
    match: { kind: "fixed-code", code: "Equal", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  decreaseTextSize: {
    id: "app.decrease-text-size",
    label: "⌘-",
    nonMacLabel: "Ctrl+-",
    description: "Decrease text size",
    owner: "js",
    match: { kind: "fixed-code", code: "Minus", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  selectAll: {
    id: "app.select-all",
    label: "⌘A",
    nonMacLabel: "Ctrl+A",
    description: "Select all",
    owner: "native-menu",
    match: { kind: "fixed", key: "a", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  undo: {
    id: "app.undo",
    label: "⌘Z",
    nonMacLabel: "Ctrl+Z",
    description: "Undo",
    owner: "native-menu",
    match: { kind: "fixed", key: "z", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  redo: {
    id: "app.redo",
    label: "⌘⇧Z",
    nonMacLabel: "Ctrl+Shift+Z",
    description: "Redo",
    owner: "native-menu",
    match: { kind: "fixed", key: "z", meta: true, shift: true, alt: false },
    allowInInputs: true,
  },
} as const satisfies Record<string, ShortcutDef>;
