import type { ShortcutDef } from "./types";

export const WORKSPACE_SHORTCUTS = {
  newWorktree: {
    id: "workspace.new-worktree",
    label: "⌘⌥N",
    nonMacLabel: "Ctrl+Alt+Shift+N",
    description: "New worktree workspace",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyN", meta: true, shift: false, alt: true },
    nonMacMatch: { kind: "fixed-code", code: "KeyN", meta: true, shift: true, alt: true },
    allowInInputs: true,
  },
  newLocal: {
    id: "workspace.new-local",
    label: "⌘⇧N",
    nonMacLabel: "Ctrl+Shift+N",
    description: "New local workspace",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyN", meta: true, shift: true, alt: false },
    allowInInputs: true,
  },
  newCloud: {
    id: "workspace.new-cloud",
    label: "⌘⌃N",
    nonMacLabel: "Ctrl+Alt+N",
    description: "New cloud workspace",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyN", meta: true, ctrl: true, shift: false, alt: false },
    nonMacMatch: { kind: "fixed-code", code: "KeyN", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  addRepository: {
    id: "workspace.add-repository",
    label: "⌘O",
    nonMacLabel: "Ctrl+O",
    description: "Add repository",
    owner: "js",
    match: { kind: "fixed", key: "o", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  copyWorkspacePath: {
    id: "workspace.copy-path",
    label: "⌘⇧C",
    nonMacLabel: "Ctrl+Shift+C",
    description: "Copy workspace path",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyC", meta: true, shift: true, alt: false },
    allowInInputs: true,
  },
  copyBranchName: {
    id: "workspace.copy-branch",
    label: "⌘⌥C",
    nonMacLabel: "Ctrl+Alt+C",
    description: "Copy branch name",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyC", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  previousWorkspace: {
    id: "workspace.previous-workspace",
    label: "⌘⌥↑",
    nonMacLabel: "Ctrl+Alt+↑",
    description: "Previous workspace",
    owner: "js",
    match: { kind: "fixed", key: "ArrowUp", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  nextWorkspace: {
    id: "workspace.next-workspace",
    label: "⌘⌥↓",
    nonMacLabel: "Ctrl+Alt+↓",
    description: "Next workspace",
    owner: "js",
    match: { kind: "fixed", key: "ArrowDown", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  previousTab: {
    id: "workspace.previous-tab",
    label: "⌘⇧[",
    nonMacLabel: "Ctrl+Shift+[",
    description: "Previous tab",
    owner: "js",
    match: { kind: "fixed-code", code: "BracketLeft", meta: true, shift: true, alt: false },
    allowInInputs: true,
  },
  previousTabArrow: {
    id: "workspace.previous-tab",
    label: "⌘⌥←",
    nonMacLabel: "Ctrl+Alt+←",
    description: "Previous tab",
    owner: "js",
    match: { kind: "fixed", key: "ArrowLeft", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  nextTab: {
    id: "workspace.next-tab",
    label: "⌘⇧]",
    nonMacLabel: "Ctrl+Shift+]",
    description: "Next tab",
    owner: "js",
    match: { kind: "fixed-code", code: "BracketRight", meta: true, shift: true, alt: false },
    allowInInputs: true,
  },
  nextTabArrow: {
    id: "workspace.next-tab",
    label: "⌘⌥→",
    nonMacLabel: "Ctrl+Alt+→",
    description: "Next tab",
    owner: "js",
    match: { kind: "fixed", key: "ArrowRight", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  tabByIndex: {
    id: "workspace.tab-by-index",
    label: "⌘⌥1-9",
    nonMacLabel: "Ctrl+Alt+1-9",
    description: "Jump to chat by index",
    owner: "js",
    match: { kind: "digit-code", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  // Declared before workspaceByIndex so the Settings overlay wins the ⌘1-9 overlap
  // while it is open. When Settings is closed its handler is unregistered, so dispatch
  // falls through to workspace switching.
  settingsSectionByIndex: {
    id: "settings.section-by-index",
    label: "⌘1-9",
    nonMacLabel: "Ctrl+1-9",
    description: "Switch settings section by index",
    owner: "js",
    match: { kind: "digit-key", meta: true, shift: false, alt: false },
    allowInInputs: false,
  },
  workspaceByIndex: {
    id: "workspace.by-index",
    label: "⌘1-9",
    nonMacLabel: "Ctrl+1-9",
    description: "Switch to workspace by index",
    owner: "js",
    match: { kind: "digit-key", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  newSessionTab: {
    id: "workspace.new-session-tab",
    label: "⌘T",
    nonMacLabel: "Ctrl+T",
    description: "New chat",
    owner: "native-menu",
    match: { kind: "fixed", key: "t", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  restoreTab: {
    id: "workspace.restore-tab",
    label: "⌘⇧T",
    description: "Restore closed tab",
    owner: "js",
    match: { kind: "fixed", key: "t", meta: true, shift: true, alt: false },
    allowInInputs: true,
  },
  toggleCoworkThreads: {
    id: "workspace.toggle-cowork-threads",
    label: "⌘⌥T",
    nonMacLabel: "Ctrl+Alt+T",
    description: "Toggle cowork threads",
    owner: "js",
    match: { kind: "fixed", key: "t", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  closeActiveTab: {
    id: "workspace.close-active-tab",
    label: "⌘W",
    description: "Close tab",
    owner: "native-menu",
    match: { kind: "fixed", key: "w", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  closeOtherTabs: {
    id: "workspace.close-other-tabs",
    label: "⌘⌥O",
    nonMacLabel: "Ctrl+Alt+O",
    description: "Close other tabs",
    owner: "js",
    match: { kind: "fixed", key: "o", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  closeOtherTabsShiftAlias: {
    id: "workspace.close-other-tabs",
    label: "⌘⇧O",
    nonMacLabel: "Ctrl+Shift+O",
    description: "Close other tabs",
    owner: "js",
    match: { kind: "fixed", key: "o", meta: true, shift: true, alt: false },
    allowInInputs: true,
  },
  focusChat: {
    id: "workspace.focus-chat",
    label: "⌘L",
    nonMacLabel: "Ctrl+L",
    description: "Focus chat input",
    owner: "js",
    match: { kind: "fixed", key: "l", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  openTerminal: {
    id: "workspace.open-terminal",
    label: "⌘J",
    nonMacLabel: "Ctrl+J",
    description: "Open terminal",
    owner: "js",
    match: { kind: "fixed", key: "j", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  toggleLeftSidebar: {
    id: "workspace.toggle-left-sidebar",
    label: "⌘B",
    nonMacLabel: "Ctrl+B",
    description: "Toggle left sidebar",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyB", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  toggleRightPanel: {
    id: "workspace.toggle-right-panel",
    label: "⌘⌥B",
    nonMacLabel: "Ctrl+Alt+B",
    description: "Toggle right panel",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyB", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  openCommandPalette: {
    id: "workspace.open-command-palette",
    label: "⌘K",
    nonMacLabel: "Ctrl+K",
    description: "Open command palette",
    owner: "js",
    match: { kind: "fixed", key: "k", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  findContent: {
    id: "workspace.find-content",
    label: "⌘F",
    nonMacLabel: "Ctrl+F",
    description: "Find visible content",
    owner: "js",
    match: { kind: "fixed", key: "f", meta: true, shift: false, alt: false },
    allowInInputs: true,
  },
  openWorkspaceInWeb: {
    id: "workspace.open-in-web",
    label: "⌘⌥W",
    nonMacLabel: "Ctrl+Alt+W",
    description: "Open current workspace in web",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyW", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  syncWorkspaceToWeb: {
    id: "workspace.sync-to-web",
    label: "⌘⌥S",
    nonMacLabel: "Ctrl+Alt+S",
    description: "Sync current workspace to web",
    owner: "js",
    match: { kind: "fixed-code", code: "KeyS", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
  renameSession: {
    id: "session.rename",
    label: "⌘⌥R",
    nonMacLabel: "Ctrl+Alt+R",
    description: "Rename current chat",
    owner: "js",
    match: { kind: "fixed", key: "r", meta: true, shift: false, alt: true },
    allowInInputs: true,
  },
} as const satisfies Record<string, ShortcutDef>;
