#!/usr/bin/env python3
"""Bundle all files under specs/ into one Markdown document."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPECS_ROOT = ROOT / "specs"
DEFAULT_OUTPUT = SPECS_ROOT / "generated" / "all-specs.md"
LANGUAGES = {
    ".json": "json",
    ".md": "markdown",
    ".sql": "sql",
    ".toml": "toml",
    ".yaml": "yaml",
    ".yml": "yaml",
}


def source_files(output: Path) -> list[Path]:
    excluded = output.resolve()
    return sorted(
        path
        for path in SPECS_ROOT.rglob("*")
        if path.is_file() and path.resolve() != excluded
    )


def tree_lines(paths: list[Path]) -> list[str]:
    lines = ["specs/"]
    children: dict[tuple[str, ...], set[str]] = {}
    for path in paths:
        parts = path.relative_to(SPECS_ROOT).parts
        for depth, part in enumerate(parts):
            children.setdefault(parts[:depth], set()).add(part)

    def append_children(parent: tuple[str, ...], prefix: str) -> None:
        names = sorted(children.get(parent, set()))
        for index, name in enumerate(names):
            current = parent + (name,)
            is_last = index == len(names) - 1
            is_directory = current in children
            connector = "└── " if is_last else "├── "
            suffix = "/" if is_directory else ""
            lines.append(f"{prefix}{connector}{name}{suffix}")
            if is_directory:
                extension = "    " if is_last else "│   "
                append_children(current, prefix + extension)

    append_children((), "")
    return lines


def fence_for(contents: str) -> str:
    runs = [len(match.group(0)) for match in re.finditer(r"`+", contents)]
    return "`" * max(3, max(runs, default=0) + 1)


def render(output: Path) -> str:
    files = source_files(output)
    sections = [
        "# All specifications",
        "",
        "> Generated by `python3 scripts/regenerate_specs_bundle.py`. Do not edit by hand.",
        "",
        f"This bundle contains {len(files)} files from `specs/`, sorted by path.",
        "",
        "## File tree",
        "",
        "```text",
        *tree_lines(files),
        "```",
    ]
    for path in files:
        relative = path.relative_to(ROOT)
        try:
            contents = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            contents = path.read_bytes().hex(" ")
        fence = fence_for(contents)
        language = LANGUAGES.get(path.suffix.lower(), "text")
        sections.extend(
            [
                "",
                f"## `{relative.as_posix()}`",
                "",
                f"{fence}{language}",
                contents.rstrip("\n"),
                fence,
            ]
        )
    return "\n".join(sections) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Bundle every file under specs/ into one Markdown document."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit nonzero if the bundle is missing or stale",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output if args.output.is_absolute() else ROOT / args.output
    expected = render(output)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            print(f"{output.relative_to(ROOT)} is stale; regenerate it", file=sys.stderr)
            return 1
        print(f"{output.relative_to(ROOT)} is up to date")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    print(f"Generated {output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
