export const COMPUTE_COPY = {
  title: "Personal compute",
  description: "SSH targets and personal machines available to cloud-dispatchable work you own.",
  addSshTarget: "Add SSH target",
  connectTarget: "Connect target",
  reconnectTarget: "Reconnect",
  connectSuccess: "Target connected through",
  connectSuccessNoTunnel: "Target connected. Organization cloud work can use it.",
  save: "Save",
  saveSuccess: "Target settings saved.",
  saveError: "Could not save target settings.",
  testConnection: "Test connection",
  testConnectionSuccess: "Connection succeeded through",
  testConnectionError: "Could not reach AnyHarness through SSH.",
  emptyTitle: "No SSH targets yet",
  emptyDescription: "Connect an SSH machine to run cloud-dispatchable work on your own compute.",
  selectTargetTitle: "No target selected",
  selectTargetDescription: "Choose a target from the list to review readiness, launch auth, direct access, and appearance settings.",
  targetFallbackTitle: "Target",
  installCommandLabel: "Run this on the target machine",
  appearanceHelp: "Shown alongside this target's name throughout the app.",
  directSshHelp: "How Desktop tunnels into this target's AnyHarness runtime. These values are stored locally on this Desktop.",
  directSshUnavailable: "Direct SSH access applies to SSH targets. Managed cloud and local targets use their own runtime connection path.",
  directSshNotSshTarget: "This target does not use a Desktop-managed SSH tunnel.",
  archiveTarget: "Archive target",
  archiveConfirm: "Archive this compute target?",
  archiveError: "Could not archive target.",
} as const;
