export const COMPUTE_COPY = {
  title: "Personal compute",
  description: "The machines you own that run your work directly, plus managed cloud runtimes.",
  machinesTitle: "Your machines",
  machinesDescription: "This Mac and every machine you connected. Select one to inspect setup, readiness, access, and agent auth.",
  thisMacFallbackName: "This Mac",
  thisMacKindLabel: "This machine",
  thisMacDetail: "Desktop's own runtime. Always available while the app is running.",
  cloudSectionTitle: "Cloud",
  cloudSectionDescription: "Managed runtimes provisioned and metered by Proliferate.",
  willApplyWhenAttached: "This machine is not attached right now. Changes are saved and apply the next time it attaches.",
  agentAuthTitle: "Agent auth",
  agentAuthDescription: "How agents on this machine authenticate to models.",
  agentAuthUsingDefaults: "Using your defaults",
  agentAuthOverrideCount: (count: number) =>
    count === 1 ? "1 override" : `${count} overrides`,
  agentAuthLoading: "Loading agent auth...",
  agentAuthManage: "Manage agent auth",
  addSshTarget: "Add SSH target",
  connectTarget: "Connect target",
  reconnectTarget: "Reconnect",
  connectSuccess: "Target connected through",
  connectSuccessNoTunnel: "Target connected. Organization cloud work can use it.",
  save: "Save",
  saveSuccess: "Target settings saved.",
  saveError: "Could not save target settings.",
  testConnection: "Test connection",
  testConnectionSuccess: "Connection succeeded through",
  testConnectionError: "Could not reach AnyHarness through SSH.",
  emptyTitle: "No SSH targets yet",
  emptyDescription: "Connect an SSH machine to run cloud-dispatchable work on your own compute.",
  selectTargetTitle: "No target selected",
  selectTargetDescription: "Choose a target from the list to review readiness, launch auth, direct access, and appearance settings.",
  targetFallbackTitle: "Target",
  installCommandLabel: "Run this on the target machine",
  appearanceHelp: "Shown alongside this target's name throughout the app.",
  directSshHelp: "How Desktop tunnels into this target's AnyHarness runtime. These values are stored locally on this Desktop.",
  directSshUnavailable: "Direct SSH access applies to SSH targets. Managed cloud and local targets use their own runtime connection path.",
  directSshNotSshTarget: "This target does not use a Desktop-managed SSH tunnel.",
  archiveTarget: "Archive target",
  archiveConfirm: "Archive this compute target?",
  archiveError: "Could not archive target.",
} as const;
