import { extendTailwindMerge } from "tailwind-merge";

/**
 * The closed semantic `text-*` FONT-SIZE vocabulary generated by the design
 * package (`apps/packages/design/src/tokens.ts` → `dist/theme.css`).
 * tailwind-merge's default config only knows the stock sizes
 * (text-xs…text-9xl), so it classifies unknown `text-*` classes as text
 * COLORS — and then silently drops them whenever a real color (e.g.
 * text-muted-foreground) appears later in the same merge. Every generated size
 * token must be listed here or it will vanish from merged class lists.
 *
 * The stock generic steps (xs/sm/base/lg/xl) are deleted from the theme, so
 * they are deliberately absent rather than merely unlisted.
 *
 * COMPLETENESS IS THE CONTRACT, not the subset anyone happens to use: this list
 * must name EVERY emitted `--text-*` font-size id, including ids that carry no
 * `--line-height` sibling (`chat-meta`). Membership is asserted against the
 * generated theme in appearance-css-drift.test.ts, because an id missing here
 * fails silently and only at the exact call sites the arbitrary-utility bans push
 * consumers toward.
 */
export const TEXT_SIZE_TOKEN_IDS = [
  "ui-sm",
  "ui",
  "chat",
  "chat-meta",
  "composer",
  "body",
  "workspace-title",
  "body-emphasis",
  "heading",
  "title",
  "hero",
  "sidebar-nav",
  "sidebar-row",
  "sidebar-brand",
  "message",
  "readable-code",
  "markdown-inline-code",
] as const;

export const ICON_SIZE_TOKEN_IDS = [
  "status",
  "compact",
  "paired",
  "control",
  "large",
  "display",
] as const;

/**
 * The generated `size-icon-button-*` control-box tiers
 * (`--size-icon-button-sm|md|lg` → `@utility size-icon-button-*` in
 * dist/theme.css, which sets BOTH width and height).
 *
 * These belong to tailwind-merge's stock `size` group, not to a group of their
 * own: `size-icon-button-sm` conflicts with `size-6`, `h-7`, and `w-7` exactly
 * the way `size-5` does, and only membership in `size` carries the stock
 * `size → [w, h]` conflict mapping. Unregistered, a consumer that overrides a
 * component's own `h-7 w-7` with `size-icon-button-sm` gets BOTH in the merged
 * list and loses on generated-CSS source order — the same silent-drop failure
 * mode as an unregistered font size, only inverted (the token survives the
 * merge but never wins the cascade).
 *
 * Locked against the generated theme's emitted utilities in
 * appearance-css-drift.test.ts.
 */
export const ICON_BUTTON_SIZE_TOKEN_IDS = ["sm", "md", "lg"] as const;

/**
 * The one true twMerge: knows the design-package font-size tokens. Import it
 * from here — never from "tailwind-merge" directly. check-design-system.sh
 * enforces this across desktop, web, and the shared UI packages — every
 * workspace that depends on tailwind-merge (mobile is React Native and has
 * no tailwind-merge surface).
 */
export const twMerge = extendTailwindMerge<"icon-size">({
  extend: {
    classGroups: {
      "font-size": [{ text: [...TEXT_SIZE_TOKEN_IDS] }],
      "icon-size": [{ icon: [...ICON_SIZE_TOKEN_IDS] }],
      size: [{ size: ICON_BUTTON_SIZE_TOKEN_IDS.map((step) => `icon-button-${step}`) }],
    },
  },
});
