"""Manifest helpers for sandbox materialization."""

from __future__ import annotations

import json
from dataclasses import dataclass


@dataclass(frozen=True)
class MaterializedSecretManifest:
    kind: str
    env_path: str
    manifest_path: str
    file_paths: tuple[str, ...]

    def to_json_dict(self) -> dict[str, object]:
        return {
            "kind": self.kind,
            "envPath": self.env_path,
            "manifestPath": self.manifest_path,
            "filePaths": list(self.file_paths),
        }


def file_paths_from_manifest(value: dict[str, object]) -> set[str]:
    raw_paths = value.get("filePaths")
    if not isinstance(raw_paths, list):
        return set()
    return {item for item in raw_paths if isinstance(item, str) and item}


def render_manifest_json(
    manifest: MaterializedSecretManifest,
    *,
    versions: dict[str, int],
) -> str:
    payload = {
        **manifest.to_json_dict(),
        "versions": versions,
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def single_quote_shell_value(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def render_env_file(env_vars: dict[str, str]) -> str:
    lines = ["# Generated by Proliferate. Do not edit."]
    for name, value in sorted(env_vars.items()):
        lines.append(f"export {name}={single_quote_shell_value(value)}")
    return "\n".join(lines) + "\n"
